<script lang="ts">
 import Icon from '../components/Icon.svelte';
 import Modal from '../components/Modal.svelte';
 import Badge from '../components/Badge.svelte';
 import AppSelect from '../components/Select.svelte';
 import {demo,api,saveRow,getRow,removeRow,runAction,refreshState,downloadAuthenticated,toast,errorMessage} from '../store.svelte';
 import type {Row} from '../data';

 const providerOptions=[{value:'cloudflare',label:'Cloudflare'},{value:'alidns',label:'阿里云 DNS'},{value:'dnspodcn',label:'腾讯云 DNSPod'},{value:'namesilo',label:'NameSilo'}];
 const caOptions=[{value:'letsencrypt',label:"Let's Encrypt"},{value:'staging',label:"Let's Encrypt 测试环境"},{value:'zerossl',label:'ZeroSSL'},{value:'custom',label:'自定义 ACME'}];
 let tab=$state('certificates'),query=$state(''),busy=$state(''),error=$state('');
 let open=$state(false),providerOpen=$state(false),uploadOpen=$state(false),deployOpen=$state(false),deleteOpen=$state(false);
 let form=$state<Row>({id:''}),provider=$state<Row>({id:''}),selected=$state<Row>({id:''}),ca=$state('letsencrypt'),domains=$state(''),targets=$state<string[]>([]);
 let uploadDomain=$state(''),certificate=$state(''),privateKey=$state(''),uploadTarget=$state('');
 let deleteCollection=$state('certificates'),operationError=$state('');
 const certs=$derived((demo.data.certificates??[]).filter(row=>[row.name,...names(row)].join(' ').toLowerCase().includes(query.toLowerCase())));
 const providers=$derived(demo.data.dnsProviders??[]);
 const providerChoices=$derived(providers.map(row=>({value:row.id,label:`${row.name} · ${providerName(row.provider)}`})));
 const manual=$derived(form.type==='manual'||form.provider==='manual');
 function names(row:Row):string[]{return Array.isArray(row.domains)?row.domains:String(row.domains||row.name||'').split(/[\s,，]+/).filter(Boolean);}
 function providerName(value:string){return providerOptions.find(item=>item.value===String(value).toLowerCase())?.label??value;}
 function caName(row:Row){if(row.materialSource==='manual')return '上传证书';if(row.acmeDirectory?.includes('zerossl'))return 'ZeroSSL';if(row.staging)return "Let's Encrypt 测试";return row.acmeDirectory?'自定义 ACME':"Let's Encrypt";}
 function expiry(row:Row){const time=Date.parse(row.expires);if(!Number.isFinite(time))return {date:'未签发',remaining:'',status:'待签发',kind:'neutral'};const days=Math.ceil((time-Date.now())/86400000);return {date:new Date(time).toLocaleDateString('zh-CN'),remaining:days>0?`${days} 天后到期`:'已过期',status:days<=0?'已过期':days<=30?'即将到期':'有效',kind:days<=0?'danger':days<=30?'warning':'success'};}
 function deployments(row:Row){const tasks=(demo.data.tasks??[]).filter(task=>task.type==='certificate.deploy'&&task.certificateId===row.id&&task.certificateSerial===row.serial);const latest=new Map<string,Row>();for(const task of [...tasks].sort((a,b)=>Date.parse(b.created)-Date.parse(a.created)))if(!latest.has(task.target))latest.set(task.target,task);return [...latest.values()];}
 function serverName(id:string){return demo.data.servers.find(row=>row.id===id)?.name??id;}
 function resultError(result:any){return [result.deploymentError,...(result.deployment_errors??[]).map((item:any)=>`${serverName(item.serverId)}：${item.error}`)].filter(Boolean).join('\n');}
 async function work(key:string,fn:()=>Promise<void>){if(busy)return;busy=key;error='';try{await fn();}catch(cause){error=errorMessage(cause);}finally{busy='';}}
 async function edit(row?:Row){await work('edit',async()=>{form=row?await getRow('certificates',row.id):{id:crypto.randomUUID(),name:'',email:'',challenge:'DNS-01',dnsProviderId:providers[0]?.id??'',httpChallengeHost:'0.0.0.0',httpChallengePort:8080,termsAgreed:false,autoRenew:true,autoDeploy:false,status:'待签发'};domains=names(form).join('\n');ca=form.acmeDirectory?.includes('zerossl')?'zerossl':form.acmeDirectory?'custom':form.staging?'staging':'letsencrypt';targets=[...(form.serverIds??[])];open=true;});}
 async function saveCertificate(issue=false){await work('save',async()=>{const list=domains.split(/[\s,，]+/).filter(Boolean);if(!list.length)throw new Error('请填写至少一个域名');const row:Row={...form,name:form.name?.trim()||list[0],domains:list,serverIds:targets,staging:ca==='staging',acmeDirectory:ca==='zerossl'?'https://acme.zerossl.com/v2/DV90':ca==='custom'?form.acmeDirectory:''};if(!manual&&row.challenge==='DNS-01'&&!row.dnsProviderId&&!form.credentialConfigured&&!form.accessKeySecretConfigured&&!form.secretKeyConfigured)throw new Error('请选择 DNS 提供商');await saveRow('certificates',row);form=await getRow('certificates',row.id);if(issue){const result=await runAction('certificate.issue',form.id,'certificates');operationError=resultError(result);toast(result.message??'证书已签发');}else toast('证书设置已保存');open=false;});}
 async function editProvider(row?:Row){await work('provider-edit',async()=>{provider=row?await getRow('dnsProviders',row.id):{id:crypto.randomUUID(),name:'',provider:'cloudflare'};providerOpen=true;});}
 async function saveProvider(){await work('provider-save',async()=>{const saved=await saveRow('dnsProviders',provider);if(open&&!form.dnsProviderId)form.dnsProviderId=saved.id;providerOpen=false;toast('DNS 提供商已保存');});}
 function startUpload(row?:Row){error='';uploadTarget=row?.id??'';uploadDomain=names(row??{id:''})[0]??'';certificate='';privateKey='';uploadOpen=true;}
 async function readPEM(event:Event,key:boolean){const input=event.currentTarget as HTMLInputElement;const file=input.files?.[0];if(!file)return;if(file.size>(key?128*1024:1024*1024)){error='文件过大';input.value='';return;}try{const value=await file.text();if(key)privateKey=value;else certificate=value;}catch(cause){error=errorMessage(cause);}}
 async function upload(){await work('upload',async()=>{const result=uploadTarget?await runAction('certificate.upload',uploadTarget,'certificates',{certificate,privateKey}):await api('/api/admin/certificates/upload',{method:'POST',body:JSON.stringify({domain:uploadDomain.trim(),cert_pem:certificate,key_pem:privateKey,deploy:false})});operationError=resultError(result);uploadOpen=false;certificate='';privateKey='';await refreshState(true);toast('证书与私钥已验证保存');});}
 async function renew(row:Row){await work(row.id,async()=>{const result=await runAction(row.expires?'certificate.renew':'certificate.issue',row.id,'certificates');operationError=resultError(result);toast(result.message??'证书已签发');});}
 async function toggle(row:Row,key:'autoRenew'|'autoDeploy'){await work(row.id,async()=>{await saveRow('certificates',{...row,[key]:!row[key]});});}
 function startDeploy(row:Row){error='';selected=row;targets=[...(row.serverIds??[])];deployOpen=true;}
 async function deploy(){await work('deploy',async()=>{if(!targets.length)throw new Error('请选择部署服务器');const saved=await saveRow('certificates',{...selected,serverIds:targets});const result=await runAction('certificate.deploy',saved.id,'certificates',{serverIds:targets});operationError=resultError(result);deployOpen=false;toast(result.message);});}
 function startDelete(row:Row,collection:string){error='';selected=row;deleteCollection=collection;deleteOpen=true;}
 async function remove(){await work('delete',async()=>{await removeRow(deleteCollection,selected.id);deleteOpen=false;toast('已删除');});}
 function references(id:string){return (demo.data.certificates??[]).filter(row=>row.dnsProviderId===id).length+(demo.data.servers??[]).filter(row=>row.ddns?.dnsProviderId===id).length;}
</script>

<div class="page-head"><div><h1><Icon name="shield" size={23}/>SSL/TLS 证书管理</h1></div><div class="actions"><button class="icon-button" title="刷新证书" aria-label="刷新证书" disabled={!!busy} onclick={()=>work('refresh',()=>refreshState(true))}><Icon name="refresh"/></button><button class="button primary" disabled={!!busy} onclick={()=>edit()}><Icon name="plus"/>申请证书</button><button class="button" disabled={!!busy} onclick={()=>startUpload()}><Icon name="up"/>上传证书</button></div></div>
<div class="cert-tabs" role="tablist" aria-label="证书管理"><button role="tab" aria-selected={tab==='certificates'} class:active={tab==='certificates'} onclick={()=>{tab='certificates';query='';}}>证书列表 <span>{demo.data.certificates?.length??0}</span></button><button role="tab" aria-selected={tab==='providers'} class:active={tab==='providers'} onclick={()=>{tab='providers';query='';}}>DNS 提供商 <span>{providers.length}</span></button></div>
{#if error&&!open&&!providerOpen&&!uploadOpen&&!deployOpen&&!deleteOpen}<p class="error" role="alert">{error}</p>{/if}
{#if operationError}<div class="operation-error" role="alert"><p>{operationError}</p><button class="icon-button" title="关闭" aria-label="关闭部署错误" onclick={()=>operationError=''}><Icon name="x"/></button></div>{/if}
{#if busy}<p class="muted" role="status">{busy==='save'||certs.some(row=>row.id===busy)?'正在处理，请稍候…':'处理中…'}</p>{/if}
{#if tab==='certificates'}
 <section class="cert-section" aria-label="证书列表"><div class="section-head"><h2>证书列表</h2><div class="search-input cert-search"><Icon name="search"/><input aria-label="搜索域名或名称" placeholder="搜索域名或名称" bind:value={query}/></div></div><div class="cert-table-scroll"><table class="cert-table" class:no-rows={!certs.length}><thead><tr>{#each ['域名','CA','服务器','验证','状态','过期时间','部署','自动续期','自动部署','操作'] as heading}<th>{heading}</th>{/each}</tr></thead><tbody>
 {#each certs as row (row.id)}{@const state=expiry(row)}{@const tasks=deployments(row)}<tr><td class="domains"><button class="domain-link" disabled={!!busy} onclick={()=>edit(row)}>{names(row)[0]||row.name}</button>{#each names(row).slice(1) as domain}<small>{domain}</small>{/each}</td><td title={row.issuer||''}>{caName(row)}</td><td><div class="server-list">{#each row.serverIds??[] as id}<span><Icon name="server" size={13}/>{serverName(id)}</span>{:else}<span class="muted">未指定</span>{/each}</div></td><td><span class="tag">{row.materialSource==='manual'?'上传':row.challenge||'DNS-01'}</span></td><td><Badge value={state.status} kind={state.kind}/>{#if row.lastOperation?.status==='failed'}<small class="expiring" title={row.lastOperation.error}>自动任务失败</small>{/if}</td><td><span>{state.date}</span><small class:expiring={state.kind!=='success'}>{state.remaining}</small></td><td><div class="deployment-list">{#each tasks as task}<a href={'/tasks?detail='+encodeURIComponent(task.id)} title={serverName(task.target)+(task.error?'：'+task.error:'')}><Badge value={task.status}/></a>{:else}<span class="muted">暂无记录</span>{/each}</div></td><td><button class="toggle" class:on={!!row.autoRenew} role="switch" aria-checked={!!row.autoRenew} aria-label={`${names(row)[0]} 自动续期`} title={row.type==='manual'?'上传证书不自动续期':'自动续期'} disabled={!!busy||row.type==='manual'} onclick={()=>toggle(row,'autoRenew')}><i></i></button></td><td><button class="toggle" class:on={!!row.autoDeploy} role="switch" aria-checked={!!row.autoDeploy} aria-label={`${names(row)[0]} 自动部署`} title="自动部署" disabled={!!busy} onclick={()=>toggle(row,'autoDeploy')}><i></i></button></td><td><div class="row-actions"><button class="icon-button" title="编辑证书" aria-label="编辑证书" disabled={!!busy} onclick={()=>edit(row)}><Icon name="edit"/></button>{#if row.type==='manual'}<button class="icon-button" title="更新证书文件" aria-label="更新证书文件" disabled={!!busy} onclick={()=>startUpload(row)}><Icon name="file"/></button>{:else}<button class="icon-button" title={row.expires?'续期证书':'签发证书'} aria-label={row.expires?'续期证书':'签发证书'} disabled={!!busy} onclick={()=>renew(row)}><Icon name="refresh"/></button>{/if}<button class="icon-button" title="部署证书" aria-label="部署证书" disabled={!!busy||!row.serial||state.status==='已过期'} onclick={()=>startDeploy(row)}><Icon name="up"/></button><button class="icon-button" title="下载证书与私钥" aria-label="下载证书与私钥" disabled={!!busy||!row.serial} onclick={()=>work(row.id,()=>downloadAuthenticated(`/api/certificates/${encodeURIComponent(row.id)}/download`,`${names(row)[0]?.replaceAll('*','wildcard')||'certificate'}.zip`))}><Icon name="download"/></button><button class="icon-button danger-action" title="删除证书" aria-label="删除证书" disabled={!!busy} onclick={()=>startDelete(row,'certificates')}><Icon name="trash"/></button></div></td></tr>
 {:else}<tr><td colspan="10"><div class="empty"><Icon name="shield" size={30}/><p>{query?'没有匹配的证书':'暂无证书'}</p>{#if !query}<button class="button" onclick={()=>edit()}><Icon name="plus"/>申请证书</button>{/if}</div></td></tr>{/each}
 </tbody></table></div></section>
{:else}
 <section class="cert-section" aria-label="DNS 提供商列表"><div class="section-head"><h2>DNS 提供商</h2><button class="button primary" disabled={!!busy} onclick={()=>editProvider()}><Icon name="plus"/>添加提供商</button></div><div class="cert-table-scroll"><table class="cert-table providers" class:no-rows={!providers.length}><thead><tr><th>名称</th><th>DNS 服务商</th><th>关联资源</th><th>更新时间</th><th>操作</th></tr></thead><tbody>{#each providers as row (row.id)}<tr><td>{row.name}</td><td>{providerName(row.provider)}</td><td>{references(row.id)}</td><td>{row.updatedAt?new Date(row.updatedAt).toLocaleString('zh-CN'):'-'}</td><td><div class="row-actions"><button class="icon-button" title="编辑 DNS 提供商" aria-label="编辑 DNS 提供商" disabled={!!busy} onclick={()=>editProvider(row)}><Icon name="edit"/></button><button class="icon-button danger-action" title="删除 DNS 提供商" aria-label="删除 DNS 提供商" disabled={!!busy} onclick={()=>startDelete(row,'dnsProviders')}><Icon name="trash"/></button></div></td></tr>{:else}<tr><td colspan="5"><div class="empty"><Icon name="cloud" size={30}/><p>暂无 DNS 提供商</p></div></td></tr>{/each}</tbody></table></div></section>
{/if}

{#snippet serverFields()}
 <fieldset class="server-options full"><legend>部署服务器</legend>{#each demo.data.servers as server}<label><input type="checkbox" bind:group={targets} value={server.id}/><Icon name="server" size={14}/>{server.name}</label>{:else}<p class="muted">暂无服务器</p>{/each}</fieldset>
{/snippet}
{#snippet formError()}{#if error}<p class="error" role="alert">{error}</p>{/if}{/snippet}
<Modal bind:open title={form.recordVersion?'证书设置':'申请证书'} wide><form onsubmit={e=>{e.preventDefault();saveCertificate(!form.recordVersion&&!manual);}}><fieldset disabled={!!busy} class="form-grid form-fields"><label class="field">名称<input bind:value={form.name} placeholder="可选，默认使用主域名"/></label>{#if !manual}<label class="field">CA<AppSelect bind:value={ca} options={caOptions} aria-label="证书颁发机构"/></label>{/if}<label class="field full">域名<textarea bind:value={domains} required rows="3" placeholder="example.com&#10;*.example.com"></textarea></label>{#if !manual}<label class="field">联系邮箱<input type="email" required bind:value={form.email}/></label><label class="field">验证方式<AppSelect bind:value={form.challenge} options={['DNS-01','HTTP-01']} aria-label="验证方式"/></label>{#if form.challenge==='DNS-01'}<label class="field full">DNS 提供商<AppSelect bind:value={form.dnsProviderId} options={providerChoices} aria-label="DNS 提供商" placeholder={form.credentialConfigured||form.accessKeySecretConfigured||form.secretKeyConfigured?'沿用已有独立凭据':'请选择 DNS 提供商'}/><button type="button" class="button small" onclick={()=>editProvider()}><Icon name="plus"/>添加 DNS 提供商</button></label>{:else}<label class="field">主控验证监听 IP<input bind:value={form.httpChallengeHost} required/></label><label class="field">主控验证监听端口<input type="number" min="1" max="65535" bind:value={form.httpChallengePort} required/></label><p class="hint full">域名的公网 80 端口需要转发到此主控端口。</p>{/if}{#if ca==='custom'}<label class="field full">ACME 目录 URL<input type="url" bind:value={form.acmeDirectory} required placeholder="https://ca.example.com/directory"/></label><label class="field full">信任的 CA 证书（可选）<textarea bind:value={form.caCertificatePEM} rows="3"></textarea></label>{/if}{#if ca==='zerossl'||ca==='custom'}<label class="field">EAB 账户 ID<input bind:value={form.eabKid} required={ca==='zerossl'}/></label><label class="field">EAB HMAC 密钥<input type="password" autocomplete="new-password" bind:value={form.eabHmacKey} placeholder={form.eabHmacKeyConfigured?'已保存，留空保留':''} required={ca==='zerossl'&&!form.eabHmacKeyConfigured}/></label>{/if}{#if ca==='staging'}<p class="hint full">测试证书不受浏览器或客户端信任。</p>{/if}{/if}{@render serverFields()}<div class="check-options full">{#if !manual}<label><input type="checkbox" bind:checked={form.autoRenew}/>自动续期</label>{/if}<label><input type="checkbox" bind:checked={form.autoDeploy}/>自动部署</label>{#if !manual}<label><input type="checkbox" bind:checked={form.termsAgreed} required/>同意所选 CA 的服务条款</label>{/if}</div></fieldset>{@render formError()}<div class="modal-actions"><button type="button" class="button" disabled={!!busy} onclick={()=>open=false}>取消</button><button class="button primary" disabled={!!busy}>{busy==='save'?'处理中…':form.recordVersion||manual?'保存设置':'申请证书'}</button></div></form></Modal>

<Modal bind:open={providerOpen} title={provider.recordVersion?'编辑 DNS 提供商':'添加 DNS 提供商'}><form onsubmit={e=>{e.preventDefault();saveProvider();}}><fieldset disabled={!!busy} class="form-grid form-fields"><label class="field full">名称<input bind:value={provider.name} required/></label><label class="field full">DNS 服务商<AppSelect bind:value={provider.provider} options={providerOptions} aria-label="DNS 服务商" disabled={!!provider.recordVersion}/></label>{#each (provider.provider==='alidns'?[['accessKeyId','Access Key ID'],['accessKeySecret','Access Key Secret']]:provider.provider==='dnspodcn'?[['secretId','Secret ID'],['secretKey','Secret Key']]:provider.provider==='namesilo'?[['apiKey','API Key']]:[['apiToken','API Token']]) as [key,label]}<label class="field full">{label}<input type="password" autocomplete="new-password" bind:value={provider[key]} required={!provider[key+'Configured']&&!provider.recordVersion} placeholder={provider[key+'Configured']?'已保存，留空保留':''}/></label>{/each}</fieldset>{@render formError()}<div class="modal-actions"><button class="button" type="button" disabled={!!busy} onclick={()=>providerOpen=false}>取消</button><button class="button primary" disabled={!!busy}>保存</button></div></form></Modal>

<Modal bind:open={uploadOpen} title="上传证书" wide><form onsubmit={e=>{e.preventDefault();upload();}}><fieldset disabled={!!busy} class="form-grid form-fields"><label class="field full">主域名<input bind:value={uploadDomain} required readonly={!!uploadTarget} placeholder="example.com"/></label><label class="field">证书链（PEM）<input type="file" accept=".pem,.crt,.cer" onchange={e=>readPEM(e,false)}/><textarea class="pem" aria-label="证书链 PEM 内容" bind:value={certificate} required rows="8" placeholder="-----BEGIN CERTIFICATE-----"></textarea></label><label class="field">私钥（PEM）<input type="file" accept=".pem,.key" onchange={e=>readPEM(e,true)}/><textarea class="pem" aria-label="私钥 PEM 内容" bind:value={privateKey} required rows="8" placeholder="-----BEGIN PRIVATE KEY-----"></textarea></label></fieldset>{@render formError()}<div class="modal-actions"><button class="button" type="button" disabled={!!busy} onclick={()=>{uploadOpen=false;certificate='';privateKey='';}}>取消</button><button class="button primary" disabled={!!busy}>上传并验证</button></div></form></Modal>

<Modal bind:open={deployOpen} title="部署证书"><form onsubmit={e=>{e.preventDefault();deploy();}}><p class="muted">{names(selected).join('、')}</p><fieldset class="form-fields" disabled={!!busy}>{@render serverFields()}</fieldset>{@render formError()}<div class="modal-actions"><button type="button" class="button" disabled={!!busy} onclick={()=>deployOpen=false}>取消</button><button class="button primary" disabled={!!busy||!targets.length}><Icon name="up"/>部署</button></div></form></Modal>
<Modal bind:open={deleteOpen} title={deleteCollection==='certificates'?'删除证书':'删除 DNS 提供商'}><p>确认删除「{selected.name}」？</p>{#if deleteCollection==='certificates'}<p class="muted space-top">主控保存的证书和私钥将被删除。已部署到服务器的文件不会撤回。</p>{/if}{@render formError()}<div class="modal-actions"><button class="button" disabled={!!busy} onclick={()=>deleteOpen=false}>取消</button><button class="button danger" disabled={!!busy} onclick={remove}>删除</button></div></Modal>

<style>
 h1{display:flex;align-items:center;gap:.65rem;font-size:1.45rem;letter-spacing:0}.cert-tabs{display:flex;gap:1.4rem;border-bottom:1px solid var(--line);margin-bottom:1.5rem}.cert-tabs button{display:flex;align-items:center;gap:.5rem;padding:.8rem .1rem;border:0;border-bottom:2px solid transparent;background:none;color:var(--muted);font-size:.85rem}.cert-tabs button.active{color:var(--foreground);border-bottom-color:var(--primary)}.cert-tabs span{font-size:.7rem;color:var(--muted);font-variant-numeric:tabular-nums}.cert-section{min-width:0}.cert-section h2{font-size:.95rem}.cert-search{width:16rem}.cert-table-scroll{overflow-x:auto;width:100%}.cert-table{width:100%;min-width:1080px;border-collapse:collapse;font-size:.78rem}.cert-table th{font-size:.72rem;color:var(--muted);font-weight:500;text-align:left;padding:.9rem .7rem;border-bottom:1px solid var(--line);white-space:nowrap}.cert-table td{padding:1rem .7rem;border-bottom:1px solid var(--line);vertical-align:middle}.cert-table th:last-child{text-align:right}.cert-table small{display:block;margin-top:.25rem;color:var(--muted);font-size:.7rem}.cert-table small.expiring{color:var(--warning)}.domains{min-width:140px;max-width:240px;overflow-wrap:anywhere}.domain-link{border:0;background:none;color:var(--foreground);text-align:left;padding:0;font-weight:500;overflow-wrap:anywhere}.domain-link:hover{color:var(--primary)}.server-list,.deployment-list{display:flex;flex-direction:column;gap:.4rem}.server-list span{display:flex;gap:.3rem;align-items:center;overflow-wrap:anywhere;max-width:130px}.row-actions{white-space:nowrap}.providers{min-width:640px}.form-fields{border:0;padding:0;min-width:0}.form-fields:disabled{opacity:.65}.server-options{border:1px solid var(--line);padding:.8rem;max-height:220px;overflow:auto;margin-top:.5rem}.server-options legend{font-size:.8rem;color:var(--muted);padding:0 .4rem}.server-options label{display:flex;align-items:center;gap:.5rem;padding:.4rem;overflow-wrap:anywhere;font-size:.8rem}.check-options{display:flex;flex-wrap:wrap;gap:1rem;font-size:.8rem}.check-options label{display:flex;align-items:center;gap:.4rem}.pem{font-family:ui-monospace,monospace;font-size:.72rem;word-break:break-all}.operation-error{display:flex;justify-content:space-between;gap:1rem;padding:.8rem;border:1px solid var(--danger);margin-bottom:1rem}.operation-error p{white-space:pre-wrap;overflow-wrap:anywhere}.danger-action{color:var(--danger)}.empty{min-height:180px}.empty :global(svg){color:var(--muted)}
 @media(max-width:767px){h1{font-size:1.2rem}.page-head{align-items:flex-start;gap:1rem;flex-direction:column}.page-head>.actions{width:100%;flex-wrap:wrap}.cert-search{width:12rem;max-width:65%}.cert-tabs{gap:1rem}.form-grid{grid-template-columns:minmax(0,1fr)}.field{min-width:0}.cert-table{min-width:1000px}.cert-table.no-rows{min-width:0}.no-rows thead{display:none}}
</style>
