<script lang="ts">
 import {page} from '$app/state';
 import ExpandableValue from '../components/ExpandableValue.svelte';
 import {realityNodeChoices,nodeSpeedtestError} from '../reality-client-options';
 import FederationAgent from '../components/FederationAgent.svelte';import NetworkOperations from '../components/NetworkOperations.svelte';
 import AppSelect from '../components/Select.svelte';import Modal from '../components/Modal.svelte';import Badge from '../components/Badge.svelte';import Icon from '../components/Icon.svelte';import {demo,saveRow,getRow,api,runAction,toast,errorMessage,download,copy} from '../store.svelte';
 let pairing=$state<{code:string;pairURL:string;expiresAt:string}|null>(null),pairOpen=$state(false),rotationExpiry=$state('');
 let ddnsEnabled=$state(false),ddnsInterval=$state(300);let lastTask=$state('');let tab=$state('共享与联邦'),busy=$state(false),error=$state(''),name=$state(''),serverId=$state(''),recordId=$state(''),nodeIds=$state<string[]>([]),ownerUrl=$state(''),shareId=$state(''),token=$state(''),domain=$state(''),config=$state(''),zoneId=$state(''),dnsType=$state('A'),dnsToken=$state(''),address=$state(''),endpointId=$state(''),node=$state('{}'),duration=$state(8),parallel=$state('1'),downloadURL=$state(''),resultOpen=$state(false),secret=$state('');
 const tabs=['共享与联邦','Agent 管理分享','转发与隧道','限速管理','Nginx 网站','DDNS 与端口','测速工作台','Telegram Bot','迁移与导入','脚本覆写'];const servers=$derived([{value:'',label:'选择服务器'},...demo.data.servers.map(s=>({value:s.id,label:s.name}))]);
 const shareChoices=$derived(realityNodeChoices(demo.data.nodes,nodeIds));

 $effect(()=>{const requested=page.url.searchParams.get('tab')==='限速与事件'?'限速管理':page.url.searchParams.get('tab');if(requested&&tabs.includes(requested))tab=requested;});
 function switchTab(value:string){tab=value;error='';recordId='';name='';config='';secret='';}
 async function execute(action:string,id?:string,params:Record<string,any>={}){if(busy)return;busy=true;error='';try{const result=await runAction(action,id,undefined,params);lastTask=result.task?.id??'';toast(result.task?'请求已受理，请查看任务执行结果':result.message??'操作已完成');return result;}catch(cause){error=errorMessage(cause);}finally{busy=false;}}
 async function publish(){if(shareChoices.unavailable.length){error='已选节点不再支持，请先移除不可用选择';return;}const result=await execute('federation.publish',undefined,{name,nodeIds});if(result){secret=JSON.stringify(result,null,2);resultOpen=true;}}
 async function connect(){const result=await execute('federation.connect',undefined,{name,ownerUrl,shareId,token});if(result)token='';}
 async function saveSite(apply=false){busy=true;error='';try{if(!name.trim()||!serverId||!config.trim())throw new Error('请填写站点名称、服务器与完整 Nginx 配置');const row=await saveRow('sites',{id:recordId||crypto.randomUUID(),name,domain,serverId,config,status:'草稿'});recordId=row.id;if(apply){const out=await runAction('site.apply',serverId,'sites',{config});lastTask=out.task?.id??'';}toast(apply?'配置已提交，Agent 会校验并重载 Nginx':'站点配置已保存');}catch(cause){error=errorMessage(cause);}finally{busy=false;}}
 async function loadSite(id:string){try{const row=await getRow('sites',id);recordId=id;name=row.name;serverId=row.serverId;domain=row.domain??'';config=row.config??'';}catch(cause){error=errorMessage(cause);}}
 async function saveDNS(sync=false){busy=true;error='';try{const server=demo.data.servers.find(s=>s.id===serverId);if(!server)throw new Error('请选择服务器');const providerId=server.ddns?.dnsProviderId||'ddns-'+serverId;const prior=demo.data.dnsProviders?.find(s=>s.id===providerId);if(!dnsToken&&!prior)throw new Error('请填写 Cloudflare DNS 编辑令牌');await saveRow('dnsProviders',{id:providerId,name:'DDNS · '+server.name,provider:'cloudflare',...(dnsToken?{apiToken:dnsToken}:{})});await saveRow('servers',{id:server.id,name:server.name,ddns:{enabled:ddnsEnabled,interval:ddnsInterval,provider:'cloudflare',dnsProviderId:providerId,name:domain,type:dnsType,zoneId,ttl:120,proxied:false}});dnsToken='';if(sync)await runAction('ddns.sync',server.id,'servers',{address});toast(sync?'DNS 记录已核对更新':'DDNS 配置已保存');}catch(cause){error=errorMessage(cause);}finally{busy=false;}}
 function loadDNS(id:string){serverId=id;const ddns=demo.data.servers.find(s=>s.id===id)?.ddns??{};ddnsEnabled=ddns.enabled===true;ddnsInterval=ddns.interval??300;domain=ddns.name??'';zoneId=ddns.zoneId??'';dnsType=ddns.type??'A';dnsToken='';address='';}
 async function createEndpoint(){busy=true;error='';try{if(!name.trim())throw new Error('请填写测速端名称');const row=await saveRow('endpoints',{id:crypto.randomUUID(),name,status:'启用'});endpointId=row.id;name='';toast('测速端已创建');}catch(cause){error=errorMessage(cause);}finally{busy=false;}}
 async function enrollment(){busy=true;error='';try{const result=await api('/api/home/'+encodeURIComponent(endpointId)+'/enrollment');secret=JSON.stringify(result.config,null,2);resultOpen=true;}catch(cause){error=errorMessage(cause);}finally{busy=false;}}
 async function createPairing(){if(busy||!endpointId)return;busy=true;error='';try{const result=await api('/api/home/'+encodeURIComponent(endpointId)+'/pairing',{method:'POST',body:'{}'});pairing={code:result.code,pairURL:result.pairURL,expiresAt:result.expiresAt};pairOpen=true;}catch(cause){error=errorMessage(cause);}finally{busy=false;}}
 async function rotateEndpoint(){if(busy||!endpointId)return;busy=true;error='';try{const result=await api('/api/home/'+encodeURIComponent(endpointId)+'/rotate',{method:'POST',body:'{}'});lastTask=result.task?.id??'';rotationExpiry=new Date(Number(result.previousExpiresAt)*1000).toLocaleString();toast('新凭据及轮换任务已保存，请核对端点执行结果');}catch(cause){error=errorMessage(cause);}finally{busy=false;}}
 async function speedtest(){try{const parsed=JSON.parse(node);const validation=nodeSpeedtestError(parsed);if(validation)throw new Error(validation);await execute('speedtest.run',endpointId,{node:parsed,url:downloadURL,duration_seconds:duration,parallel:Number(parallel)});}catch(cause){error=errorMessage(cause);}}
 $effect(()=>{if(!resultOpen)secret='';});
 $effect(()=>{if(!pairOpen)pairing=null;});
</script>
<div class="page-head"><div><div class="eyebrow">工作区 / 扩展能力</div><h1>让连接更完整</h1><p>管理节点分享、网站、动态 DNS 与家用测速端。</p></div></div>
<div class="settings-grid"><nav class="settings-nav" aria-label="扩展分类">{#each tabs as item}<button class:active={tab===item} onclick={()=>switchTab(item)}>{item}</button>{/each}</nav><section class="card padded"><div class="section-head"><h2>{tab}</h2><Icon name="layers"/></div>{#if lastTask}<p class="hint space-top">已提交任务 · <a href={`/tasks?detail=${encodeURIComponent(lastTask)}`}>查看执行结果</a></p>{/if}{#if error}<div class="status-banner space-top" role="alert">{error}</div>{/if}
{#if tab==='共享与联邦'}<p class="muted">向另一台 ASWired 主控分享明确选择的节点，或接收其分享。分享包含节点连接凭据。</p><label class="field space-top">名称<input bind:value={name}/></label><h3 class="space-top">发布节点分享</h3><div class="stack space-top">{#each shareChoices.available as n}<label class="tag"><input type="checkbox" bind:group={nodeIds} value={n.id}/>{n.name}</label>{:else}<p class="hint">先在节点库添加 VLESS TCP REALITY 节点。</p>{/each}{#each shareChoices.unavailable as n}<label class="tag"><input type="checkbox" bind:group={nodeIds} value={n.id}/>{n.name} <small class="muted">不再支持，请取消选择</small></label>{/each}</div><button class="button primary space-top" disabled={busy||!nodeIds.length} onclick={publish}>发布分享</button><h3 class="space-top">接收节点分享</h3><div class="form-grid space-top"><label class="field">对方主控地址<input type="url" bind:value={ownerUrl}/></label><label class="field">分享标识<input bind:value={shareId}/></label><label class="field full">分享令牌<input type="password" autocomplete="off" bind:value={token}/></label></div><button class="button space-top" disabled={busy||!ownerUrl||!shareId||!token} onclick={connect}>连接并同步</button><div class="stack space-top">{#each (demo.data.shares??[]).filter(row=>row.scope!=='agent_management') as share}<div class="car-summary"><div><strong>{share.name}</strong><small>{share.direction==='owner'?'我发布的分享':'接收的分享'} · {share.nodes??0} 个节点</small></div><Badge value={share.status}/>{#if share.direction==='owner'}<button class="button small" disabled={busy} onclick={()=>execute('federation.revoke',share.id)}>撤销</button>{:else}<button class="button small" disabled={busy} onclick={()=>execute('federation.sync',share.id)}>同步</button><button class="button small" disabled={busy} onclick={()=>execute('federation.disconnect',share.id)}>断开</button>{/if}</div>{/each}</div>
{:else if tab==='Agent 管理分享'}<FederationAgent/>{:else if tab==='转发与隧道'}<NetworkOperations/>{:else if tab==='限速管理'}<p class="muted space-top">查看现有限速规则，以及触发处罚的用户、原因和解除记录。</p><a href="/limits" class="button primary space-top">打开限速管理</a>{:else if tab==='Nginx 网站'}<p class="muted">保存完整 Nginx 配置，由所选 Agent 检查并重载。Agent 须事先设置本机 Nginx 配置路径。</p><div class="form-grid space-top"><label class="field">站点名称<input bind:value={name}/></label><label class="field">服务器<AppSelect bind:value={serverId} options={servers} aria-label="站点服务器"/></label><label class="field full">域名备注<input bind:value={domain}/></label><label class="field full">完整 Nginx 配置<textarea class="code-editor" spellcheck="false" bind:value={config}></textarea></label></div><div class="actions space-top"><button class="button" disabled={busy} onclick={()=>saveSite()}>保存配置</button><button class="button primary" disabled={busy} onclick={()=>saveSite(true)}>校验并重载</button></div>{#each demo.data.sites??[] as site}<div class="car-summary"><strong>{site.name}</strong><button class="button small" onclick={()=>loadSite(site.id)}>编辑</button></div>{/each}
{:else if tab==='DDNS 与端口'}<p class="muted">将选定服务器地址更新到 Cloudflare A / AAAA 记录。可启用周期同步，并在服务器详情查看最近更新结果。</p><div class="form-grid space-top"><label class="field">服务器<AppSelect value={serverId} onchange={loadDNS} options={servers} aria-label="DDNS服务器"/></label><label class="field">DNS 类型<AppSelect bind:value={dnsType} options={['A','AAAA']} aria-label="DNS类型"/></label><label class="field">主机域名<input bind:value={domain}/></label><label class="field">自动同步间隔（秒）<input type="number" min="60" max="86400" bind:value={ddnsInterval}/></label><label class="tag"><input type="checkbox" bind:checked={ddnsEnabled}/>启用周期同步</label><label class="field">Cloudflare Zone ID<input bind:value={zoneId}/></label><label class="field full">DNS 编辑令牌（留空保留已保存令牌）<input type="password" autocomplete="off" bind:value={dnsToken}/></label><label class="field full">本次更新 IP（留空使用服务器地址）<input bind:value={address}/></label></div><div class="actions space-top"><button class="button" disabled={busy||!serverId} onclick={()=>saveDNS()}>保存配置</button><button class="button primary" disabled={busy||!serverId} onclick={()=>saveDNS(true)}>同步 DNS</button><button class="button" disabled={busy||!serverId} onclick={()=>execute('server.ports.check',serverId)}>检查端口</button></div>
{:else if tab==='测速工作台'}<p class="muted">在家庭或办公网络运行测速端 Agent，再通过该端测试指定节点。</p><div class="actions space-top"><input aria-label="测速端名称" bind:value={name} placeholder="测速端名称"/><button class="button" disabled={busy} onclick={createEndpoint}>新增测速端</button></div><label class="field space-top">测速端<AppSelect bind:value={endpointId} options={[{value:'',label:'选择测速端'},...(demo.data.endpoints??[]).map(e=>({value:e.id,label:e.name}))]} aria-label="测速端"/></label><div class="actions space-top"><button class="button" disabled={busy||!endpointId} onclick={enrollment}>读取配对配置</button><button class="button primary" disabled={busy||!endpointId} onclick={createPairing}>生成一次性配对码</button><button class="button" disabled={busy||!endpointId} onclick={rotateEndpoint}>轮换连接凭据</button></div><p class="hint space-top">凭据轮换通过真实任务下发，旧凭据保留 15 分钟，期间须确认端点已持久保存新身份。{#if rotationExpiry}本次旧凭据截止：{rotationExpiry}。{/if}</p><label class="field space-top">节点 JSON（Clash）<textarea class="code-editor" spellcheck="false" bind:value={node}></textarea></label><label class="field">下载测试地址<input type="url" bind:value={downloadURL}/></label><label class="field">持续时间 / 秒<input type="number" min="1" max="30" bind:value={duration}/></label><label class="field">并发<AppSelect bind:value={parallel} options={['1','8']} aria-label="测速并发"/></label><p class="hint">会通过所选节点下载测试内容，达到持续时间后停止。</p><button class="button primary space-top" disabled={busy||!endpointId||!downloadURL} onclick={speedtest}>开始测速</button><a href="/tasks" class="quiet-link space-top">查看实际执行结果</a>
{:else if tab==='Telegram Bot'}<p class="muted space-top">在通知设置中填写 Bot Token 与接收者，再发送测试通知。</p><a href="/settings" class="button primary space-top">打开通知设置</a>
{:else if tab==='迁移与导入'}<p class="muted space-top">ASWired 备份在系统设置中上传恢复；标准节点订阅在外部订阅页面导入同步。</p><div class="actions space-top"><a href="/settings" class="button">备份与恢复</a><a href="/sources?new" class="button primary">导入标准订阅</a></div>
{:else}<p class="muted space-top">在规则与模板中保存并校验脚本，将脚本绑定到需要覆写的套餐实例。</p><a href="/templates" class="button primary space-top">打开规则与模板</a>{/if}</section></div>
<Modal bind:open={resultOpen} title="保存连接配置" description="以下内容包含连接凭据，请仅交给获授权的使用者。" wide>{#key secret}<ExpandableValue value={secret} label="连接配置详情" force />{/key}<div class="modal-actions"><button class="button" onclick={()=>copy(secret)}>复制</button><button class="button" onclick={()=>download('aswired-connection.json',secret,'application/json')}>下载配置</button><button class="button primary" onclick={()=>resultOpen=false}>关闭</button></div></Modal>
<Modal bind:open={pairOpen} title="家用端一次性配对码" description="配对码只显示本次，10 分钟有效，成功配对后立即失效。">{#if pairing}<label class="field">主控配对地址<input value={pairing.pairURL} readonly/></label><label class="field space-top">配对码<input class="mono" value={pairing.code} readonly/></label><p class="hint space-top">到期时间：{new Date(pairing.expiresAt).toLocaleString()}。家用 Agent 使用 -pair-url 与 -pair-code 配对。运行前仍需在本机配置固定 mihomo 二进制及其 SHA256。</p><div class="modal-actions"><button class="button" onclick={()=>copy(pairing!.code)}>复制配对码</button><button class="button" onclick={()=>copy(pairing!.pairURL)}>复制地址</button><button class="button" onclick={()=>download('aswired-home-pairing.txt',`配对地址：${pairing!.pairURL}\n配对码：${pairing!.code}\n到期：${pairing!.expiresAt}`)}>保存配对信息</button><button class="button primary" onclick={()=>pairOpen=false}>已保存</button></div>{/if}</Modal>
