<script lang="ts">
 import {onMount} from 'svelte';
 import Icon from '../components/Icon.svelte';
 import Modal from '../components/Modal.svelte';
 import Badge from '../components/Badge.svelte';
 import {api,demo,copy,toast,errorMessage,runAction} from '../store.svelte';
 import type {Row} from '../data';
 let rows=$state<Row[]>([]), templates=$state<Row[]>([]), loading=$state(true), busy=$state(false), error=$state('');
 let creator=$state('全部创建用户'), externalOpen=$state(true), editorOpen=$state(false), detailOpen=$state(false), deleteOpen=$state(false);
 let form=$state<Row>({id:'',recordVersion:0,name:'',description:'',templateId:'',expiresAt:''}), detail=$state<Row|null>(null), selectedDelete=$state<Row|null>(null);
 const filtered=$derived(rows.filter(row=>creator==='全部创建用户'||row.creator===creator));
 const creators=$derived([...new Set(rows.map(row=>String(row.creator??'')))].filter(Boolean));
 const formatName=(value:any)=>({clash:'Clash',surge:'Surge',loon:'Loon'}[String(value)]??String(value??'').toUpperCase());
 const date=(value:any)=>value?new Date(value).toLocaleString('zh-CN',{hour12:false}):'-';
 const percent=(row:Row)=>row.metered&&row.limit?Math.min(100,Number(row.used??0)/Number(row.limit)*100):0;
 onMount(()=>{void load();});
 async function load(){loading=true;error='';try{const [data,choice]=await Promise.all([api('/api/generated-subscriptions'),api('/api/templates/options')]);rows=data.rows??[];templates=choice.templates??[];}catch(cause){error=errorMessage(cause);}finally{loading=false;}}
 function edit(row:Row){form={...row};editorOpen=true;}
 async function save(){if(busy)return;busy=true;error='';try{await api('/api/generated-subscriptions/'+encodeURIComponent(form.id),{method:'PUT',body:JSON.stringify({recordVersion:form.recordVersion,name:form.name,description:form.description,templateId:form.templateId,expiresAt:form.expiresAt!==rows.find(item=>item.id===form.id)?.expiresAt?form.expiresAt||undefined:undefined})});editorOpen=false;toast('订阅已更新');await load();}catch(cause){error=errorMessage(cause);}finally{busy=false;}}
 async function show(row:Row){try{const data=await api('/api/generated-subscriptions/'+encodeURIComponent(row.id));detail=data.row;detailOpen=true;}catch(cause){toast(errorMessage(cause));}}
 async function remove(){if(!selectedDelete||busy)return;busy=true;try{await api('/api/generated-subscriptions/'+encodeURIComponent(selectedDelete.id),{method:'DELETE',body:JSON.stringify({recordVersion:selectedDelete.recordVersion})});deleteOpen=false;toast('订阅已撤销');await load();}catch(cause){toast(errorMessage(cause));}finally{busy=false;}}
 async function move(row:Row,direction:number){const visible=filtered.findIndex(item=>item.id===row.id),target=filtered[visible+direction];if(!target||busy)return;const index=rows.findIndex(item=>item.id===row.id),next=rows.findIndex(item=>item.id===target.id);const copyRows=[...rows],swap=copyRows[next];copyRows[next]=copyRows[index];copyRows[index]=swap;busy=true;try{await api('/api/generated-subscriptions/order',{method:'POST',body:JSON.stringify({rows:copyRows.map(item=>({id:item.id,recordVersion:item.recordVersion}))})});await load();}catch(cause){toast(errorMessage(cause));}finally{busy=false;}}
 function localDate(value:string){const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}
 async function updateTemplate(row:Row,templateId:string){if(busy)return;busy=true;try{await api('/api/generated-subscriptions/'+encodeURIComponent(row.id),{method:'PUT',body:JSON.stringify({recordVersion:row.recordVersion,templateId})});await load();toast('模板已更新');}catch(cause){toast(errorMessage(cause));await load();}finally{busy=false;}}
 async function syncSources(sources:Row[]=demo.data.sources??[]){if(busy)return;busy=true;let succeeded=0;const failures:string[]=[];try{for(const source of sources){try{await runAction('source.sync',source.id,'sources');succeeded++;}catch(cause){failures.push(source.name+': '+errorMessage(cause));}}toast(`已完成 ${succeeded} 个订阅源同步${failures.length?'；失败：'+failures.join('；'):''}`);}finally{busy=false;}}
</script>
<div class="page-head"><div><div class="eyebrow">工作区 / 订阅</div><h1>订阅管理</h1><p>已生成的订阅文件与外部订阅源。</p></div><a class="button primary" href="/subscription-generator"><Icon name="plus"/>生成订阅</a></div>
{#if error}<p class="error" role="alert">{error}</p>{/if}
<section class="card padded generated-card"><div class="section-head"><div><h2>订阅列表 ({filtered.length})</h2><p class="muted">已添加的订阅文件</p></div><label class="filter"><span class="sr-only">创建用户</span><select bind:value={creator}><option>全部创建用户</option>{#each creators as item}<option value={item}>{item}</option>{/each}</select></label></div>
<div class="table-scroll"><table aria-label="生成订阅列表"><thead><tr><th>订阅名称</th><th>说明</th><th>创建用户</th><th>最后更新</th><th>自定义链接</th><th>模板</th><th>流量</th><th>操作</th></tr></thead><tbody>
{#each filtered as row,index (row.id)}<tr><td><button class="identity link-button" onclick={()=>show(row)}><span class="soft-icon"><Icon name="rss"/></span><strong>{row.name||'ASWired'}</strong></button><small class="subline">{formatName(row.format)} · {row.nodeCount} 个节点</small></td><td class="description">{row.description||'-'}</td><td><span class="creator">{row.creator}</span></td><td>{date(row.updatedAt||row.createdAt)}</td><td>{#if row.hasLink}<button class="quiet-link" onclick={()=>show(row)}><Icon name="link"/>查看链接</button>{:else}<span class="muted">旧版链接（需重新生成以查看）</span>{/if}</td><td><select class="template-select" value={row.templateId??''} disabled={busy} onchange={e=>updateTemplate(row,e.currentTarget.value)}><option value="">选择模板</option>{#each templates.filter(item=>String(item.type).toLowerCase()===String(row.format)) as item}<option value={item.id}>{item.name}</option>{/each}</select></td><td>{#if row.metered}<div class="usage"><div class="usage-bar"><i style={'width:'+percent(row)+'%'}></i></div><small>{Number(row.used??0).toFixed(1)} / {row.limit} GB</small></div>{:else}<span class="muted">未计量</span>{/if}</td><td><div class="row-actions"><button class="icon-button" title="上移" aria-label={'上移 '+row.name} disabled={busy||index===0} onclick={()=>move(row,-1)}><Icon name="up"/></button><button class="icon-button" title="下移" aria-label={'下移 '+row.name} disabled={busy||index===filtered.length-1} onclick={()=>move(row,1)}><Icon name="down"/></button><button class="icon-button" title="编辑设置" aria-label={'设置 '+row.name} onclick={()=>edit(row)}><Icon name="settings"/></button><button class="icon-button" title="编辑" aria-label={'编辑 '+row.name} onclick={()=>edit(row)}><Icon name="edit"/></button><button class="icon-button danger" title="撤销" aria-label={'撤销 '+row.name} onclick={()=>{selectedDelete=row;deleteOpen=true;}}><Icon name="trash"/></button></div></td></tr>{:else}<tr><td colspan="8"><div class="empty">{loading?'正在读取订阅…':'暂无已生成订阅，先生成一个订阅文件。'}</div></td></tr>{/each}</tbody></table></div></section>
<section class="card padded external-card"><button class="collapse-head" aria-expanded={externalOpen} onclick={()=>externalOpen=!externalOpen}><span><Icon name="external"/> <strong>外部订阅 ({demo.data.sources?.length??0})</strong><small>管理从节点管理导入的外部订阅源，用于同步节点</small></span><Icon name={externalOpen?'chevron':'right'}/></button>{#if externalOpen}<div class="external-body"><div class="external-actions"><button class="button" disabled={busy||!(demo.data.sources?.length)} onclick={()=>syncSources()}><Icon name="refresh"/>同步所有订阅</button><a class="button" href="/sources"><Icon name="settings"/>管理订阅源</a></div>{#if demo.data.sources?.length}<div class="source-list">{#each demo.data.sources as source}<div class="source-row"><span class="soft-icon"><Icon name="link"/></span><div><strong>{source.name}</strong><small>{source.format??'自动识别'} · {source.nodes??0} 个节点 · {source.updated??'尚未同步'}</small></div><Badge value={source.status??'启用'}/><button class="icon-button" aria-label={'同步 '+source.name} disabled={busy} onclick={()=>syncSources([source])}><Icon name="refresh"/></button></div>{/each}</div>{:else}<div class="empty">暂无外部订阅，请在外部订阅页面添加。</div>{/if}</div>{/if}</section>
<Modal bind:open={editorOpen} title="编辑订阅" description="更新后会保留原链接凭据与权限范围。" wide><form onsubmit={e=>{e.preventDefault();save();}}><div class="form-grid"><label class="field full">订阅名称<input bind:value={form.name} maxlength="200" required/></label><label class="field full">说明<textarea bind:value={form.description} maxlength="2000" rows="3"></textarea></label><label class="field">到期时间<input type="datetime-local" value={form.expiresAt?localDate(form.expiresAt):''} onchange={e=>form.expiresAt=e.currentTarget.value?new Date(e.currentTarget.value).toISOString():''}/></label><label class="field">模板<select bind:value={form.templateId}><option value="">默认模板</option>{#each templates.filter(item=>String(item.type).toLowerCase()===String(form.format)) as item}<option value={item.id}>{item.name}</option>{/each}</select></label></div><div class="modal-actions"><button type="button" class="button" onclick={()=>editorOpen=false}>取消</button><button class="button primary" disabled={busy}>保存修改</button></div></form></Modal>
<Modal bind:open={detailOpen} title={detail?.name??'订阅详情'} description="链接仅在显式打开详情时读取。" wide>{#if detail}<label class="field">自定义链接<input readonly value={detail.url??'暂不可用'} /></label><div class="modal-actions"><button class="button" disabled={!detail.url} onclick={()=>{if(detail?.url)void copy(new URL(detail.url,location.origin).href);}}><Icon name="copy"/>复制链接</button><a class="button" href="/subscription-generator"><Icon name="edit"/>重新生成</a><button class="button" onclick={()=>detailOpen=false}>关闭</button></div>{/if}</Modal>
<Modal bind:open={deleteOpen} title="撤销订阅" description="撤销后链接立即失效，历史记录不会再出现在列表中。"><p>确认撤销「{selectedDelete?.name}」？</p><div class="modal-actions"><button class="button" onclick={()=>deleteOpen=false}>取消</button><button class="button danger" disabled={busy} onclick={remove}>确认撤销</button></div></Modal>
<style>
 h1{font-size:1.45rem;letter-spacing:0}h2{font-size:1rem;letter-spacing:0;margin:0}.generated-card,.external-card{overflow:hidden}.section-head{display:flex;justify-content:space-between;align-items:flex-start;gap:1rem;margin-bottom:1rem}.section-head p{margin:.25rem 0 0;font-size:.78rem}.filter select,.template-select{border:1px solid var(--line);background:var(--background);color:var(--foreground);padding:.5rem .7rem;border-radius:4px}.generated-card table{min-width:1120px}.generated-card td,.generated-card th{vertical-align:middle;white-space:nowrap}.generated-card td.description{max-width:170px;overflow:hidden;text-overflow:ellipsis}.identity.link-button{border:0;background:none;padding:0;display:flex;align-items:center;gap:.55rem;color:var(--foreground);font-weight:600}.subline{display:block;margin:.28rem 0 0 2.2rem;color:var(--muted);font-size:.7rem}.creator{background:color-mix(in srgb,var(--primary) 14%,transparent);padding:.28rem .45rem;font-size:.72rem}.quiet-link{display:inline-flex;align-items:center;gap:.3rem;border:0;background:none;color:var(--primary);font-size:.75rem}.usage{min-width:90px}.usage-bar{height:6px;border-radius:8px;background:color-mix(in srgb,var(--primary) 14%,var(--background));overflow:hidden}.usage-bar i{display:block;height:100%;background:var(--primary)}.usage small{font-size:.68rem;color:var(--muted)}.row-actions{display:flex;gap:.2rem}.collapse-head{width:100%;display:flex;align-items:center;justify-content:space-between;border:0;background:none;color:var(--foreground);text-align:left;padding:0}.collapse-head>span{display:flex;align-items:center;gap:.55rem}.collapse-head small{display:block;color:var(--muted);font-size:.75rem;font-weight:400;margin-left:1.7rem;margin-top:.25rem}.external-body{padding-top:1.2rem}.external-actions{display:flex;justify-content:flex-end;gap:.5rem;margin-bottom:1rem}.source-list{display:grid;gap:.4rem}.source-row{display:flex;align-items:center;gap:.7rem;border-top:1px solid var(--line);padding:.7rem 0}.source-row>div{flex:1;min-width:0}.source-row strong,.source-row small{display:block}.source-row small{color:var(--muted);font-size:.72rem;margin-top:.2rem}@media(max-width:767px){.section-head{flex-direction:column}.filter,.filter select{width:100%}.external-actions{justify-content:flex-start;flex-wrap:wrap}.collapse-head small{white-space:normal}.generated-card table{min-width:1050px}}
</style>
