<script lang="ts">
 import {formatNumber} from '../format';
 import {onMount} from 'svelte';import {api,demo,errorMessage} from '../store.svelte';import Badge from '../components/Badge.svelte';import type {Row} from '../data';
 let effective=$state<Row[]>([]),events=$state<Row[]>([]),busy=$state(false),error=$state(''),tab=$state('当前限制');let stopped=false,timer:ReturnType<typeof setTimeout>|undefined;
 const name=(collection:string,id:string)=>(demo.data[collection]??[]).find(row=>row.id===id)?.name??id??'—';
 const speed=(value:unknown)=>{const display=formatNumber(value);return display==='—'?'未知':Number(value)===0?'不限':`${display} Mbps`;};
 async function refresh(){if(busy)return;busy=true;error='';try{const [limits,history]=await Promise.all([api('/api/limits/effective'),api('/api/limits/events')]);if(!stopped){effective=limits.rows??[];events=history.rows??[];}}catch(cause){if(!stopped)error=errorMessage(cause);}finally{busy=false;if(!stopped)timer=setTimeout(refresh,5000);}}
 onMount(()=>{refresh();return()=>{stopped=true;if(timer)clearTimeout(timer);};});
</script>
<div class="page-head"><div><div class="eyebrow">运行状态 / 速度与行为</div><h1>限速与事件</h1><p>查看主控计算的下载限制与 Agent 执行回报，以及触发、释放和额度事件。</p></div><button class="button" disabled={busy} onclick={()=>{if(timer)clearTimeout(timer);refresh();}}>刷新</button></div>
{#if error}<p class="error" role="alert">{error}</p>{/if}<div class="tabs">{#each ['当前限制','事件记录'] as item}<button class:active={tab===item} onclick={()=>tab=item}>{item}</button>{/each}</div>
<section class="card no-pad"><div class="table-scroll"><table><thead><tr>{#if tab==='当前限制'}<th>成员 / 服务器</th><th>计算下载上限</th><th>行为状态</th><th>采样</th><th>执行确认</th>{:else}<th>时间</th><th>成员</th><th>事件</th><th>原因 / 来源</th><th>下载限制</th>{/if}</tr></thead><tbody>{#if tab==='当前限制'}{#each effective as row}<tr><td><strong>{name('members',row.userId)}</strong><small class="muted">{name('servers',row.serverId)}</small></td><td>{row.disabled?'凭据已停用':speed(row.effectiveMbps)}</td><td>{row.behaviorActive?`执行中 · ${row.ruleId}`:'未触发'}{#if row.until}<small class="muted">至 {row.until}</small>{/if}</td><td>{row.sampleValid?speed(row.sampleMbps):'无有效连续采样'}{#if row.sampleReason}<small class="muted">{row.sampleReason}</small>{/if}</td><td><Badge value={row.enforcementAvailable===false?'Agent 不支持':row.applied?'已应用':row.executionStatus??'等待回报'} kind={row.applied?'success':'neutral'}/>{#if row.taskId&&demo.user?.role==='admin'}<a class="quiet-link" href={`/tasks?detail=${encodeURIComponent(row.taskId)}`}>查看任务</a>{/if}</td></tr>{:else}<tr><td colspan="5"><div class="empty">尚无计算或执行记录</div></td></tr>{/each}{:else}{#each events as row}<tr><td>{row.at}</td><td>{name('members',row.userId)}</td><td>{row.type}</td><td>{row.reason}<small class="muted">{row.source}</small></td><td>{speed(row.limitMbps)}</td></tr>{:else}<tr><td colspan="5"><div class="empty">尚无限速事件</div></td></tr>{/each}{/if}</tbody></table></div></section>
<p class="hint space-top">主控计算值与节点已生效状态分别展示。采样缺口、核心重启或数据不完整时，不把缺失样本当成超速证据。此页面仅管理员可用。</p>
