<script lang="ts">
 import {onMount} from 'svelte';
 import {DropdownMenu} from 'bits-ui';
 import Icon from '../components/Icon.svelte';
 import Modal from '../components/Modal.svelte';
 import AppSelect from '../components/Select.svelte';
 import BehaviorEditor from '../components/BehaviorEditor.svelte';
 import RegistrationInvites from '../components/RegistrationInvites.svelte';
 import {demo,api,saveRow,getRow,refreshState,copy,toast,errorMessage,returnToLogin} from '../store.svelte';
 import type {Row} from '../data';

 let rows=$state<Row[]>([]),loading=$state(false),busy=$state(false),error=$state(''),dialogError=$state(''),search=$state(''),planFilter=$state('all'),view=$state('full'),page=$state(0);
 let mode=$state(''),selected=$state<Row|null>(null),form=$state<Row>({id:''}),behavior=$state(''),quotas=$state(''),note=$state(''),password=$state(''),code=$state(''),command=$state(''),confirmed=$state(false),subscriptionId=$state(''),planId=$state(''),expires=$state(''),days=$state(30);
 let dialogOpen=$state(false);
 $effect(()=>{if(!dialogOpen){mode='';password='';command='';}});
 const subs=(row:Row):Row[]=>row.subscriptions??[];
 const plans=$derived(demo.data.plans??[]);
 const enabledPlans=$derived(plans.filter(p=>!['停用','暂停','草稿','disabled'].includes(p.status)));
 const filtered=$derived(rows.filter(row=>(planFilter==='all'||planFilter==='none'&&!subs(row).length||subs(row).some(s=>s.planId===planFilter))&&[row.username,row.name,row.note,row.email,...subs(row).map(s=>s.plan)].join(' ').toLowerCase().includes(search.trim().toLowerCase())));
 const visible=$derived(filtered.slice(page*25,page*25+25));
 const availablePlans=$derived(enabledPlans.filter(p=>!selected||!subs(selected).some(s=>s.planId===p.id)));
 const titles:Record<string,string>={create:'新增用户',edit:'编辑用户',note:'修改备注',password:'重置密码',status:'更改用户状态',delete:'删除用户',bind:'绑定套餐',renew:'续费',code:'修改用户短码',telegram:'绑定 Telegram',unbind:'解绑 Telegram'};
 $effect(()=>{search;planFilter;view;page=0;});
 $effect(()=>{if(page>0&&page*25>=filtered.length)page=Math.max(0,Math.ceil(filtered.length/25)-1);});
 onMount(()=>{void load();});
 async function load(){if(loading)return;loading=true;error='';try{rows=(await api<{rows:Row[]}>('/api/members/management')).rows;}catch(cause){error=errorMessage(cause);}finally{loading=false;}}
 function isDisabled(row:Row){return ['暂停','停用','禁用'].includes(row.status);}
 function usage(sub:Row){return sub.used==null?'未知':Number(sub.used).toFixed(2);}
 function percent(sub:Row){return sub.used==null||!sub.limit?0:Math.min(100,Math.max(0,Number(sub.used)/Number(sub.limit)*100));}
 function date(raw:string){if(!raw)return '长期';const d=new Date(raw);return Number.isNaN(d.valueOf())?'日期无效':d.toLocaleDateString('zh-CN');}
 function expiry(raw:string){if(!raw)return '长期有效';const remaining=Math.ceil((new Date(raw).valueOf()-Date.now())/86400000);return remaining<0?'已到期':remaining===0?'今日到期':`${remaining} 天后到期`;}
 async function open(next:string,row?:Row){if(busy)return;selected=row??null;dialogError='';confirmed=false;password='';command='';code=row?.shortCode??'';note=row?.note??'';subscriptionId=subs(row??{id:''})[0]?.id??'';planId=enabledPlans.find(p=>!row||!subs(row).some(s=>s.planId===p.id))?.id??'';expires='';days=30;
  form=row?{...row,password:''}:{id:crypto.randomUUID(),name:'',username:'',email:'',note:'',application:'aswired',role:'普通用户',status:'正常',password:'',resourceQuotas:{nodes:50}};
  behavior=row?.behaviorLimits?JSON.stringify(row.behaviorLimits,null,2):'';quotas=JSON.stringify(row?.resourceQuotas??{nodes:50},null,2);mode=next;dialogOpen=true;if(next==='renew')subscriptionId=subs(row!).find(s=>s.expires)?.id??'';
  if(next==='telegram'){busy=true;try{command=(await api(`/api/members/${encodeURIComponent(row!.id)}/telegram`,{method:'POST',body:'{}'})).command;}catch(cause){dialogError=errorMessage(cause);}finally{busy=false;}}
 }
 async function update(fields:Record<string,any>){if(!selected)return;await api(`/api/members/${encodeURIComponent(selected.id)}`,{method:'PUT',body:JSON.stringify({row:{...fields,recordVersion:selected.recordVersion}})});}
 async function copySubscription(row:Row){if(busy)return;busy=true;try{const result=await api(`/api/members/${encodeURIComponent(row.id)}/subscription-link`,{method:'POST',body:'{}'});await copy(result.url);await load();}catch(cause){error=errorMessage(cause);}finally{busy=false;}}
 async function submit(){if(busy)return;busy=true;dialogError='';const currentMode=mode;try{
  if(mode==='create'||mode==='edit'){
   if(!form.name?.trim()||!form.username?.trim())throw new Error('请填写用户名和昵称');
   const limits=behavior.trim()?JSON.parse(behavior):null;const quota=JSON.parse(quotas);
   if(!quota||Array.isArray(quota)||Object.values(quota).some(v=>!Number.isInteger(v)||Number(v)<0))throw new Error('资源配额须为非负整数对象');
   const fields={name:form.name,username:form.username,email:form.email,note:form.note,application:form.application,role:form.application==='komari'?'普通用户':form.role,status:form.status,behaviorLimits:limits,resourceQuotas:quota};
   if(mode==='create'){if(new TextEncoder().encode(form.password??'').length<12)throw new Error('密码至少 12 字节');await saveRow('members',{id:form.id,...fields,password:form.password});}else await update(fields);
  }else if(mode==='note')await update({note});
  else if(mode==='password'){if(!confirmed)throw new Error('请确认撤销该用户的旧登录会话');if(new TextEncoder().encode(password).length<12)throw new Error('密码至少 12 字节');await update({password});}
  else if(mode==='status'){if(!confirmed)throw new Error('请确认修改状态');await update({status:isDisabled(selected!)?'正常':'暂停'});}
  else if(mode==='delete'){if(!confirmed)throw new Error('请确认删除用户');await api(`/api/members/${encodeURIComponent(selected!.id)}`,{method:'DELETE',body:JSON.stringify({confirm:true})});}
  else if(mode==='bind'){if(!planId)throw new Error('请选择套餐');const plan=plans.find(p=>p.id===planId)!;await saveRow('subscriptions',{id:crypto.randomUUID(),name:`${selected!.username} · ${plan.name}`,memberId:selected!.id,planId,limit:plan.limit??0,expires,status:'启用'});}
  else if(mode==='renew'){if(!confirmed||!Number.isInteger(days)||days<1||days>3660)throw new Error('请确认续费，天数须为 1 至 3660');const sub=await getRow('subscriptions',subscriptionId);if(sub.memberId!==selected!.id)throw new Error('套餐归属已改变');if(!sub.expires)throw new Error('长期套餐无需续费');let base=new Date(sub.expires.length===10?sub.expires+'T00:00:00+08:00':sub.expires);if(sub.expires.length===10)base=new Date(base.valueOf()+86400000);if(!Number.isFinite(base.valueOf()))throw new Error('到期时间无效');base=new Date(Math.max(Date.now(),base.valueOf()));base.setUTCDate(base.getUTCDate()+days);await saveRow('subscriptions',{...sub,expires:base.toISOString()});}
  else if(mode==='code'){await api(`/api/members/${encodeURIComponent(selected!.id)}/subscription-link`,{method:'POST',body:JSON.stringify({code,confirm:confirmed})});}
  else if(mode==='unbind'){await api(`/api/members/${encodeURIComponent(selected!.id)}/telegram`,{method:'POST',body:JSON.stringify({unbind:true,confirm:confirmed})});}
  mode='';dialogOpen=false;password='';form.password='';
  if(selected?.id===demo.user?.id&&['password','status'].includes(currentMode)){returnToLogin('账户已更新，请重新登录');return;}
  await load();await refreshState();toast('已保存');
 }catch(cause){dialogError=errorMessage(cause);}finally{busy=false;}}
</script>

<div class="page-head"><div><div class="eyebrow">工作区 / 用户</div><h1>用户管理</h1><p>账号、套餐与订阅</p></div></div>
<section class="member-workbench card padded">
 <div class="member-toolbar"><div><h2>账号列表 <span class="muted">{rows.length}</span></h2></div><div class="actions"><div class="view-modes" role="group" aria-label="用户列表视图"><button class:active={view==='full'} aria-pressed={view==='full'} onclick={()=>view='full'}><Icon name="list"/>完整视图</button><button class:active={view==='renewal'} aria-pressed={view==='renewal'} onclick={()=>view='renewal'}><Icon name="wallet"/>续费视图</button></div><button class="icon-button" title="刷新用户" aria-label="刷新用户" disabled={loading||busy} onclick={load}><Icon name="refresh"/></button><button class="button primary" disabled={busy} onclick={()=>open('create')}><Icon name="plus"/>新增用户</button></div></div>
 <div class="member-search search-input"><Icon name="search"/><input aria-label="搜索用户" bind:value={search} placeholder="搜索用户名 / 昵称 / 套餐 / 备注"/></div>
 <div class="plan-filters" role="group" aria-label="按套餐筛选"><button class:active={planFilter==='all'} aria-pressed={planFilter==='all'} onclick={()=>planFilter='all'}>全部 ({rows.length})</button>{#each plans as plan}<button class:active={planFilter===plan.id} aria-pressed={planFilter===plan.id} onclick={()=>planFilter=plan.id}>{plan.name} ({rows.filter(row=>subs(row).some(s=>s.planId===plan.id)).length})</button>{/each}<button class:active={planFilter==='none'} aria-pressed={planFilter==='none'} onclick={()=>planFilter='none'}>未绑定套餐 ({rows.filter(row=>!subs(row).length).length})</button></div>
 {#if error}<p class="error" role="alert">{error}</p>{/if}
 <div class="table-scroll" aria-busy={loading}><table class:renewal={view==='renewal'}><thead><tr><th>用户名</th><th>昵称</th>{#if view==='full'}<th>Telegram</th><th>备注</th><th>用户短码</th><th>用户订阅</th>{/if}<th class="quota-cell">套餐 / 流量</th>{#if view==='renewal'}<th>到期日期</th><th>续费</th>{/if}<th>角色</th><th>状态</th><th class="action-column">操作</th></tr></thead><tbody>
 {#each visible as row(row.id)}<tr><td><strong>{row.username}</strong>{#if row.application==='komari'}<small>Komari 探针</small>{/if}</td><td>{row.name}</td>
 {#if view==='full'}<td>{#if row.telegram?.length}<div class="inline-cell"><span class="telegram-id" title={row.telegram.map((t:any)=>t.chatId).join(', ')}>已绑定</span><button class="icon-button" title="解绑 Telegram" aria-label={`解绑 ${row.username} 的 Telegram`} disabled={busy} onclick={()=>open('unbind',row)}><Icon name="unplug" size={14}/></button></div>{:else}<button class="button small" disabled={busy||isDisabled(row)} onclick={()=>open('telegram',row)}><Icon name="link" size={14}/>绑定</button>{/if}</td><td><div class="inline-cell"><span class="note-text" title={row.note}>{row.note||'—'}</span><button class="icon-button" title="编辑备注" aria-label={`编辑 ${row.username} 的备注`} disabled={busy} onclick={()=>open('note',row)}><Icon name="edit" size={14}/></button></div></td><td><div class="inline-cell"><code class="short-code" title={row.shortCode}>{row.shortCode?`${row.shortCode.slice(0,8)}…`:'未生成'}</code><button class="icon-button" title="修改用户短码" aria-label={`修改 ${row.username} 的短码`} disabled={busy||!subs(row).length||isDisabled(row)} onclick={()=>open('code',row)}><Icon name="edit" size={14}/></button></div></td><td>{#if subs(row).length}<button class="button small" disabled={busy||isDisabled(row)} onclick={()=>copySubscription(row)}><Icon name="copy" size={14}/>复制订阅</button>{:else}<span class="muted">—</span>{/if}</td>{/if}
 <td class="quota-cell">{#each subs(row) as sub}<div class="quota"><div><span title={sub.plan}>{sub.plan}</span><small>{sub.used==null?'未知':sub.limit?`${Math.round(Number(sub.used)/Number(sub.limit)*100)}%`:'不限量'}</small></div><div class="progress" title={`${usage(sub)} / ${sub.limit||'不限'} GB`}><i style={`width:${percent(sub)}%`}></i></div><small>{usage(sub)} / {sub.limit||'不限'} GB</small></div>{:else}<button class="button small" disabled={busy||row.application==='komari'} onclick={()=>open('bind',row)}><Icon name="package" size={14}/>绑定套餐</button>{/each}</td>
 {#if view==='renewal'}<td>{#each subs(row) as sub}<div class="expiry" class:expired={sub.expires&&new Date(sub.expires).valueOf()<Date.now()}><span>{date(sub.expires)}</span><small>{sub.plan} · {expiry(sub.expires)}</small></div>{:else}—{/each}</td><td><button class="button small" disabled={busy||!subs(row).some(s=>s.expires)} onclick={()=>open('renew',row)}><Icon name="wallet" size={14}/>续费</button></td>{/if}
 <td><span class="role-label">{row.role}</span></td><td><span class="member-status" class:disabled={isDisabled(row)}>{isDisabled(row)?'停用':'启用'}</span></td><td class="action-column"><DropdownMenu.Root><DropdownMenu.Trigger class="icon-button" disabled={busy} aria-label={`${row.username} 的操作`} title="用户操作"><Icon name="more"/></DropdownMenu.Trigger><DropdownMenu.Portal><DropdownMenu.Content class="member-menu" sideOffset={5} align="end"><DropdownMenu.Item class="member-menu-item" onSelect={()=>open('edit',row)}><Icon name="edit"/>编辑用户</DropdownMenu.Item><DropdownMenu.Item class="member-menu-item" onSelect={()=>open('password',row)}><Icon name="key"/>重置密码</DropdownMenu.Item><DropdownMenu.Item class="member-menu-item" disabled={row.application==='komari'} onSelect={()=>open('bind',row)}><Icon name="package"/>绑定套餐</DropdownMenu.Item><DropdownMenu.Item class="member-menu-item" disabled={!subs(row).some(s=>s.expires)} onSelect={()=>open('renew',row)}><Icon name="wallet"/>续费</DropdownMenu.Item><DropdownMenu.Item class="member-menu-item" onSelect={()=>open('status',row)}><Icon name={isDisabled(row)?'play':'pause'}/>{isDisabled(row)?'启用用户':'停用用户'}</DropdownMenu.Item><DropdownMenu.Item class="member-menu-item danger-text" onSelect={()=>open('delete',row)}><Icon name="trash"/>删除用户</DropdownMenu.Item></DropdownMenu.Content></DropdownMenu.Portal></DropdownMenu.Root></td></tr>
 {:else}<tr><td colspan={view==='full'?10:8}><div class="empty">{loading?'正在读取用户…':search||planFilter!=='all'?'没有符合条件的用户':'暂无用户'}</div></td></tr>{/each}
 </tbody></table></div>
 <div class="member-pagination"><span>共 {filtered.length} 个用户 · 每页 25 个</span><div class="actions"><button class="icon-button" title="上一页" aria-label="上一页" disabled={page===0} onclick={()=>page--}><Icon name="back"/></button><span>{page+1} / {Math.max(1,Math.ceil(filtered.length/25))}</span><button class="icon-button" title="下一页" aria-label="下一页" disabled={(page+1)*25>=filtered.length} onclick={()=>page++}><Icon name="right"/></button></div></div>
</section>
<div class="space-top"><RegistrationInvites/></div>

<Modal bind:open={dialogOpen} title={titles[mode]??'用户管理'} description={selected?.username??''} wide={mode==='create'||mode==='edit'}>
 <form onsubmit={event=>{event.preventDefault();void submit();}}>
 {#if mode==='create'||mode==='edit'}<div class="form-grid"><label class="field">用户名<input required maxlength="128" bind:value={form.username}/></label><label class="field">昵称<input required maxlength="128" bind:value={form.name}/></label><label class="field">邮箱<input type="email" bind:value={form.email}/></label><label class="field">账户系统<AppSelect bind:value={form.application} options={[{value:'aswired',label:'ASWired 工作区'},{value:'komari',label:'Komari 探针'}]} disabled={mode==='edit'} aria-label="账户系统"/></label><label class="field">角色<AppSelect bind:value={form.role} options={['管理员','普通用户']} disabled={form.application==='komari'} aria-label="角色"/></label><label class="field">状态<AppSelect bind:value={form.status} options={['正常','暂停']} aria-label="用户状态"/></label>{#if mode==='create'}<label class="field full">初始密码<input required type="password" minlength="12" maxlength="72" autocomplete="new-password" bind:value={form.password}/></label>{/if}<label class="field full">备注<textarea maxlength="2000" bind:value={form.note}></textarea></label><BehaviorEditor bind:value={behavior}/><label class="field full">资源配额<textarea bind:value={quotas} spellcheck="false"></textarea></label></div>
 {:else if mode==='note'}<label class="field">备注<textarea maxlength="2000" bind:value={note}></textarea></label>
 {:else if mode==='password'}<label class="field">新密码<input type="password" required minlength="12" maxlength="72" autocomplete="new-password" bind:value={password}/></label><label class="tag space-top"><input type="checkbox" bind:checked={confirmed}/>确认重置密码并撤销旧登录会话</label>
 {:else if mode==='status'||mode==='delete'}<p>{mode==='delete'?'删除此用户及关联账户数据，此操作不可撤销。':isDisabled(selected!)?'启用后允许用户登录和使用订阅。':'停用后用户无法登录和使用订阅。'}</p><label class="tag space-top"><input type="checkbox" bind:checked={confirmed}/>确认{mode==='delete'?'删除':isDisabled(selected!)?'启用':'停用'} {selected?.username}</label>
 {:else if mode==='bind'}<label class="field">套餐<AppSelect bind:value={planId} options={availablePlans.map(p=>({value:p.id,label:p.name}))} aria-label="绑定套餐"/></label>{#if !availablePlans.length}<p class="hint">没有可绑定的套餐，请先创建套餐。</p>{/if}<label class="field space-top">到期日期（留空为长期）<input type="date" bind:value={expires}/></label>
 {:else if mode==='renew'}<label class="field">套餐<AppSelect bind:value={subscriptionId} options={subs(selected!).filter(s=>s.expires).map(s=>({value:s.id,label:`${s.plan} · ${date(s.expires)}`}))} aria-label="续费套餐"/></label><label class="field space-top">续费天数<input type="number" required min="1" max="3660" step="1" bind:value={days}/></label><p class="hint">从当前到期时间或今天起延长，不重置流量用量。</p><label class="tag space-top"><input type="checkbox" bind:checked={confirmed}/>已核对续费条件</label>
 {:else if mode==='code'}<label class="field">用户短码<input required minlength="24" maxlength="128" pattern="[A-Za-z0-9_-]+" bind:value={code}/></label><button type="button" class="button space-top" onclick={()=>code=crypto.randomUUID().replaceAll('-','')}><Icon name="refresh"/>生成短码</button><p class="hint">短码是订阅访问凭据，至少 24 位。修改后旧用户订阅链接失效。</p><label class="tag space-top"><input type="checkbox" bind:checked={confirmed}/>确认更新用户订阅链接</label>
 {:else if mode==='telegram'}<p>将绑定命令交给该用户，在配置的 Telegram Bot 私聊中发送，5 分钟内有效。</p>{#if command}<label class="field space-top">绑定命令<input readonly value={command}/></label><button class="button space-top" type="button" onclick={()=>copy(command)}><Icon name="copy"/>复制命令</button>{/if}
 {:else if mode==='unbind'}<p>解绑后该用户不再通过当前 Telegram 账户接收通知或执行命令。</p><label class="tag space-top"><input type="checkbox" bind:checked={confirmed}/>确认解绑 Telegram</label>{/if}
 {#if dialogError}<p class="error space-top" role="alert">{dialogError}</p>{/if}<div class="modal-actions"><button type="button" class="button" disabled={busy} onclick={()=>{dialogOpen=false;mode='';password='';form.password='';}}>关闭</button>{#if mode!=='telegram'}<button class="button primary" disabled={busy||(mode==='bind'&&!planId)||(mode==='renew'&&!subscriptionId)}>{busy?'处理中…':'确认'}</button>{/if}</div>
 </form>
</Modal>

<style>
 .member-workbench{min-width:0}.member-toolbar{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:12px 0}.member-toolbar h2{font-size:16px}.member-toolbar h2 span{font-size:12px;margin-left:8px}.actions{flex-wrap:wrap}.view-modes{display:flex;background:var(--nested);border:1px solid var(--border);border-radius:6px;padding:3px}.view-modes button{display:flex;align-items:center;gap:7px;padding:7px 10px;font-size:12px;border:0;border-radius:4px;color:var(--muted);background:transparent}.view-modes button.active{background:color-mix(in srgb,var(--primary) 14%,transparent);color:var(--primary)}.member-search{max-width:390px;margin:8px 0 14px}.plan-filters{display:flex;flex-wrap:wrap;gap:6px;margin-bottom:16px}.plan-filters button{border:1px solid var(--border);border-radius:4px;padding:7px 11px;font-size:12px;color:var(--muted);background:var(--nested);overflow-wrap:anywhere}.plan-filters button.active{color:var(--primary);border-color:var(--primary);background:color-mix(in srgb,var(--primary) 14%,transparent)}table{min-width:1160px;width:100%;table-layout:fixed}table.renewal{min-width:900px}th,td{padding:13px 10px;overflow-wrap:anywhere;vertical-align:middle}th{font-size:12px}td{font-size:12px}td strong{font-weight:600}td>small,.expiry small{display:block;color:var(--muted);font-size:10px;margin-top:4px}.inline-cell{display:flex;align-items:center;gap:5px;min-width:0}.inline-cell .icon-button{flex-shrink:0}.note-text{display:-webkit-box;-webkit-line-clamp:2;line-clamp:2;-webkit-box-orient:vertical;overflow:hidden;overflow-wrap:anywhere}.short-code{font-size:10px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.quota-cell{width:190px}.quota+.quota{margin-top:12px}.quota>div:first-child{display:flex;align-items:center;justify-content:space-between;gap:6px;margin-bottom:5px}.quota span{overflow:hidden;white-space:nowrap;text-overflow:ellipsis}.quota small{font-size:10px;color:var(--muted)}.quota>small{display:block;margin-top:4px}.member-status{padding:4px 7px;border-radius:4px;font-size:11px;color:var(--primary);background:color-mix(in srgb,var(--primary) 14%,transparent);white-space:nowrap}.member-status.disabled{color:var(--muted);background:var(--nested)}.action-column{width:50px;text-align:right}.role-label{font-size:11px}.telegram-id{color:#49b7e5}.expired{color:#e88e91}.expiry+.expiry{margin-top:10px}.member-pagination{display:flex;justify-content:space-between;align-items:center;padding:14px 0;color:var(--muted);font-size:12px}.member-pagination .actions{gap:8px}.member-pagination .icon-button{width:30px;height:30px}.table-scroll{border-top:1px solid var(--border);border-bottom:1px solid var(--border)}
 :global(.member-menu){z-index:90;min-width:170px;padding:5px;background:var(--background,#17191c);border:1px solid var(--border);border-radius:6px;box-shadow:0 8px 30px #0004}:global(.member-menu-item){display:flex;align-items:center;gap:9px;padding:9px 12px;border-radius:3px;font-size:12px;cursor:pointer;outline:none}:global(.member-menu-item[data-highlighted]){background:color-mix(in srgb,var(--primary) 14%,transparent);color:var(--primary)}:global(.member-menu-item[data-disabled]){opacity:.4;pointer-events:none}:global(.member-menu-item.danger-text){color:#e88e91}
 @media(max-width:700px){.member-toolbar{align-items:flex-start;flex-direction:column}.member-toolbar>.actions{width:100%}.member-search{max-width:none}.member-pagination{gap:10px}.plan-filters{max-height:140px;overflow:auto}}
</style>
