<script lang="ts">
 import {formatNumber} from '../format';
 import ExpandableValue from '../components/ExpandableValue.svelte';
 import {realityClientFormats} from '../reality-client-options';
 import {onDestroy} from 'svelte';
 import {createSubscriptionOutput} from '../subscription-output.svelte';
 import QuotaFields from '../components/QuotaFields.svelte';
 import AppSelect from '../components/Select.svelte';
 import Icon from '../components/Icon.svelte';import Modal from '../components/Modal.svelte';import Badge from '../components/Badge.svelte';
 import {demo,saveRow,getRow,api,apiText,refreshState,copy,download,toast,percent,errorMessage,runAction} from '../store.svelte';import type {Row} from '../data';import QRCode from 'qrcode';
 const formats=realityClientFormats.map(item=>item.label);const formatCodes:Record<string,string>=Object.fromEntries(realityClientFormats.map(item=>[item.label,item.value]));
 let templateOptions=$state<Row[]>([]),selectedTemplate=$state('');
 const matchingTemplates=$derived(templateOptions.filter(item=>String(item.type).toLowerCase()===(formatCodes[format]==='stash'?'clash':formatCodes[format])));
 let resetOpen=$state(false),resetConfirmation=$state(false),resetRequestId=$state(''),search=$state(''),open=$state(false),editing=$state(false),row=$state<Row>({id:''}),format=$state('Clash Meta'),revealed=$state(false),tab=$state('订阅链接'),error=$state(''),busy=$state(false);
 const rows=$derived(demo.data.subscriptions.filter(r=>[r.name,r.member,r.plan].join(' ').includes(search)));
 const url=$derived(row.token&&typeof window!=='undefined'?`${window.location.origin}/api/clash/subscribe?token=${encodeURIComponent(row.token)}&format=${formatCodes[format]??'clash'}${selectedTemplate?'&template='+encodeURIComponent(selectedTemplate):''}`:'');
 const output=createSubscriptionOutput(apiText,value=>QRCode.toDataURL(value,{width:180,margin:2,color:{dark:'#141413',light:'#faf9f5'}}));
 const ready=$derived(open&&output.state.url===url&&output.state.ready);
 $effect(()=>{if(open&&row.id&&url)void output.load({id:row.id,format:formatCodes[format]??'clash',url,template:selectedTemplate});else output.clear();});
 onDestroy(()=>output.clear());
 function retryOutput(){if(open&&row.id&&url)void output.load({id:row.id,format:formatCodes[format]??'clash',url,template:selectedTemplate});}
 async function show(r:Row){if(busy)return;busy=true;try{row=await getRow('subscriptions',r.id);selectedTemplate='';templateOptions=(await api('/api/templates/options')).templates??[];format=row.format&&formatCodes[row.format]?row.format:'Clash Meta';tab='订阅链接';revealed=false;open=true;}catch(cause){toast(errorMessage(cause));}finally{busy=false;}}
 async function edit(r?:Row){error='';busy=true;try{row=r?await getRow('subscriptions',r.id):{id:crypto.randomUUID(),name:'',member:demo.data.members[0]?.username??demo.data.members[0]?.name??'',plan:demo.data.plans[0]?.name??'',limit:demo.data.plans[0]?.limit??0,used:0,status:'启用',format:'Clash Meta',ipLimit:demo.data.plans[0]?.ipLimit??0,deviceLimit:0,expires:''};editing=true;}catch(cause){toast(errorMessage(cause));}finally{busy=false;}}
 async function save(){if(busy)return;error='';if(!row.name?.trim()){error='请填写订阅名称';return;}if(!row.member||!row.plan){error='请选择成员和套餐';return;}busy=true;try{row=await saveRow('subscriptions',row);editing=false;toast('套餐实例已保存');}catch(cause){error=errorMessage(cause);}finally{busy=false;}}
 async function rotate(){if(busy)return;busy=true;try{const result=await api(`/api/subscriptions/${encodeURIComponent(row.id)}/rotate`,{method:'POST'});row={...row,...result.row,token:result.token};await refreshState();toast('令牌已轮换，旧订阅链接已失效');}catch(cause){toast(errorMessage(cause));}finally{busy=false;}}
 async function resetTraffic(){if(busy||!resetConfirmation)return;busy=true;try{await runAction('subscription.traffic.reset',row.id,'subscriptions',{confirmed:true,requestId:resetRequestId,recordVersion:row.recordVersion});row=await getRow('subscriptions',row.id);resetOpen=false;toast('本周期用量已重置');}catch(cause){toast(errorMessage(cause));}finally{busy=false;}}
 async function savePolicy(toggle=false){busy=true;try{const draft={...row,...(toggle?{status:row.status==='停用'?'启用':'停用'}:{})};row=await saveRow('subscriptions',draft);toast('策略已保存');}catch(cause){toast(errorMessage(cause));}finally{busy=false;}}
</script>
<div class="page-head"><div><div class="eyebrow">订阅与拼车 / 订阅</div><h1>订阅管理</h1><p>每个套餐实例拥有独立凭据、额度与到期时间。</p></div>{#if demo.user?.role==='admin'}<button class="button primary" disabled={busy} onclick={()=>edit()}><Icon name="plus"/>分配套餐</button>{/if}</div>
<div class="card no-pad"><div class="toolbar"><div class="search-input"><Icon name="search"/><input aria-label="搜索订阅" bind:value={search} placeholder="搜索成员、套餐或订阅名称…"/></div><span class="muted">{rows.length} 个订阅</span></div><div class="table-scroll"><table><thead><tr><th>订阅 / 成员</th><th>套餐</th><th>本期用量</th><th>到期日期</th><th>状态</th><th>操作</th></tr></thead><tbody>{#each rows as r}<tr><td><button class="identity" onclick={()=>show(r)}><span class="soft-icon"><Icon name="rss"/></span><span><strong>{r.name}</strong><small>{r.member} · {r.nodes??0} 个节点</small></span></button></td><td>{r.plan}</td><td><div class="cell-progress"><span>{formatNumber(r.used)} / {r.limit?formatNumber(r.limit):'不限'} GB</span><div class="progress thin"><i style={`width:${percent(r.used,r.limit)}%`}></i></div></div></td><td>{r.expires||'不限期'}</td><td><Badge value={r.status}/></td><td><div class="row-actions"><button class="button small" disabled={busy} onclick={()=>show(r)}>获取订阅 <Icon name="right" size={13}/></button>{#if demo.user?.role==='admin'}<button class="icon-button" disabled={busy} aria-label={`编辑订阅 ${r.member}`} onclick={()=>edit(r)}><Icon name="edit"/></button>{/if}</div></td></tr>{:else}<tr><td colspan="6"><div class="empty">尚未分配套餐实例</div></td></tr>{/each}</tbody></table></div></div>
<Modal bind:open title={row.name??'订阅'} description="订阅与配置来自主控" wide><div class="tabs">{#each ['订阅链接','配置预览',...(demo.user?.role==='admin'?['访问控制']:[])] as item}<button class:active={tab===item} disabled={busy} onclick={()=>tab=item}>{item}</button>{/each}</div>
{#if tab==='访问控制'}<div class="form-grid"><label class="field">设备标识上限（0 为不限）<input type="number" min="0" bind:value={row.deviceLimit}/></label><label class="field">在线 IP 上限（0 为不限）<input type="number" min="0" bind:value={row.ipLimit}/></label><QuotaFields bind:row inherit/><label class="field full">订阅白名单（CIDR，以逗号分隔）<input bind:value={row.whitelist} placeholder="留空允许任意来源"/></label></div><p class="hint">设备标识、在线 IP 与实际连接数是不同的限制。节点执行能力以 Agent 实际支持为准。</p><div class="modal-actions"><button class="button" disabled={busy} onclick={()=>savePolicy(true)}>{row.status==='停用'?'启用':'暂停'}订阅</button><button class="button" disabled={busy} onclick={()=>{resetConfirmation=false;resetRequestId=crypto.randomUUID();resetOpen=true;}}>重置本周期流量</button><button class="button primary" disabled={busy} onclick={()=>savePolicy()}>保存策略</button></div>
{:else}<label class="field">客户端格式<AppSelect bind:value={format} options={formats} aria-label="客户端格式" onchange={()=>selectedTemplate=''}/></label>{#if matchingTemplates.length}<label class="field space-top">客户端模板<AppSelect bind:value={selectedTemplate} options={[{value:'',label:'订阅指定 / 默认模板'},...matchingTemplates.filter(item=>item.userVisible!==false).map(item=>({value:item.id,label:item.name}))]} aria-label="订阅模板选择"/></label>{/if}{#if format==='Quantumult X'}<p class="hint">Quantumult X 仅用于未启用 Vision Flow 的节点；以主控实际配置检查结果为准。</p>{/if}
{#if output.state.loading}<p class="hint space-top" role="status">正在检查 {format} 配置…</p>{:else if output.state.error}<p class="error space-top" role="alert">{output.state.error}</p><button class="button small" disabled={busy} onclick={retryOutput}>重新检查</button>{:else if ready}<p class="hint space-top" role="status">{format} 配置已就绪</p>{/if}
{#if tab==='订阅链接'}<div class="split space-top"><div><div class="token-box"><code>{ready?(revealed?url:'订阅凭据已隐藏'):output.state.loading?'正在检查所选格式…':output.state.error?'当前格式不可用':'暂未生成订阅凭据'}</code><button class="icon-button" disabled={!ready} aria-label="显示订阅地址" onclick={()=>revealed=!revealed}><Icon name="eye"/></button></div><div class="actions space-top"><button class="button primary" disabled={!ready||busy} onclick={()=>copy(url)}><Icon name="copy"/>复制链接</button><button class="button" disabled={busy} onclick={rotate}><Icon name="refresh"/>轮换令牌</button></div><p class="hint">有效期至 {row.expires||'不限期'}</p></div><div class="qr-box">{#if ready&&output.state.qr}<img src={output.state.qr} alt={`${format} 订阅二维码`} width="180" height="180"/><small>使用客户端扫描</small>{:else}<small>{output.state.loading?'正在检查所选格式…':output.state.qrError||'当前格式暂无可用二维码'}</small>{/if}</div></div>{:else}{#if ready}<div class="space-top">{#key row.id}{#key format}<ExpandableValue value={output.state.config} label="订阅配置详情" force />{/key}{/key}</div>{:else if !output.state.loading&&!output.state.error}<p class="hint space-top">当前格式暂无可用配置</p>{/if}<div class="modal-actions"><button class="button" disabled={!ready||busy} onclick={()=>copy(output.state.config)}>复制配置</button><button class="button primary" disabled={!ready||busy} onclick={()=>download(`aswired-${format}.${['Clash Meta','Stash','Egern'].includes(format)?'yaml':format==='sing-box'?'json':['V2Ray','Shadowrocket'].includes(format)?'txt':'conf'}`,output.state.config)}><Icon name="download"/>下载配置</button></div>{/if}{/if}</Modal>
<Modal bind:open={editing} title="分配与编辑套餐实例" description="同一成员不能重复绑定同一个套餐" wide><form onsubmit={e=>{e.preventDefault();save();}}><div class="form-grid"><label class="field full">订阅名称<input bind:value={row.name} required/></label><label class="field">成员<AppSelect bind:value={row.member} options={demo.data.members.map(r=>r.username??r.name)} aria-label="成员"/></label><label class="field">套餐<AppSelect bind:value={row.plan} options={demo.data.plans.map(r=>r.name)} aria-label="套餐" onchange={()=>{const plan=demo.data.plans.find(plan=>plan.name===row.plan);if(plan){row.limit=plan.limit??0;row.ipLimit=plan.ipLimit??0;}}}/></label><label class="field">额度 / GB（0 为不限）<input type="number" min="0" bind:value={row.limit}/></label><label class="field">到期日期<input type="date" bind:value={row.expires}/></label><QuotaFields bind:row inherit/><label class="field">客户端模板<AppSelect bind:value={row.templateId} options={[{value:'',label:'使用默认配置'},...demo.data.policies.map(p=>({value:p.id,label:p.name}))]} aria-label="客户端模板"/></label><label class="field">脚本覆写<AppSelect bind:value={row.scriptId} options={[{value:'',label:'不使用脚本'},...(demo.data.rules??[]).filter(r=>r.type==='script').map(r=>({value:r.id,label:r.name}))]} aria-label="脚本覆写"/></label><label class="field">设备标识上限<input type="number" min="0" bind:value={row.deviceLimit}/></label><label class="field">在线 IP 上限<input type="number" min="0" bind:value={row.ipLimit}/></label></div>{#if error}<p class="error" role="alert">{error}</p>{/if}<div class="modal-actions"><button type="button" class="button" onclick={()=>editing=false}>取消</button><button class="button primary" disabled={busy}>{busy?'保存中…':'保存实例'}</button></div></form></Modal>

<Modal bind:open={resetOpen} title="重置套餐用量" description="当前周期从本次操作时刻重新计量，历史流量账本仍保留。"><p class="hint">跨越此时刻、尚未上报的流量会随 Agent 下一次采样计入新周期。</p><label class="tag space-top"><input type="checkbox" bind:checked={resetConfirmation}/>确认重置 {row.member} 的 {row.plan} 本周期用量</label><div class="modal-actions"><button class="button" onclick={()=>resetOpen=false}>取消</button><button class="button primary" disabled={busy||!resetConfirmation} onclick={resetTraffic}>确认重置</button></div></Modal>
