<script lang="ts">
 import {formatNumber} from '../format';
 import MemberServices from '../components/MemberServices.svelte';import Icon from '../components/Icon.svelte';import Badge from '../components/Badge.svelte';import Modal from '../components/Modal.svelte';import {demo,saveRow,percent,toast,errorMessage,runAction} from '../store.svelte';
 let open=$state(false),name=$state('我的转发'),port=$state(19080),target=$state(''),busy=$state(false),error=$state('');
 const member=$derived(demo.user?.username??'');
 const profile=$derived(demo.data.members.find(m=>m.id===demo.user?.id||m.username===member)??{used:0,limit:0,plan:'尚未分配',status:'正常',expires:''});
 const subscriptions=$derived(demo.user?.role==='admin'?demo.data.subscriptions.filter(s=>s.member===member||s.memberId===demo.user?.id):demo.data.subscriptions);
 async function saveForward(){if(busy)return;busy=true;error='';try{await saveRow('forwards',{id:crypto.randomUUID(),name,owner:member,port,target,status:'草稿'});open=false;toast('转发规则已保存，可在我的转发中查看状态');}catch(cause){error=errorMessage(cause);}finally{busy=false;}}
 async function renew(id:string){try{await runAction('subscription.renewal.declare',id,'subscriptions');toast('已提交续费声明');}catch(cause){toast(errorMessage(cause));}}
</script>
<div class="page-head"><div><div class="eyebrow">成员门户</div><h1>你好，{member}。</h1><p>查看你的套餐、订阅与到期时间。</p></div></div>
<div class="stat-grid"><div class="card stat-card"><span class="muted">本期已用</span><div class="stat-number">{formatNumber(profile.used??0)}<small> GB</small></div><div class="progress"><i style={`width:${percent(profile.used,profile.limit)}%`}></i></div><small class="muted">额度 {profile.limit?formatNumber(profile.limit):'不限'} GB</small></div><div class="card stat-card"><span class="muted">我的套餐</span><div class="stat-number" style="font-size:1.4rem">{subscriptions.length} 个实例</div><Badge value={profile.status??'正常'}/></div><div class="card stat-card"><span class="muted">有效期至</span><div class="stat-number" style="font-size:1.4rem">{profile.expires||'以套餐实例为准'}</div></div><div class="card stat-card"><span class="muted">账户身份</span><div class="stat-number" style="font-size:1.4rem">{demo.role}</div><small class="muted">由主控验证账户权限</small></div></div>
<section class="card padded"><div class="section-head"><h2>我的订阅</h2><Icon name="rss"/></div>{#each subscriptions as sub}<div class="car-summary"><div><strong>{sub.name}</strong><small>{sub.plan} · {formatNumber(sub.used??0)} / {sub.limit?formatNumber(sub.limit):'不限'} GB · {sub.expires||'不限期'}</small></div><div class="actions"><a class="button small" href="/subscriptions">获取订阅</a><button class="button small" onclick={()=>renew(sub.id)}>已续费</button></div></div>{:else}<div class="empty">尚无套餐，请联系管理员分配。</div>{/each}</section>
<MemberServices/>
{#if demo.user?.role==='admin'}
<section class="card padded space-top"><div class="section-head"><div><h2>我的转发</h2><p class="muted">可用范围和操作次数由主控设置。</p></div><button class="button" onclick={()=>open=true}><Icon name="plus"/>新增转发</button></div>{#each demo.data.forwards?.filter(f=>f.owner===member)??[] as forward}<div class="car-summary"><div><strong>{forward.name}</strong><small>{forward.port} → {forward.target}</small></div><Badge value={forward.status??'草稿'}/></div>{:else}<div class="empty"><Icon name="route" size={28}/><p>还没有转发规则</p></div>{/each}</section>
<Modal bind:open title="新增个人转发" description="主控校验可用范围后保存"><form onsubmit={e=>{e.preventDefault();saveForward();}}><div class="form-grid"><label class="field full">名称<input required bind:value={name}/></label><label class="field">监听端口<input type="number" min="1" max="65535" bind:value={port}/></label><label class="field">目标<input required bind:value={target}/></label></div>{#if error}<p class="error" role="alert">{error}</p>{/if}<div class="modal-actions"><button type="button" class="button" onclick={()=>open=false}>取消</button><button class="button primary" disabled={busy}>{busy?'保存中…':'保存'}</button></div></form></Modal>
{/if}
