<script lang="ts">
 import CountryBadge from '../components/CountryBadge.svelte';
 import ProbeAssets from '../components/ProbeAssets.svelte';import type {PublicProbeAsset} from '../probe-assets';
 import {onMount} from 'svelte';import Icon from '../components/Icon.svelte';import Badge from '../components/Badge.svelte';import AppSelect from '../components/Select.svelte';import {KOMARI_PROVIDER,KOMARI_VERSION} from '../probe';import {probeMetrics,historyCurve,formatProbeValue} from '../probe-history';
 import {createProbeHistory,ProbeHistoryError} from '../probe-history-state.svelte';
 type ProbeNode=PublicProbeAsset & {name:string;online:boolean;region?:string;cpu_pct?:number;mem_used?:number;mem_total?:number;disk_used?:number;disk_total?:number;upload_speed?:number;download_speed?:number;uptime?:number};
 let nodes=$state<ProbeNode[]>([]),enabled=$state(false),showGlobe=$state(false),showAssets=$state(false),loading=$state(true),error=$state(''),metric=$state('cpu_pct'),range=$state('1h'),selected=$state('0'),updated=$state('');
 let stopped=false,controller:AbortController|undefined,timer:ReturnType<typeof setTimeout>|undefined,lastHistoryFetch=0,publicRequest=0;
 async function readProbe(path:string,signal:AbortSignal){const response=await fetch(path,{cache:'no-store',signal});let body;try{body=await response.json();}catch{throw new ProbeHistoryError(response.ok?'探针响应格式异常':'无法读取公开探针',response.status);}if(!response.ok)throw new ProbeHistoryError(body?.error?.message??'无法读取公开探针',response.status);return body;}
 const historyData=createProbeHistory(readProbe,cause=>{clearPublic();error=cause.message;});
 const series=$derived(historyData.state.series),method=$derived(historyData.state.method),bucketSeconds=$derived(historyData.state.bucketSeconds),historyError=$derived(historyData.state.error);
 const historyIdentity=$derived(JSON.stringify([nodes.map(node=>[node.name,node.region]),Object.keys(nodes[Number(selected)]??{}).sort()]));
 const onlineCount=$derived(nodes.filter(node=>node.online).length);
 const metricInfo=$derived(probeMetrics.find(item=>item.value===metric)!);const ceiling=$derived(metricInfo.percent?100:Math.max(1,...series.map(sample=>sample.value))*1.1);const historyPath=$derived(historyCurve(series,ceiling,bucketSeconds));
 const formatRate=(value?:number)=>value==null?'未知':value>=1024*1024?`${(value/1024/1024).toFixed(1)} MB/s`:`${(value/1024).toFixed(1)} KB/s`;
 async function history(){lastHistoryFetch=Date.now();if(!enabled||!nodes.length){historyData.clear();return;}await historyData.load({server:selected,identity:historyIdentity,metric,range,network:metricInfo.network===true});}
 function clearPublic(){publicRequest++;controller?.abort();nodes=[];enabled=false;showGlobe=false;showAssets=false;lastHistoryFetch=0;historyData.clear();}
 async function refresh(){
  const request=++publicRequest;const active=new AbortController();controller=active;const timeout=setTimeout(()=>active.abort(),15000);
  try{
   const body=await readProbe('/api/public/probe-servers',active.signal);if(stopped||request!==publicRequest)return;
   if(typeof body.enabled!=='boolean'||(body.enabled&&!Array.isArray(body.servers)))throw new Error('探针响应格式异常，请稍后重试');
   const before=historyIdentity;enabled=body.enabled;showGlobe=enabled&&body.show_globe===true;showAssets=enabled&&body.show_assets===true;nodes=enabled?body.servers.map((node:ProbeNode,i:number)=>({...node,name:node.name||('服务器 '+(i+1))})):[];
   if(Number(selected)>=nodes.length){selected='0';lastHistoryFetch=0;}
   error='';updated=new Date().toLocaleTimeString();
   if(!enabled||!nodes.length)historyData.clear();
   else if(before!==historyIdentity||Date.now()-lastHistoryFetch>=30000)void history();
  }catch(cause){if(!stopped&&request===publicRequest){error=active.signal.aborted?'探针更新超时，请稍后重试':cause instanceof Error?cause.message:'连接失败';if(cause instanceof ProbeHistoryError&&[401,403,404].includes(cause.status))clearPublic();}}
  finally{clearTimeout(timeout);if(controller===active)controller=undefined;if(!stopped){loading=false;timer=setTimeout(refresh,5000);}}
 }
 onMount(()=>{stopped=false;refresh();return()=>{stopped=true;controller?.abort();if(timer)clearTimeout(timer);historyData.clear();};});
</script>
<div class="page-head"><div><div class="eyebrow">ASWired / 公开状态</div><h1>探针监控</h1><p>{KOMARI_PROVIDER} {KOMARI_VERSION}</p></div><Badge value={loading?'正在连接':error?'连接异常':enabled?'实时状态':'公开展示已关闭'} kind={error?'warning':'neutral'}/></div>
{#if error}<div class="status-banner" role="alert"><Icon name="activity"/>{error}{enabled?'；当前显示上次成功读取的数据。':''}</div>{/if}{#if loading}<div class="card empty">正在读取探针状态…</div>{:else if enabled}<ProbeAssets {nodes} {showGlobe} {showAssets}/><div class="section-head space-top"><h2>服务器状态</h2><span class="muted">{#if error}状态待更新 · 上次更新于 {updated}{:else}{onlineCount} 台在线 · {nodes.length-onlineCount} 台离线 · 更新于 {updated}{/if}</span></div><div class="car-grid">{#each nodes as node,i}<article class="card padded"><div class="section-head"><div class="identity"><CountryBadge region={node.region}/><h2>{node.name}</h2></div><Badge value={error?'状态待确认':node.online?'在线':'离线'} kind={!error&&node.online?'success':'warning'}/></div><div class="metric-list probe-metrics"><div><small>CPU</small><strong>{node.online&&node.cpu_pct!=null?`${node.cpu_pct.toFixed(1)}%`:'未知'}</strong></div><div><small>内存</small><strong>{node.online&&node.mem_used!=null&&node.mem_total?`${(node.mem_used/node.mem_total*100).toFixed(1)}%`:'未知'}</strong></div><div><small>磁盘</small><strong>{node.online&&node.disk_used!=null&&node.disk_total?`${(node.disk_used/node.disk_total*100).toFixed(1)}%`:'未知'}</strong></div><div><small>上传 / 下载</small><strong class="network-rate">{node.online?formatRate(node.upload_speed):'未知'} / {node.online?formatRate(node.download_speed):'未知'}</strong></div></div><button class="button small space-top" onclick={()=>{selected=String(i);history();}}>查看历史</button></article>{:else}<div class="card empty">尚未公开任何服务器。</div>{/each}</div>
{#if nodes.length}<section class="card padded space-top"><div class="section-head"><h2>{metricInfo.label}历史</h2><div class="actions"><AppSelect bind:value={selected} options={nodes.map((node,i)=>({value:String(i),label:node.name}))} aria-label="查看服务器历史" onchange={history}/><AppSelect bind:value={metric} options={probeMetrics} aria-label="历史指标" onchange={history}/><div class="segmented">{#each ['1h','6h','24h'] as window}<button class:active={range===window} onclick={()=>{range=window;history();}}>{window}</button>{/each}</div></div></div>{#if metricInfo.network}<p class="hint">{method==='icmp'?'ICMP 探测；失败率表示未收到有效回包。':'TCP 连接失败率不代表 ICMP 丢包。'}展示管理员配置的第一个监测目标，地址不公开。</p>{/if}{#if historyError}<p class="error" role="alert">{series.length?'历史更新失败，当前显示上次数据：':''}{historyError}</p>{/if}{#if series.length}<p class="hint">纵轴 0 – {formatProbeValue(ceiling,metric)} · 最新 {formatProbeValue(series.at(-1)!.value,metric)}</p><svg class="history" viewBox="0 0 720 200" preserveAspectRatio="none" role="img" aria-label={`${nodes[Number(selected)]?.name} ${metricInfo.label}历史`}><path d="M0 20H720 M0 100H720 M0 180H720" stroke="var(--line)" stroke-dasharray="3 5"/><path d={historyPath} stroke="var(--primary)" stroke-width="2" fill="none" vector-effect="non-scaling-stroke"/></svg><div class="section-head"><small class="muted">{new Date(series[0].t*1000).toLocaleTimeString()}</small><small class="muted">{new Date(series[series.length-1].t*1000).toLocaleTimeString()}</small></div>{:else if historyData.state.loading&&!historyData.state.loaded}<div class="empty">正在读取历史数据…</div>{:else if !historyError}<div class="empty">尚无该时间范围的历史数据</div>{/if}</section>{/if}
{:else if !error}<div class="card empty"><Icon name="activity"/><h2>公开展示已关闭</h2><p>管理员可以在探针设置中配置公开范围。</p></div>{/if}
<p class="hint space-top">公开页只接收允许公开的字段。缺失与离线数据标为未知，历史缺口不补零连线；网卡速率不参与套餐计费。</p>
<style>.probe-metrics{grid-template-columns:repeat(auto-fit,minmax(7rem,1fr))}.network-rate{font-size:.9rem;line-height:1.7}.history{width:100%;height:13rem;margin-top:1.5rem}</style>
