<script lang="ts">
 import {onMount,onDestroy} from 'svelte';
 import {page} from '$app/state';
 import AppSelect from '../components/Select.svelte';
 import Icon from '../components/Icon.svelte';
 import {demo,api,getRow,runAction,toast,errorMessage} from '../store.svelte';
 import {parseRoutingJSON,routingFields,quickRules,csvValues,setRuleField,ruleApplies,isCatchAll,ruleSummary,moveRule,type RoutingRule} from '../routing';

 let serverId=$state(''),scope=$state(''),revision=$state(''),defaultOutbound=$state('direct');
 let routing=$state<Record<string,any>>({domainStrategy:'AsIs',rules:[],balancers:[]});
 let outbounds=$state<any[]>([]),inbounds=$state<any[]>([]),selected=$state(-1),balancerIndex=$state(-1);
 let busy=$state(false),loaded=$state(false),error=$state(''),baseline=$state(''),tab=$state('规则');
 let json=$state(''),ruleJSON=$state(''),showRuleJSON=$state(false),dns=$state('{}'),dnsBaseline=$state('{}');
 let task=$state<any>(null),dragFrom=-1,disposed=false,timer:ReturnType<typeof setTimeout>|undefined;
 let preview=$state(''),quick=$state('0'),quickTarget=$state('direct');
 const rules=$derived((routing.rules??[]) as RoutingRule[]);
 const balancers=$derived((routing.balancers??[]) as RoutingRule[]);
 const current=$derived(rules[selected]);
 const balance=$derived(balancers[balancerIndex]);
 const dirty=$derived(loaded&&(JSON.stringify({routing,defaultOutbound})!==baseline || (tab==='JSON'&&json!==JSON.stringify(routing,null,2))));
 const pending=$derived(dirty||dns!==dnsBaseline);
 const visible=$derived(rules.map((rule,index)=>({rule,index})).filter(({rule})=>ruleApplies(rule,scope)));
 const catchAll=$derived(scope?visible.find(({rule})=>isCatchAll(rule)&&rule.inboundTag.includes(scope)):undefined);
 const targetOptions=$derived([...outbounds.map(o=>({value:`out:${o.tag}`,label:`${o.name} · ${o.tag}`})),...balancers.map(b=>({value:`bal:${b.tag}`,label:`均衡 · ${b.tag}`}))]);
 const quickOptions=$derived(quickRules.map((q,i)=>({value:String(i),label:q.name})).filter(o=>o.value!=='6'||outbounds.some(o=>o.tag==='warp-v4')));
 const taskStatus=$derived(task?.status??'');
 const terminal=['成功','失败','不支持','结果未明','已撤回','success','failed','unsupported','unknown','superseded'];

 function accept(data:any){routing=data.routing;defaultOutbound=data.defaultOutbound;revision=data.revision;outbounds=data.outbounds;inbounds=data.inbounds;baseline=JSON.stringify({routing,defaultOutbound});json=JSON.stringify(routing,null,2);loaded=true;preview='';}
 async function load(id:string){if(busy)return;busy=true;error='';loaded=false;serverId=id;selected=-1;balancerIndex=-1;task=null;if(timer)clearTimeout(timer);try{if(!id)return;const [result,server]=await Promise.all([api('/api/actions',{method:'POST',body:JSON.stringify({action:'routing.get',targetId:id})}),getRow('servers',id)]);if(disposed)return;accept(result);dns=JSON.stringify(server.globalConfig?.dns??{},null,2);dnsBaseline=dns;}catch(cause){error=errorMessage(cause);}finally{busy=false;}}
 function selectRule(index:number){selected=index;showRuleJSON=false;ruleJSON=JSON.stringify(rules[index],null,2);}
 function updateRule(key:string,value:string){routing.rules=rules.map((r,i)=>i===selected?setRuleField(r,key,value):r);}
 function target(value:string){const next={...current};delete next.outboundTag;delete next.balancerTag;if(value.startsWith('bal:'))next.balancerTag=value.slice(4);else next.outboundTag=value.slice(4);routing.rules=rules.map((r,i)=>i===selected?next:r);}
 function addRule(preset:RoutingRule={}){const rule:RoutingRule={type:'field',outboundTag:quickTarget,...structuredClone(preset)};if(scope)rule.inboundTag=[scope];routing.rules=[...rules,rule];tab='规则';selectRule(rules.length-1);}
 function parseObject(value:string){const result=JSON.parse(value);if(!result||typeof result!=='object'||Array.isArray(result))throw new Error('JSON 必须是对象');return result;}
 function importRule(){try{const next=parseRoutingJSON(JSON.stringify({rules:[parseObject(ruleJSON)]})).rules[0];if(next.outboundTag==='api')throw new Error('API 规则由主控维护');routing.rules=rules.map((r,i)=>i===selected?next:r);showRuleJSON=false;error='';}catch(cause){error=errorMessage(cause);}}
 function switchTab(next:string){if(tab==='JSON'){try{routing=parseRoutingJSON(json);}catch(cause){error=errorMessage(cause);return;}}tab=next;if(next==='JSON')json=JSON.stringify(routing,null,2);}
 async function poll(id:string){try{const result=await getRow('tasks',id);if(disposed||task?.id!==id)return;task=result;if(!terminal.includes(result.status))timer=setTimeout(()=>poll(id),1500);}catch(cause){if(!disposed)error='任务状态读取失败：'+errorMessage(cause);}}
 async function save(apply=true,validateOnly=false){if(busy||!loaded)return;busy=true;error='';try{if(tab==='JSON')routing=parseRoutingJSON(json);const result=await runAction(validateOnly?'routing.preview':'routing.update',serverId,'servers',{routing,defaultOutbound,revision,apply});if(disposed)return;if(validateOnly){preview=JSON.stringify({routing:result.routing,defaultOutbound:result.defaultOutbound,observatory:result.observatory,burstObservatory:result.burstObservatory},null,2);toast('主控结构校验通过；发布时由 Xray 校验完整配置');return;}accept(result);if(result.applyError)error='配置已保存，但下发失败：'+result.applyError;if(result.task){task=result.task;poll(task.id);}toast(result.task?'已保存并提交，请查看下方执行结果':'路由已保存');}catch(cause){error=errorMessage(cause);}finally{busy=false;}}
 async function reorder(from:number,to:number){if(busy||dirty)return;routing.rules=moveRule(rules,from,to);selected=to;await save();}
 async function removeRule(){if(!current||current.outboundTag==='api')return;routing.rules=rules.filter((_,i)=>i!==selected);selected=-1;await save();}
 function addBalancer(){routing.balancers=[...balancers,{tag:`balance-${Date.now().toString(36)}`,selector:[],strategy:{type:'random'}}];balancerIndex=balancers.length-1;tab='负载均衡';}
 function setBalance(key:string,value:any){routing.balancers=balancers.map((b,i)=>i===balancerIndex?{...b,[key]:value}:b);}
 function balanceRule(){addRule({balancerTag:balance.tag});const next={...rules[selected]};delete next.outboundTag;routing.rules=rules.map((r,i)=>i===selected?next:r);}
 async function deleteBalance(){if(rules.some(r=>r.balancerTag===balance.tag)){error='请先删除或修改引用该均衡器的规则';return;}routing.balancers=balancers.filter((_,i)=>i!==balancerIndex);balancerIndex=-1;await save();}
 async function saveDNS(){busy=true;error='';try{const result=await runAction('server.global.update',serverId,'servers',{section:'dns',config:parseObject(dns),apply:true});dnsBaseline=dns;task=result.task;if(task)poll(task.id);toast('DNS 已保存并提交');}catch(cause){error=errorMessage(cause);}finally{busy=false;}}
 function outboundName(tag:string){return outbounds.find(o=>o.tag===tag)?.name??tag;}
 onMount(()=>{scope=page.url.searchParams.get('inbound')??'';const id=page.url.searchParams.get('server')??demo.data.servers[0]?.id??'';if(id)load(id);});
 onDestroy(()=>{disposed=true;if(timer)clearTimeout(timer);});
</script>

<div class="page-head"><div><div class="eyebrow">工作区 / Xray</div><h1>路由与 DNS</h1><p>从上到下匹配，命中第一条后转发到指定出口。</p></div><div class="actions"><button class="button" disabled={busy||!loaded} onclick={()=>save(false,true)}>校验与预览</button><button class="button primary" disabled={busy||!loaded} onclick={()=>tab==='DNS'?saveDNS():save()}><Icon name="play"/>{busy?'处理中…':'保存并发布'}</button></div></div>
<section class="card routing-toolbar"><label class="field">服务器<AppSelect value={serverId} onchange={load} options={[{value:'',label:'选择服务器'},...demo.data.servers.map(s=>({value:s.id,label:s.name}))]} disabled={busy||pending} aria-label="路由服务器"/></label><label class="field">查看范围<AppSelect bind:value={scope} options={[{value:'',label:'全部入站'},...inbounds.map(i=>({value:i.tag,label:`${i.name} · ${i.tag}`}))]} disabled={busy} aria-label="路由入站范围"/></label><button class="button" disabled={busy||!serverId} onclick={()=>load(serverId)}>{pending?'放弃更改并重载':'重新载入'}</button></section>
{#if error}<p class="status-banner error" role="alert">{error}</p>{/if}
{#if task}<section class="task-state" class:failed={['失败','failed','不支持','结果未明'].includes(taskStatus)} role="status"><span><strong>本次发布：{taskStatus}</strong>{#if task.error}<span> · {task.error}</span>{/if}</span><a class="quiet-link" href={`/tasks?detail=${encodeURIComponent(task.id)}`}>查看执行结果 →</a><button class="button small" onclick={()=>poll(task.id)}>刷新状态</button></section>{/if}
{#if !loaded}<section class="card empty">{busy?'正在读取路由配置…':'请选择服务器以管理路由'}</section>{:else}
<div class="tabs">{#each ['规则','负载均衡','DNS','JSON'] as item}<button class:active={tab===item} disabled={busy} onclick={()=>switchTab(item)}>{item}{item==='规则'?` · ${rules.length}`:item==='负载均衡'?` · ${balancers.length}`:''}</button>{/each}<span class="edit-state">{pending?'有未发布更改':'已保存'}</span></div>
{#if tab==='规则'}
<section class="routing-settings"><label class="field">默认出站<AppSelect bind:value={defaultOutbound} options={outbounds.map(o=>({value:o.tag,label:`${o.name} · ${o.tag}`}))} disabled={busy} aria-label="默认出站"/></label><label class="field">域名解析策略<AppSelect value={routing.domainStrategy??'AsIs'} onchange={v=>routing.domainStrategy=v} options={['AsIs','IPIfNonMatch','IPOnDemand']} disabled={busy} aria-label="域名解析策略"/></label><p class="hint">未命中规则时走默认出站。单条规则的多个条件须同时满足。</p></section>
{#if catchAll}<p class="status-banner" role="status">第 {catchAll.index+1} 条规则接管此入站的全部流量，排在它后面的全局规则与默认出站不再生效。</p>{/if}
<div class="routing-actions"><AppSelect bind:value={quick} options={quickOptions} disabled={busy} aria-label="快捷规则"/>{#if !('outboundTag' in quickRules[Number(quick)].rule)}<AppSelect bind:value={quickTarget} options={outbounds.map(o=>({value:o.tag,label:o.name}))} disabled={busy} aria-label="快捷规则出站"/>{/if}<button class="button" disabled={busy} onclick={()=>addRule(quickRules[Number(quick)].rule)}>快捷添加</button><button class="button" disabled={busy} onclick={()=>addRule()}><Icon name="plus"/>自定义规则</button><button class="button" disabled={busy} onclick={addBalancer}>负载均衡</button></div>
<div class="routing-split"><section class="card rule-list"><div class="list-heading"><strong>{scope?'此入站的有效规则':'全部路由规则'}</strong><small>按实际匹配顺序</small></div><p class="hint list-hint">拖动或用上下按钮排序后自动发布。{dirty?'请先保存当前编辑再排序。':''}</p>
{#each visible as {rule,index} (index)}
<div class="rule-row" class:selected={selected===index} class:protected={rule.outboundTag==='api'} draggable={!busy&&!dirty&&rule.outboundTag!=='api'} ondragstart={()=>dragFrom=index} ondragover={e=>e.preventDefault()} ondrop={e=>{e.preventDefault();reorder(dragFrom,index);}} role="group" aria-label={`第 ${index+1} 条规则`}>
<button class="rule-select" onclick={()=>selectRule(index)}><span class="rule-number">{index+1}</span><span class="rule-copy"><span class="rule-meta">{rule.outboundTag==='api'?'系统 API':rule.inboundTag?.length?'专属 · '+rule.inboundTag.join(', '):'全局规则'}</span><strong>{ruleSummary(rule)}</strong><span class="rule-target">→ {rule.balancerTag?'均衡 · '+rule.balancerTag:outboundName(rule.outboundTag)}</span></span></button><div class="order-buttons"><button aria-label={`上移规则 ${index+1}`} disabled={busy||dirty||index===0||rule.outboundTag==='api'||rules[index-1]?.outboundTag==='api'} onclick={()=>reorder(index,index-1)}>↑</button><button aria-label={`下移规则 ${index+1}`} disabled={busy||dirty||index===rules.length-1||rule.outboundTag==='api'} onclick={()=>reorder(index,index+1)}>↓</button></div></div>
{:else}<div class="empty">暂无规则，流量使用默认出站。</div>{/each}
<div class="default-summary"><small>未匹配流量</small><strong>→ {outboundName(defaultOutbound)}</strong></div></section>
<section class="card padded rule-detail">{#if current}<div class="section-head"><h2>规则 {selected+1}</h2><span class="hint">{current.outboundTag==='api'?'系统规则 · 只读':current.inboundTag?.length?'入站专属':'全部入站'}</span></div><fieldset disabled={busy||current.outboundTag==='api'}><label class="field space-top">转发到<AppSelect value={current.balancerTag?`bal:${current.balancerTag}`:`out:${current.outboundTag??''}`} onchange={target} options={targetOptions} disabled={busy||current.outboundTag==='api'} aria-label="规则目标"/></label><div class="form-grid space-top">{#each routingFields as [key,label,placeholder]}<label class="field" class:full={['domain','ip','inboundTag','attrs'].includes(key)}>{label}<input value={Array.isArray(current[key])?current[key].join(', '):current[key]??''} {placeholder} oninput={e=>updateRule(key,e.currentTarget.value)}/></label>{/each}</div><p class="hint">数组字段用逗号分隔，空字段不提交。入站范围留空即为全局规则。</p><div class="actions space-top"><button class="button" onclick={()=>{ruleJSON=JSON.stringify(current,null,2);showRuleJSON=!showRuleJSON;}}>高级 JSON</button><button class="button danger" onclick={removeRule}>删除并发布</button><button class="button primary" onclick={()=>save()}>保存并发布</button></div>{#if showRuleJSON}<label class="field space-top">规则 JSON<textarea class="code-editor rule-json" bind:value={ruleJSON} spellcheck="false"></textarea></label><button class="button space-top" onclick={importRule}>采用 JSON 修改</button>{/if}</fieldset><details class="space-top"><summary>JSON 预览</summary><pre>{JSON.stringify(current,null,2)}</pre></details>{:else}<div class="empty detail-empty"><Icon name="route" size={28}/><h2>选择一条路由规则</h2><p>编辑匹配条件和目标出口，或添加新规则。</p></div>{/if}</section></div>
{:else if tab==='负载均衡'}
<div class="routing-actions"><button class="button" disabled={busy} onclick={addBalancer}><Icon name="plus"/>新增均衡器</button></div><div class="routing-split"><section class="card rule-list">{#each balancers as b,i}<button class="balance-row" class:active={balancerIndex===i} onclick={()=>balancerIndex=i}><strong>{b.tag}</strong><small>{b.strategy?.type??'random'} · {(b.selector??[]).join(', ')}</small></button>{:else}<div class="empty">暂无均衡器</div>{/each}</section><section class="card padded">{#if balance}<h2>编辑均衡器</h2><fieldset disabled={busy}><div class="form-grid space-top"><label class="field">标签<input value={balance.tag} oninput={e=>setBalance('tag',e.currentTarget.value)}/></label><label class="field">策略<AppSelect value={balance.strategy?.type??'random'} onchange={v=>setBalance('strategy',{...balance.strategy,type:v})} options={['random','roundRobin','leastPing','leastLoad']} disabled={busy} aria-label="均衡策略"/></label><label class="field full">出站标签前缀<input value={(balance.selector??[]).join(', ')} placeholder="例如 landing-, proxy-" oninput={e=>setBalance('selector',csvValues(e.currentTarget.value))}/></label><label class="field full">备用出站<AppSelect value={balance.fallbackTag??''} onchange={v=>setBalance('fallbackTag',v)} options={[{value:'',label:'不指定'},...outbounds.map(o=>({value:o.tag,label:o.name}))]} disabled={busy} aria-label="备用出站"/></label></div><p class="hint">当前匹配：{outbounds.filter(o=>balance.selector?.some((p:string)=>o.tag.startsWith(p))).map(o=>o.name+' · '+o.tag).join('、')||'无'}</p>{#if ['leastPing','leastLoad'].includes(balance.strategy?.type)}<p class="hint">发布时自动生成{balance.strategy.type==='leastPing'?' observatory':' burstObservatory'} 探测配置，默认每分钟探测一次。</p>{/if}<div class="actions space-top"><button class="button" onclick={balanceRule}>为它添加路由规则</button><button class="button danger" onclick={deleteBalance}>删除并发布</button><button class="button primary" onclick={()=>save()}>保存并发布</button></div></fieldset>{:else}<div class="empty">选择或新增一个均衡器</div>{/if}</section></div>
{:else if tab==='DNS'}<section class="card padded"><h2>DNS 配置</h2><label class="field space-top">DNS JSON<textarea class="code-editor" bind:value={dns} spellcheck="false" disabled={busy}></textarea></label></section>
{:else}<section class="card padded"><h2>完整路由 JSON</h2><p class="hint">保留高级字段；系统 API 规则由主控维护，并固定在规则最前面。</p><label class="field space-top">路由 JSON<textarea class="code-editor" bind:value={json} spellcheck="false" disabled={busy}></textarea></label></section>{/if}
{#if preview}<section class="card padded space-top"><h2>编译预览</h2><pre>{preview}</pre></section>{/if}
{/if}

<style>
 .routing-toolbar{display:flex;gap:18px;align-items:end;padding:18px;margin-bottom:22px}.routing-toolbar .field{flex:1;max-width:440px}.routing-settings{display:grid;grid-template-columns:1fr 1fr 1.3fr;gap:20px;align-items:center;margin:22px 0}.routing-actions{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin:18px 0}.routing-actions :global(.app-select-trigger){width:auto;min-width:165px}.routing-split{display:grid;grid-template-columns:minmax(0,2fr) minmax(0,3fr);gap:20px;align-items:start}.rule-list{overflow:hidden}.list-heading{display:flex;justify-content:space-between;gap:12px;padding:20px 18px 0}.list-heading small,.rule-meta,.rule-target,.default-summary small,.balance-row small{color:var(--muted)}.list-hint{padding:0 18px}.rule-row{display:flex;align-items:center;margin:8px 10px;border:1px solid transparent;border-radius:9px;background:var(--bg)}.rule-row.selected{border-color:var(--accent);background:color-mix(in srgb,var(--accent) 7%,var(--card))}.rule-select{display:flex;align-items:start;gap:12px;padding:15px 12px;flex:1;min-width:0;text-align:left;background:none;border:0;color:inherit;cursor:pointer}.rule-number{font-size:12px;color:var(--muted);padding-top:2px;font-variant-numeric:tabular-nums}.rule-copy{display:grid;gap:7px;min-width:0}.rule-copy strong{font-size:13px;overflow-wrap:anywhere;line-height:1.55}.rule-meta,.rule-target{font-size:11px;overflow-wrap:anywhere}.order-buttons{display:grid;gap:3px;padding:0 8px}.order-buttons button{background:none;border:0;color:var(--muted);cursor:pointer;padding:5px 8px}.order-buttons button:disabled{opacity:.25}.default-summary{display:grid;gap:9px;padding:20px;border-top:1px solid var(--line);margin-top:16px}.default-summary strong{font-size:13px}.rule-detail{min-height:460px}fieldset{border:0;padding:0;margin:0;min-width:0}.detail-empty{min-height:375px;display:flex;flex-direction:column;justify-content:center;align-items:center;gap:12px}.detail-empty p{font-size:12px}.edit-state{margin-left:auto;align-self:center;font-size:12px;color:var(--muted)}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px;line-height:1.65;padding:16px;background:var(--bg);border-radius:8px;max-height:550px;overflow:auto}.rule-json{min-height:250px!important}.balance-row{display:grid;gap:8px;width:100%;padding:20px;text-align:left;border:0;border-bottom:1px solid var(--line);background:none;color:inherit;cursor:pointer}.balance-row.active{background:color-mix(in srgb,var(--accent) 7%,var(--card))}.task-state{display:flex;gap:14px;align-items:center;flex-wrap:wrap;padding:14px 18px;border:1px solid var(--line);border-radius:10px;margin:16px 0;font-size:12px}.task-state.failed{color:var(--danger)}.task-state>a{margin-left:auto}.protected{opacity:.8}summary{cursor:pointer;font-size:12px;color:var(--muted)}
 @media(max-width:1000px){.routing-split{grid-template-columns:1fr}.routing-settings{grid-template-columns:1fr 1fr}.routing-settings>p{grid-column:1/-1}.routing-toolbar{flex-wrap:wrap}.routing-toolbar .field{min-width:210px}}
 @media(max-width:600px){.routing-settings{grid-template-columns:1fr}.routing-toolbar .field{max-width:none}.routing-actions>*{flex:1}.routing-toolbar{gap:12px}.list-heading{flex-wrap:wrap}}
</style>
