<script lang="ts">
 import {page} from '$app/state';
 import SystemUpdates from '../components/SystemUpdates.svelte';
 import UpgradeBackups from '../components/UpgradeBackups.svelte';
 import DatabaseManagement from '../components/DatabaseManagement.svelte';
 import IPDatabase from '../components/IPDatabase.svelte';
 import TelegramControls from '../components/TelegramControls.svelte';
 import BehaviorEditor from '../components/BehaviorEditor.svelte';
 import TurnstileWidget from '../components/TurnstileWidget.svelte';import RemoteBackup from '../components/RemoteBackup.svelte';import IdentitySecurity from '../components/IdentitySecurity.svelte';import AppSelect from '../components/Select.svelte';import {KOMARI_PROVIDER,KOMARI_VERSION} from '../probe';import Icon from '../components/Icon.svelte';import {demo,saveSettings,toast,errorMessage,runAction,api,downloadAuthenticated,returnToLogin} from '../store.svelte';
 let behaviorText=$state(demo.settings.behaviorLimits?JSON.stringify(demo.settings.behaviorLimits,null,2):'');let turnstileTestToken=$state(''),turnstileTestVersion=$state(0),tab=$state('工作区'),busy=$state(false),error=$state(''),backupFile=$state<File|null>(null),restoreConfirm=$state('');
 const notificationEventOptions=[['account.login','账户登录'],['task.failed','任务失败'],['subscription.changed','套餐状态变化'],['subscription.unavailable','套餐暂不可用'],['subscription.expiring','套餐即将到期（7 / 3 / 1 天）'],['limit.trigger','限速触发'],['limit.release','限速释放']];const sections=['工作区','外观','登录与安全','通知渠道','备份与恢复','API 与 MCP','成员自助','代理网络','行为限速','探针监控','IP 数据库','数据库','系统维护'];
 let settings=$state<Record<string,any>>({...demo.settings,blockProxyIPv6:demo.settings.blockProxyIPv6!==false,publicServerIds:demo.settings.publicServerIds??[],notificationEvents:{...(demo.settings.notificationEvents??{})}});
 $effect(()=>{if(page.url.searchParams.get('section')==='behavior')tab='行为限速';});
 function draft(){const local={...settings};const behavior=behaviorText.trim()?JSON.parse(behaviorText):null;if(behavior&&(typeof behavior!=='object'||Array.isArray(behavior)))throw new Error('行为限速须为 JSON 对象');local.behaviorLimits=behavior;delete local.remoteBackup;return {...demo.settings,...local};}
 async function save(){if(busy)return;busy=true;error='';try{settings=await saveSettings(draft());toast('设置已保存');}catch(cause){error=errorMessage(cause);}finally{busy=false;}}
 async function action(name:string){busy=true;try{await saveSettings(draft());const result=await runAction(name,undefined,undefined,{channel:settings.release==='预发布'?'prerelease':'stable'});if(name==='backup.create'&&result.url)await downloadAuthenticated(result.url,result.name??'aswired-backup.zip');toast(result.message??(result.task?'请求已受理，请查看执行状态':'操作完成'));}catch(cause){toast(errorMessage(cause));}finally{busy=false;}}
 const switches=$derived(tab==='成员自助'?[['selfForward','允许个人转发','限制可用服务器、端口与操作次数'],['selfOutbound','允许个人出站','由主控检查协议与目标范围']]:tab==='探针监控'?[['probePublicEnabled','公开展示','只公开允许展示的服务器与指标'],['showCPU','显示 CPU','Komari CPU 指标'],['showMemory','显示内存','缺失数据展示为未知'],['showTraffic','显示网卡速率','监控数据不代替 Xray 用户流量'],['showNetworkQuality','公开网络质量历史','仅公开探测结果，不公开目标地址'],['showGlobe','显示地球视图','公开管理员填写的服务器经纬度'],['showAssets','显示续费时间轴','公开填写的到期日、续费费用、周期和服务商信息']]:[]);
 async function testTurnstile(){busy=true;error='';try{await saveSettings(draft());await api('/api/account/turnstile/test',{method:'POST',body:JSON.stringify({token:turnstileTestToken})});toast('人机验证配置有效');}catch(cause){error=errorMessage(cause);}finally{busy=false;turnstileTestToken='';turnstileTestVersion++;}}
 async function restoreBackup(){if(!backupFile||restoreConfirm!=='覆盖恢复'||busy)return;busy=true;error='';try{await api('/api/backups/restore?confirm=restore',{method:'POST',headers:{'Content-Type':'application/zip'},body:backupFile});backupFile=null;restoreConfirm='';returnToLogin('备份已恢复，请使用恢复后的账户重新登录');}catch(cause){error=errorMessage(cause);}finally{busy=false;}}
</script>
<style>
 .komari-binding{display:grid;grid-template-columns:minmax(0,1fr) auto 16px;gap:12px;align-items:center;padding:12px 0;border-bottom:1px solid var(--border);color:inherit;text-decoration:none}
 .komari-binding span{min-width:0;overflow-wrap:anywhere}
 .komari-binding small{display:block;margin-top:4px;color:var(--muted);font-size:12px}
 .komari-binding:hover{color:var(--accent)}
</style>
<div class="page-head"><div><div class="eyebrow">工作区 / 偏好设置</div><h1>系统设置</h1><p>配置你的主控与工作区。</p></div>{#if tab!=='数据库'}<button class="button primary" disabled={busy} onclick={save}>{busy?'保存中…':'保存设置'}</button>{/if}</div>{#if error}<p class="error" role="alert">{error}</p>{/if}
<div class="settings-grid"><nav class="settings-nav" aria-label="设置分类">{#each sections as section}<button class:active={tab===section} onclick={()=>tab=section}>{section}</button>{/each}</nav><section class="card padded"><div class="section-head"><h2>{tab}</h2><Icon name="sliders"/></div>
{#if tab==='工作区'}<div class="form-grid"><label class="field">工作区名称<input bind:value={settings.workspace} placeholder="ASWired"/></label><label class="field">周期时区<AppSelect bind:value={settings.timezone} options={['Asia/Shanghai','Asia/Hong_Kong','UTC']} aria-label="周期时区"/></label><label class="field full">公开地址<input type="url" bind:value={settings.domain} placeholder="https://panel.example.com"/></label></div>
{:else if tab==='外观'}<p class="muted">工作区固定使用深色外观。自定义 CSS 保存后会应用到网站与独立探针。</p><label class="field space-top">自定义 CSS<textarea class="code-editor" spellcheck="false" bind:value={settings.customCSS}></textarea></label><p class="hint">样式异常时，使用下面的恢复入口跳过自定义 CSS，再修正或清空。</p><a class="button space-top" href="/settings?nocss=1">恢复默认外观后编辑</a>{:else if tab==='登录与安全'}<IdentitySecurity/><section class="space-top"><h3>登录人机验证</h3><label class="tag space-top"><input type="checkbox" bind:checked={settings.turnstileEnabled}/>启用 Cloudflare Turnstile</label><div class="form-grid space-top"><label class="field">Site Key<input bind:value={settings.turnstileSiteKey}/></label><label class="field">Secret<input type="password" autocomplete="off" bind:value={settings.turnstileSecret} placeholder="留空保留已有密钥"/></label><label class="field full">允许验证的主机名<input bind:value={settings.turnstileHostname} placeholder="留空使用主控公开地址的主机名"/></label></div>{#if settings.turnstileSiteKey}<div class="space-top">{#key settings.turnstileSiteKey+':'+turnstileTestVersion}<TurnstileWidget siteKey={settings.turnstileSiteKey} bind:token={turnstileTestToken}/>{/key}</div><button class="button space-top" disabled={busy||!turnstileTestToken} onclick={testTurnstile}>保存并验证配置</button>{/if}<p class="hint">先完成自测，再启用。密码登录会使用深色验证组件，令牌由主控向 Cloudflare 校验。</p></section><section class="space-top"><h3>隐藏入口</h3><label class="tag space-top"><input type="checkbox" bind:checked={settings.silentMode}/>隐藏未授权访问者的登录入口</label><label class="field space-top">入口密钥（至少 24 字符）<input type="password" autocomplete="off" bind:value={settings.entryKey} placeholder="留空保留已有密钥"/></label><p class="hint">保存后通过 /entrance/你的入口密钥 唤醒当前浏览器 15 分钟，再使用账户登录。请先妥善保存入口密钥。访问地址会立即清除密钥；有效订阅也可唤醒入口。</p></section>
{:else if tab==='通知渠道'}<div class="stack"><label class="field">Telegram Bot Token<input type="password" autocomplete="new-password" bind:value={settings.telegramToken} placeholder="留空保留已有凭据"/></label><label class="field">Telegram 接收 Chat ID<input bind:value={settings.telegramChatId}/></label><label class="field">Telegram Webhook Secret<input type="password" autocomplete="off" bind:value={settings.telegramWebhookSecret}/></label><label class="tag"><input type="checkbox" bind:checked={settings.telegramMiniAppEnabled}/>启用 Telegram Mini App 登录</label><label class="field">SMTP 地址<input bind:value={settings.email}/></label><label class="field">Webhook 地址<input type="url" bind:value={settings.webhook}/></label></div><button class="button space-top" disabled={busy} onclick={()=>action('notification.channel.test')}>测试通知渠道</button><p class="hint">只有渠道测试和投递结果确认成功后，才表示通知已发送。</p><TelegramControls saveConfig={()=>saveSettings(draft())}/><h3 class="space-top">自动通知事件</h3><p class="hint">选择要投递的事件。成员通知发给其已绑定 Telegram，管理事件发给配置的通知渠道。</p><div class="stack space-top">{#each notificationEventOptions as [event,label]}<label class="tag"><input type="checkbox" bind:checked={settings.notificationEvents[event]}/>{label}</label>{/each}</div>
{:else if tab==='备份与恢复'}<button class="button primary space-top" disabled={busy} onclick={()=>action('backup.create')}>创建主控备份</button><p class="hint">备份由主控生成，通过认证后下载。</p><RemoteBackup/><h3 class="space-top">从备份恢复</h3><p class="hint">恢复会覆盖当前数据库和设置。先下载当前备份，再选择要恢复的 ZIP 文件。</p><label class="field space-top">备份文件<input type="file" accept=".zip,application/zip" onchange={event=>{backupFile=event.currentTarget.files?.[0]??null;restoreConfirm='';}}/></label><label class="field space-top">输入「覆盖恢复」确认<input bind:value={restoreConfirm} autocomplete="off"/></label><button class="button danger space-top" disabled={busy||!backupFile||restoreConfirm!=='覆盖恢复'} onclick={restoreBackup}>上传并覆盖恢复</button><UpgradeBackups/>
{:else if tab==='API 与 MCP'}<div class="status-banner">API Token 与网站登录 JWT 分开管理；MCP 权限继承账户权限。</div><p class="hint space-top">接口可用情况以主控能力为准。工具必须经过主控认证与权限检查。</p><a class="button space-top" href="/account">管理 API Token</a>
{:else if tab==='成员自助'}<div class="form-grid"><label class="field">每人转发上限<input type="number" min="0" bind:value={settings.forwardLimit}/></label><label class="field">每天操作上限<input type="number" min="0" bind:value={settings.dailyLimit}/></label></div>
{:else if tab==='代理网络'}<label class="tag"><input type="checkbox" bind:checked={settings.blockProxyIPv6}/>屏蔽代理业务 IPv6（默认开启）</label><p class="hint space-top">开启后，阻止受管代理业务访问 IPv6 目标，并关闭生成的完整订阅配置中的 IPv6 解析。服务器自身 IPv6、SSH、主控连接及服务端中转连接保持原有配置；保留订阅中的节点地址。</p><p class="hint">保存后请更新客户端订阅；仅有 AAAA 记录的节点域名可能无法被客户端解析，请使用可解析的地址。URI 链接订阅无法携带 DNS 开关，需依靠节点侧保护。</p><p class="hint">现有节点须将 Agent 升级至 v1.0.10 或更新版本，再重新下发配置。缺少 IPv6 保护能力的 Agent 会拒绝下发；请以任务执行成功为准。行为限速规则无需升级 Agent。</p><a class="button space-top" href="/servers">查看服务器与配置下发</a>
{:else if tab==='行为限速'}<p class="muted">全局未配置时使用均衡规则，允许短时高速，持续大流量才限速。套餐和成员可覆盖全局，已有明确配置保持不变。</p><BehaviorEditor bind:value={behaviorText} inherit={false}/><a class="button space-top" href="/limits">查看限速规则与触发记录</a>{:else if tab==='探针监控'}<div class="form-grid"><label class="field">探针<input value={KOMARI_PROVIDER} readonly/></label><label class="field">支持版本<input value={KOMARI_VERSION} readonly/></label><label class="field full">Komari 面板地址<input type="url" bind:value={settings.probeBaseUrl} placeholder="https://komari.example.com"/></label><label class="field full">Komari API Key<input type="password" autocomplete="new-password" bind:value={settings.probeApiKey} placeholder="留空保留已有凭据"/></label></div><div class="actions space-top"><button class="button" disabled={busy} onclick={()=>action('komari.test')}>测试连接</button><button class="button" disabled={busy} onclick={()=>action('komari.sync')}>立即同步</button></div><div class="field space-top"><span>服务器绑定</span><div class="stack">{#each demo.data.servers as server}<a class="komari-binding" href={`/servers?edit=${encodeURIComponent(server.id)}`}><span><strong>{server.name}</strong>{#if server.komariUUID}<small>{server.komariUUID}</small>{/if}</span><span>{server.probeStatus || '等待同步'}</span><Icon name="right" size={16}/></a>{/each}</div></div><div class="field space-top"><span>公开服务器</span><div class="stack">{#each demo.data.servers as server}<label class="tag"><input type="checkbox" bind:group={settings.publicServerIds} value={server.id}/>{server.name}</label>{:else}<p class="hint">添加服务器后可选择公开范围。</p>{/each}</div></div>
{:else if tab==='数据库'}<DatabaseManagement/>{:else if tab==='IP 数据库'}<IPDatabase/>{:else if tab==='系统维护'}<div class="form-grid"><label class="field">升级通道<AppSelect bind:value={settings.release} options={['稳定版','预发布']} aria-label="升级通道"/></label><label class="field">日志保留 / 天<input type="number" min="7" bind:value={settings.logDays}/></label></div><SystemUpdates channel={settings.release}/>{/if}
{#each switches as [key,label,hint]}<div class="toggle-row"><div><strong>{label}</strong><p class="muted">{hint}</p></div><button class:on={settings[key]} class="toggle" role="switch" aria-checked={!!settings[key]} aria-label={label} onclick={()=>settings[key]=!settings[key]}></button></div>{/each}
</section></div>
