<script lang="ts">
 import {Star} from '@lucide/svelte';
 import Icon from '../components/Icon.svelte';
 import Modal from '../components/Modal.svelte';
 import AppSelect from '../components/Select.svelte';
 import {api,demo,runAction,getRow,removeRow,toast,errorMessage,download} from '../store.svelte';
 import type {Row} from '../data';
 const types=['Clash','Surge','Loon'];
 const methods=[{id:'upload',name:'上传',icon:'up'},{id:'paste',name:'粘贴',icon:'file'},{id:'blank',name:'空白',icon:'plus'},{id:'url',name:'链接',icon:'link'},{id:'v2',name:'V2 导入',icon:'refresh'},{id:'subscription',name:'从订阅',icon:'rss'}];
 let filter=$state('全部'),query=$state(''),busy=$state(''),error=$state('');
 let createOpen=$state(false),editOpen=$state(false),previewOpen=$state(false),visibilityOpen=$state(false),deleteOpen=$state(false);
 let form=$state<Row>({id:'',type:'Clash',name:'',content:''}),method=$state('upload'),sourceURL=$state(''),subscriptionId=$state(''),preview=$state(''),warnings=$state<string[]>([]),history=$state<Row[]>([]),visibility=$state<Record<string,boolean>>({}),selected=$state<Row>({id:''}),readOnly=$state(false),fileReady=$state(false),prepared=$state(false);
 const rows=$derived((demo.data.policies??[]).filter(row=>(filter==='全部'||kind(row)===filter)&&String(row.name).toLowerCase().includes(query.toLowerCase())));
 const extension=$derived(form.type==='Clash'?'yaml':form.type==='Surge'?'conf':'lcf');
 function queryTemplate(action:'template.preview'|'template.history',targetId?:string,params?:Record<string,any>){return api('/api/actions',{method:'POST',body:JSON.stringify({action,targetId,collection:'policies',params})});}
 function kind(row:Row){return types.find(type=>type.toLowerCase()===String(row.type??'clash').toLowerCase())??'Clash';}
 async function work(key:string,fn:()=>Promise<void>){if(busy)return;busy=key;error='';try{await fn();}catch(cause){error=errorMessage(cause);}finally{busy='';}}
 function create(){form={id:'',name:'',type:filter==='全部'?'Clash':filter,content:''};method='upload';sourceURL='';subscriptionId='';warnings=[];history=[];preview='';error='';fileReady=false;prepared=false;createOpen=true;}
 function chooseType(type:string){form.type=type;form.content='';fileReady=false;prepared=false;warnings=[];if(method==='v2'&&type!=='Clash')method='upload';}
 function chooseMethod(value:string){method=value;form.content='';sourceURL='';fileReady=false;prepared=false;warnings=[];}
 async function readFile(event:Event){const file=(event.currentTarget as HTMLInputElement).files?.[0];if(!file)return;fileReady=false;if(file.size>1024*1024){error='模板文件不能超过 1 MiB';return;}try{form.content=await file.text();if(!form.name)form.name=file.name;fileReady=true;prepared=false;error='';}catch(cause){error=errorMessage(cause);}}
 function params(){return {name:form.name.trim(),type:form.type,content:form.content,version:method==='v2'&&!prepared?2:3,recordVersion:form.recordVersion,...(createOpen&&!prepared&&method==='url'?{url:sourceURL.trim()}:{}),...(createOpen&&!prepared&&method==='subscription'?{subscriptionId}:{})};}
 function validateInput(){if(!form.name.trim())throw new Error('请填写模板名称');if(createOpen&&!prepared){if(method==='url'&&!sourceURL.trim())throw new Error('请输入模板链接');if(method==='subscription'&&!subscriptionId)throw new Error('请选择订阅');if(method==='upload'&&!fileReady)throw new Error('请选择模板文件');if(['paste','v2'].includes(method)&&!form.content.trim())throw new Error('请输入模板内容');}}
 async function prepare(){await work('prepare',async()=>{validateInput();const result=await queryTemplate('template.preview',form.id||undefined,params());form.content=result.content;preview=result.preview;warnings=result.warnings??[];prepared=true;});}
 async function save(){await work('save',async()=>{validateInput();if(createOpen&&!prepared&&method!=='blank'){const checked=await queryTemplate('template.preview',undefined,params());form.content=checked.content;preview=checked.preview;warnings=checked.warnings??[];prepared=true;if(warnings.length)return;}const result=await runAction('template.import',form.id||undefined,'policies',params());form=result.row;createOpen=false;editOpen=false;toast('模板已保存');});}
 async function edit(row:Row,view=false){await work('load',async()=>{form=await getRow('policies',row.id);form.type=kind(form);method='paste';prepared=true;warnings=form.warnings??[];preview='';readOnly=view;if(view){preview=form.content;previewOpen=true;}else{const result=await queryTemplate('template.history',row.id);history=result.versions??[];editOpen=true;}});}
 async function previewOutput(){await work('preview',async()=>{const result=await queryTemplate('template.preview',form.id||undefined,{type:form.type,content:form.content,version:3});preview=result.preview;warnings=result.warnings??[];readOnly=false;previewOpen=true;});}
 async function restore(version:Row){await work('restore',async()=>{const result=await runAction('template.restore',form.id,'policies',{versionId:version.id,recordVersion:form.recordVersion});form=result.row;history=(await queryTemplate('template.history',form.id)).versions??[];toast('历史版本已恢复');});}
 async function setDefault(row:Row){await work(row.id,async()=>{await runAction('template.default',row.id,'policies',{enabled:!row.isDefault});toast(row.isDefault?'已取消默认模板':`已设为 ${kind(row)} 默认模板`);});}
 function showVisibility(){error='';visibility=Object.fromEntries((demo.data.policies??[]).map(row=>[row.id,!!row.userVisible]));visibilityOpen=true;}
 async function saveVisibility(){await work('visibility',async()=>{await runAction('template.visibility',undefined,'policies',{visibility});visibilityOpen=false;toast('用户可见性已保存');});}
 async function remove(){await work('delete',async()=>{await removeRow('policies',selected.id);deleteOpen=false;toast('模板已删除');});}
</script>

<div class="page-head"><h1><Icon name="code" size={23}/>模板管理</h1><div class="actions"><a class="button" href="/subscription-generator"><Icon name="rss"/>生成订阅</a><button class="button" onclick={showVisibility} disabled={!!busy}><Icon name="eye"/>用户可见性</button><button class="button primary" onclick={create} disabled={!!busy}><Icon name="plus"/>新建模板</button></div></div>
<div class="template-toolbar"><div class="segments" role="tablist" aria-label="模板类型筛选">{#each ['全部',...types] as type}<button role="tab" aria-selected={filter===type} class:active={filter===type} onclick={()=>filter=type}>{type}</button>{/each}</div><div class="search-input"><Icon name="search"/><input bind:value={query} aria-label="搜索模板" placeholder="搜索模板名称"/></div></div>
{#if error&&!createOpen&&!editOpen&&!previewOpen&&!visibilityOpen&&!deleteOpen}<p class="error" role="alert">{error}</p>{/if}
<section aria-label="模板列表" class="template-list"><div class="list-heading"><span>模板名称</span><span>操作</span></div>{#each rows as row (row.id)}<div class="template-row"><div class="template-name"><Icon name="file"/><button class="name-link" disabled={!!busy} onclick={()=>edit(row)}>{row.name}</button><span class="tag">{kind(row)}</span>{#if row.isDefault}<span class="default-label">默认</span>{/if}{#if row.userVisible}<span class="visibility-label" title="用户可选"><Icon name="eye" size={14}/><span>用户可选</span></span>{/if}</div><div class="row-actions"><button class="icon-button" class:chosen={!!row.isDefault} title={row.isDefault?'取消默认模板':'设为默认模板'} aria-label={`${row.isDefault?'取消默认模板':'设为默认模板'} ${row.name}`} disabled={!!busy} onclick={()=>setDefault(row)}><Star size={17} fill={row.isDefault?'currentColor':'none'} strokeWidth={1.65}/></button><button class="icon-button" title="编辑模板" aria-label={`编辑模板 ${row.name}`} disabled={!!busy} onclick={()=>edit(row)}><Icon name="edit"/></button><button class="icon-button" title="查看模板" aria-label={`查看模板 ${row.name}`} disabled={!!busy} onclick={()=>edit(row,true)}><Icon name="eye"/></button><button class="icon-button" title="下载模板" aria-label={`下载模板 ${row.name}`} disabled={!!busy} onclick={()=>work('download',async()=>{const result=await getRow('policies',row.id);download(result.name,result.content);})}><Icon name="download"/></button><button class="icon-button danger-action" title="删除模板" aria-label={`删除模板 ${row.name}`} disabled={!!busy} onclick={()=>{selected=row;error='';deleteOpen=true;}}><Icon name="trash"/></button></div></div>{:else}<div class="empty"><Icon name="code" size={30}/><p>{query?'没有匹配的模板':'暂无模板'}</p><button class="button" onclick={create}><Icon name="plus"/>新建模板</button></div>{/each}</section>

{#snippet feedback()}{#if warnings.length}<div class="warnings" role="status">{#each warnings as warning}<p>{warning}</p>{/each}</div>{/if}{#if error}<p class="error" role="alert">{error}</p>{/if}{/snippet}
<Modal bind:open={createOpen} title="创建模板" wide><form onsubmit={e=>{e.preventDefault();save();}}><fieldset disabled={!!busy} class="fields"><label class="field">模板名称<input bind:value={form.name} required placeholder={`my-template.${extension}`}/></label><div class="field space-top"><span>模板类型</span><div class="segments fill" role="tablist" aria-label="新建模板类型">{#each types as type}<button type="button" role="tab" aria-selected={form.type===type} class:active={form.type===type} onclick={()=>chooseType(type)}>{type} ({type==='Clash'?'.yaml':type==='Surge'?'.conf':'.lcf'})</button>{/each}</div></div><div class="segments methods" role="tablist" aria-label="模板来源">{#each methods.filter(item=>form.type==='Clash'||item.id!=='v2') as item}<button type="button" role="tab" aria-selected={method===item.id} class:active={method===item.id} onclick={()=>chooseMethod(item.id)}><Icon name={item.icon}/>{item.name}</button>{/each}</div>
{#if method==='upload'}<label class="field">选择模板文件<input type="file" accept={form.type==='Clash'?'.yaml,.yml,.json':'.conf,.lcf,.ini,.txt'} onchange={readFile}/></label>{:else if method==='url'}<label class="field">模板 URL<input type="url" bind:value={sourceURL} oninput={()=>prepared=false} placeholder="https://example.com/template.yaml" required/></label>{:else if method==='subscription'}<label class="field">订阅<AppSelect bind:value={subscriptionId} onchange={()=>prepared=false} options={demo.data.subscriptions.map(row=>({value:row.id,label:row.name}))} aria-label="生成模板的订阅" placeholder="选择订阅"/></label>{:else if method==='blank'}<div class="blank-choice"><Icon name="file" size={25}/><span>{form.type} · {form.name||`template.${extension}`}</span></div>{/if}
{#if method==='paste'||method==='v2'||prepared||fileReady}<label class="field space-top">{method==='v2'&&!prepared?'V2 模板内容':'模板内容'}<textarea class="template-editor" aria-label="新建模板内容" spellcheck="false" bind:value={form.content}></textarea></label>{/if}</fieldset>{@render feedback()}<div class="modal-actions"><button class="button" type="button" disabled={!!busy} onclick={()=>createOpen=false}>取消</button><button class="button" type="button" disabled={!!busy} onclick={prepare}><Icon name="check"/>{busy==='prepare'?'检查中…':'检查内容'}</button><button class="button primary" disabled={!!busy}>{busy==='save'?'保存中…':prepared&&warnings.length?'确认创建':'创建'}</button></div></form></Modal>

<Modal bind:open={editOpen} title="编辑模板" wide><form onsubmit={e=>{e.preventDefault();save();}}><fieldset disabled={!!busy} class="fields"><div class="editor-heading"><label class="field">模板名称<input bind:value={form.name} required/></label><span class="tag">{form.type}</span></div><label class="field space-top">模板内容<textarea class="template-editor tall" aria-label="模板内容" spellcheck="false" bind:value={form.content}></textarea></label></fieldset>{@render feedback()}<div class="modal-actions"><button class="button" type="button" disabled={!!busy} onclick={()=>editOpen=false}>取消</button><button class="button" type="button" disabled={!!busy} onclick={previewOutput}><Icon name="eye"/>预览输出</button><button class="button primary" disabled={!!busy}>保存</button></div>{#if history.length}<details class="history"><summary>历史版本 · {history.length}</summary>{#each history as version}<div><span>{new Date(version.createdAt).toLocaleString('zh-CN')}</span><button type="button" class="button small" disabled={!!busy} onclick={()=>restore(version)}><Icon name="refresh"/>恢复</button></div>{/each}</details>{/if}</form></Modal>

<Modal bind:open={previewOpen} title={readOnly?form.name:'订阅输出预览'} wide><textarea class="template-editor tall" aria-label="模板预览" readonly value={preview}></textarea>{@render feedback()}<div class="modal-actions"><button class="button" onclick={()=>previewOpen=false}>关闭</button><button class="button" onclick={()=>download(form.name||`template.${extension}`,preview)}><Icon name="download"/>下载</button></div></Modal>

<Modal bind:open={visibilityOpen} title="用户可见性"><div class="visibility-list">{#each demo.data.policies??[] as row}<label><span>{row.name}<small>{kind(row)}</small></span><input type="checkbox" bind:checked={visibility[row.id]} aria-label={`${row.name} 用户可选`} disabled={!!busy}/></label>{:else}<div class="empty">暂无模板</div>{/each}</div>{@render feedback()}<div class="modal-actions"><button class="button" disabled={!!busy} onclick={()=>visibilityOpen=false}>取消</button><button class="button primary" disabled={!!busy} onclick={saveVisibility}>保存</button></div></Modal>
<Modal bind:open={deleteOpen} title="删除模板"><p>确认删除「{selected.name}」？</p>{@render feedback()}<div class="modal-actions"><button class="button" disabled={!!busy} onclick={()=>deleteOpen=false}>取消</button><button class="button danger" disabled={!!busy} onclick={remove}>删除</button></div></Modal>

<style>
 .template-list{background:var(--card)}
 h1{display:flex;align-items:center;gap:.65rem;font-size:1.45rem;letter-spacing:0}.template-toolbar{display:flex;justify-content:space-between;align-items:center;gap:1rem;margin:1rem 0}.segments{display:flex;align-items:stretch;border:1px solid var(--line);padding:3px;background:var(--background);border-radius:6px;gap:3px;min-width:0}.segments button{display:flex;align-items:center;justify-content:center;gap:.4rem;border:0;border-radius:3px;background:none;color:var(--muted);font-size:.8rem;padding:.5rem .85rem;white-space:nowrap}.segments button.active{background:var(--nested);color:var(--foreground)}.fill button{flex:1;min-width:0}.methods{margin:1rem 0;flex-wrap:wrap}.methods button{flex:1}.template-list{border-top:1px solid var(--line)}.list-heading,.template-row{display:flex;align-items:center;justify-content:space-between;gap:1rem;padding:1rem .7rem;border-bottom:1px solid var(--line)}.list-heading{font-size:.75rem;color:var(--muted)}.template-name{display:flex;align-items:center;gap:.65rem;min-width:0;flex-wrap:wrap}.name-link{padding:0;background:none;border:0;color:var(--foreground);font-size:.86rem;overflow-wrap:anywhere;text-align:left;max-width:100%}.name-link:hover{color:var(--primary)}.default-label{color:var(--primary);background:color-mix(in srgb,var(--primary) 12%,transparent);padding:.2rem .45rem;border-radius:3px;font-size:.7rem}.visibility-label{display:flex;align-items:center;gap:.25rem;font-size:.7rem;color:var(--muted)}.row-actions{flex-shrink:0}.chosen{color:var(--primary)}.danger-action{color:var(--danger)}.fields{border:0;padding:0;min-width:0}.fields:disabled{opacity:.65}.template-editor{display:block;width:100%;height:240px;resize:vertical;font:.78rem/1.7 ui-monospace,Consolas,monospace;white-space:pre;overflow:auto;background:var(--background);border:1px solid var(--line);border-radius:6px;padding:1rem;color:var(--foreground)}.template-editor.tall{height:340px;max-height:55dvh}.editor-heading{display:flex;align-items:center;gap:1rem}.editor-heading .field{flex:1;min-width:0}.blank-choice{display:flex;align-items:center;gap:.75rem;padding:1.5rem 0;color:var(--muted);font-size:.85rem}.warnings{padding:.7rem;border-left:2px solid var(--warning);font-size:.78rem;color:var(--muted);overflow-wrap:anywhere;margin-top:.75rem}.history{border-top:1px solid var(--line);margin-top:1rem;padding-top:.8rem;font-size:.8rem}.history>div{display:flex;justify-content:space-between;gap:1rem;align-items:center;padding:.5rem 0}.visibility-list{max-height:50dvh;overflow:auto}.visibility-list label{display:flex;align-items:center;justify-content:space-between;gap:1rem;padding:.85rem 0;border-bottom:1px solid var(--line);font-size:.85rem}.visibility-list label>span{overflow-wrap:anywhere;min-width:0}.visibility-list small{display:block;color:var(--muted);margin-top:.3rem}.visibility-list input{flex-shrink:0}.empty{min-height:200px}.search-input{max-width:16rem}
 @media(max-width:767px){h1{font-size:1.2rem}.page-head{flex-direction:column;align-items:flex-start}.page-head .actions{flex-wrap:wrap}.template-toolbar{flex-direction:column;align-items:stretch}.search-input{max-width:none}.segments button{padding:.5rem .6rem}.template-row{align-items:flex-start;flex-direction:column;gap:.75rem}.template-row .row-actions{align-self:flex-end}.list-heading>span:last-child{display:none}.fill button{font-size:.72rem;padding:.5rem .25rem}.methods{display:grid;grid-template-columns:repeat(3,minmax(0,1fr))}.methods button{font-size:.75rem;padding:.5rem .3rem}.template-editor{height:240px}.modal-actions{flex-wrap:wrap}}
</style>
