<script lang="ts">
 import {onMount} from 'svelte';import Probe from '../lib/pages/Probe.svelte';import CustomAppearance from '../lib/components/CustomAppearance.svelte';import {startCallbackLogin,consumeCallback,secureOrigin} from '../lib/callback-login';import logo from '../../static/aswired-logo.gif?url';
 let master=$state(''),username=$state(''),error=$state(''),busy=$state(true);const KEY='aswired-probe-session';
 async function request(path:string,body?:any){const token=sessionStorage.getItem(KEY);const response=await fetch(path,{method:body?'POST':'GET',headers:{...(body?{'Content-Type':'application/json'}:{}),...(token?{'MM-Authorization':token}:{})},...(body?{body:JSON.stringify(body)}:{}),cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error?.message??'请求失败');return data;}
 onMount(()=>{(async()=>{try{const cfg=await request('/probe-config.json');master=secureOrigin(cfg.masterOrigin).origin;if(location.pathname==='/auth/callback'){const payload=consumeCallback(location.search);history.replaceState({},'',location.pathname);const result=await request('/api/auth/callback/exchange',payload);sessionStorage.setItem(KEY,result.token);username=result.user.username;history.replaceState({},'','/');}else if(sessionStorage.getItem(KEY)){try{const result=await request('/api/me');username=result.user.username;}catch{sessionStorage.removeItem(KEY);}}}catch(cause){error=cause instanceof Error?cause.message:'探针配置读取失败';history.replaceState({},'',location.pathname);}finally{busy=false;}})();});
 async function login(){busy=true;error='';try{await startCallbackLogin(master);}catch(cause){error=cause instanceof Error?cause.message:'登录失败';busy=false;}}
 async function logout(){try{await request('/api/logout',{});}catch(cause){error=cause instanceof Error?cause.message:'主控未确认退出';}finally{sessionStorage.removeItem(KEY);username='';}}
</script>
<CustomAppearance/><div class="standalone"><header class="section-head"><a class="brand" href="/"><img class="brand-mark" src={logo} alt=""/><strong>ASWired</strong></a><div class="actions">{#if username}<span class="tag">{username}</span><a class="button" href={master+'/portal'}>我的套餐</a><button class="button" onclick={logout}>退出</button>{:else}<button class="button" disabled={busy||!master} onclick={login}>登录工作区</button>{/if}</div></header>{#if error}<p class="status-banner" role="alert">{error}</p>{/if}<Probe/><footer><span>ASWired · 独立探针</span><a href="/?nocss=1">恢复默认外观</a></footer></div>
<style>.standalone{max-width:1440px;margin:auto;padding:1.5rem}.standalone header{margin-bottom:2rem}.standalone .brand{padding:0}.standalone footer{display:flex;justify-content:space-between;padding:2rem 0;color:var(--muted);font-size:.8rem}@media(max-width:600px){.standalone{padding:1rem}.standalone header{align-items:flex-start;gap:1rem}.standalone header .actions{justify-content:flex-end;flex-wrap:wrap}.standalone .button{font-size:.8rem}}</style>
