import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
const source=fs.readFileSync(new URL('../src/lib/callback-login.ts',import.meta.url),'utf8');
const js=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText;
const callback=await import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));
function fixture(t){const values=new Map();const originalStorage=globalThis.sessionStorage,originalLocation=globalThis.location;let navigation='';globalThis.sessionStorage={getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)};globalThis.location={origin:'https://probe.example.test',pathname:'/auth/callback',assign:v=>navigation=v};t.after(()=>{globalThis.sessionStorage=originalStorage;globalThis.location=originalLocation});return {values,navigation:()=>navigation};}
test('PKCE start stores verifier locally and navigates using only challenge',async t=>{const f=fixture(t);await callback.startCallbackLogin('https://panel.example.test');const next=new URL(f.navigation()),stored=JSON.parse(f.values.get('aswired-login-callback'));assert.equal(next.origin,'https://panel.example.test');assert.equal(next.pathname,'/auth/authorize');assert.equal(next.searchParams.get('code_challenge_method'),'S256');assert.equal(next.searchParams.has('code_verifier'),false);assert.equal(stored.verifier.length,43);assert.equal(next.searchParams.get('state'),stored.state);const result=callback.consumeCallback('?code=one-time-code&state='+encodeURIComponent(stored.state));assert.equal(result.code_verifier,stored.verifier);assert.equal(f.values.size,0);assert.throws(()=>callback.consumeCallback('?code=one-time-code&state='+stored.state),/没有找到/);});
test('callback rejects mismatched state and expiry without consuming a JWT',t=>{const f=fixture(t);const request={state:'original-state',verifier:'x'.repeat(43),redirectURI:'https://probe.example.test/auth/callback',createdAt:Date.now()};f.values.set('aswired-login-callback',JSON.stringify(request));assert.throws(()=>callback.consumeCallback('?code=one-time-code&state=attacker-state'),/不匹配/);f.values.set('aswired-login-callback',JSON.stringify({...request,createdAt:Date.now()-11*60*1000}));assert.throws(()=>callback.consumeCallback('?code=one-time-code&state=original-state'),/过期/);f.values.set('aswired-login-callback',JSON.stringify({...request,createdAt:null}));assert.throws(()=>callback.consumeCallback('?code=one-time-code&state=original-state'),/过期/);});
test('callback address must remain on the current origin and path',async t=>{fixture(t);await assert.rejects(()=>callback.startCallbackLogin('https://panel.example.test','https://other.example.test/auth/callback'),/当前站点/);assert.throws(()=>callback.secureOrigin('http://panel.example.test'),/HTTPS/);assert.throws(()=>callback.secureOrigin('https://user:secret@panel.example.test'),/HTTPS/);});
