<script lang="ts">
 import AnimatedLogo from './AnimatedLogo.svelte';
 import TurnstileWidget from './TurnstileWidget.svelte';import QRLogin from './QRLogin.svelte';import {onMount} from 'svelte';import { demo, authenticate, initialize, errorMessage,api,APIError,acceptSession } from '../store.svelte';import {requestOptions,credentialJSON,passkeyError} from '../passkey';
 let registering=$state(false),inviteCode=$state('');
 let authOptions=$state<any>(null),turnstileToken=$state(''),widgetVersion=$state(0),miniappData=$state(''),miniappStarted=$state(false),username=$state(''),password=$state(''),confirmation=$state(''),setupToken=$state(''),code=$state(''),totpRequired=$state(false),busy=$state(false),error=$state('');
 onMount(()=>{api('/api/public/auth-options').then(result=>authOptions=result).catch(cause=>error=errorMessage(cause));miniappData=new URLSearchParams(location.hash.slice(1)).get('tgWebAppData')??new URLSearchParams(location.search).get('tgWebAppData')??'';});
 $effect(()=>{if(miniappData&&!demo.connecting&&!miniappStarted){miniappStarted=true;busy=true;api('/api/telegram/miniapp',{method:'POST',body:JSON.stringify({initData:miniappData})}).then(acceptSession).then(()=>{const url=new URL(location.href);url.searchParams.delete('tgWebAppData');url.hash='';history.replaceState({},'',url.pathname+url.search);}).catch(cause=>error=errorMessage(cause)).finally(()=>busy=false);}});

 async function submit(){
  if(busy)return;error='';
  if((!demo.initialized||registering)&&password!==confirmation){error='两次输入的密码不一致';return;}
  busy=true;try{if(registering&&demo.initialized){await acceptSession(await api('/api/register',{method:'POST',body:JSON.stringify({username:username.trim(),password,inviteCode:inviteCode.trim(),turnstileToken})}));inviteCode='';}else await authenticate(username.trim(),password,!demo.initialized,demo.initialized?{code,turnstileToken}:{setupToken});password='';confirmation='';code='';setupToken='';}catch(cause){error=errorMessage(cause);if(cause instanceof APIError&&cause.code==='totp_required')totpRequired=true;}finally{busy=false;if(authOptions?.turnstileEnabled){turnstileToken='';widgetVersion++;}}
 }
 async function passkeyLogin(){if(busy)return;if(!username.trim()){error='请先填写用户名';return;}if(!window.isSecureContext||!window.PublicKeyCredential){error='通行密钥需要 HTTPS 或 localhost，以及支持的浏览器';return;}busy=true;error='';try{const begin=await api('/api/passkey/login/begin',{method:'POST',body:JSON.stringify({username:username.trim()})});const credential=await navigator.credentials.get(requestOptions(begin.options)) as PublicKeyCredential|null;if(!credential)throw new Error('未取得通行密钥');const result=await api('/api/passkey/login/finish',{method:'POST',body:JSON.stringify({challengeId:begin.challengeId,response:credentialJSON(credential)})});await acceptSession(result);password='';code='';}catch(cause){error=passkeyError(cause);}finally{busy=false;}}
</script>
<div class="auth-shell"><section class="card auth-card"><a class="auth-brand" href="/" aria-label="ASWired 首页"><AnimatedLogo/></a>
 {#if demo.connecting}<h1>正在连接 ASWired</h1><p class="muted">正在读取主控状态…</p>
 {:else}<h1>{demo.initialized?(registering?'邀请码注册':'登录到 ASWired'):'创建你的 ASWired'}</h1>{#if !demo.initialized||registering}<p class="muted">{registering?'使用管理员提供的注册邀请码创建普通账户。':'设置首个管理员账户，开始连接服务器。'}</p>{/if}
 {#if demo.connectionError}<div class="status-banner space-top" role="alert">{demo.connectionError}</div><button class="button space-top" onclick={initialize}>重新连接</button>{/if}
 <form class="stack space-top" onsubmit={e=>{e.preventDefault();submit();}}><label class="field">用户名<input required autocomplete="username" bind:value={username} disabled={busy}/></label><label class="field">密码<input required type="password" minlength={demo.initialized&&!registering?undefined:12} maxlength="72" autocomplete={demo.initialized&&!registering?'current-password':'new-password'} bind:value={password} disabled={busy}/></label>{#if demo.initialized&&!registering&&totpRequired}<label class="field">身份验证器验证码或恢复码<input required autocomplete="one-time-code" bind:value={code} disabled={busy}/></label>{/if}{#if !demo.initialized}<label class="field">初始化令牌<input required type="password" autocomplete="off" bind:value={setupToken} disabled={busy}/></label><p class="hint">从主控数据目录的 setup-token 文件获取。</p><label class="field">确认密码<input required type="password" autocomplete="new-password" bind:value={confirmation} disabled={busy}/></label><p class="hint">密码至少 12 位。账户保存在你的主控中。</p>{/if}{#if demo.initialized&&registering}<label class="field">确认密码<input required type="password" autocomplete="new-password" bind:value={confirmation} disabled={busy}/></label><label class="field">注册邀请码<input required autocomplete="off" spellcheck="false" bind:value={inviteCode} disabled={busy} placeholder="asw_inv_…"/></label><p class="hint">邀请码仅可使用一次。密码须为 12 至 72 字节。</p>{/if}{#if demo.initialized&&authOptions?.turnstileEnabled}{#key widgetVersion}<TurnstileWidget siteKey={authOptions.turnstileSiteKey} bind:token={turnstileToken}/>{/key}{/if}{#if error}<p class="error" role="alert">{error}</p>{/if}<button class="button primary" disabled={busy||(demo.initialized&&(!authOptions||(authOptions.turnstileEnabled&&!turnstileToken)))}>{busy?'请稍候…':demo.initialized?(registering?'注册并登录':'登录'):'创建工作区'}</button>{#if demo.initialized&&!registering}<button type="button" class="button" disabled={busy} onclick={passkeyLogin}>使用通行密钥登录</button><QRLogin/>{/if}</form>{#if demo.initialized}<button type="button" class="button space-top auth-switch" disabled={busy} onclick={()=>{registering=!registering;error='';password='';confirmation='';code='';totpRequired=false;turnstileToken='';widgetVersion++;}}>{registering?'已有账户，返回登录':'使用邀请码注册'}</button>{/if}{/if}
 </section></div>
<style>.auth-switch{width:100%;justify-content:center}.auth-shell{min-height:100dvh;display:grid;place-items:center;padding:2rem}.auth-card{width:min(100%,27rem);padding:2rem}.auth-brand{display:block;width:100px;aspect-ratio:10/9;margin:0 auto 1.5rem}.auth-card h1{font-size:1.7rem;margin-bottom:.8rem}.auth-card form>.button{justify-content:center;min-height:2.8rem}@media(max-width:420px){.auth-brand{width:88px}}</style>
