<script lang="ts">
 import {goto} from '$app/navigation';import {page} from '$app/state';import {api,acceptSession,demo,errorMessage} from '../store.svelte';import {consumeCallback,secureOrigin} from '../callback-login';
 let started=$state(false),busy=$state(false),error=$state(''),destination=$state('');const authorize=$derived(page.url.pathname==='/auth/authorize');
 $effect(()=>{if(authorize){try{destination=secureOrigin(page.url.searchParams.get('redirect_uri')??'').origin;}catch{error='授权回接地址无效';}}else if(!demo.connecting&&!started){started=true;exchange();}});
 async function exchange(){busy=true;try{const body=consumeCallback(location.search);history.replaceState({},'',location.pathname);const result=await api('/api/auth/callback/exchange',{method:'POST',body:JSON.stringify(body)});await acceptSession(result);await goto('/',{replaceState:true});}catch(cause){history.replaceState({},'',location.pathname);error=errorMessage(cause);}finally{busy=false;}}
 async function approve(){if(busy)return;busy=true;error='';try{const query=page.url.searchParams;const body={redirect_uri:query.get('redirect_uri'),code_challenge:query.get('code_challenge'),code_challenge_method:query.get('code_challenge_method'),state:query.get('state')};if(body.code_challenge_method!=='S256'||!body.state)throw new Error('授权请求无效');const result=await api('/api/auth/callback/authorize',{method:'POST',body:JSON.stringify(body)});const target=secureOrigin(result.redirect_url);if(target.origin!==destination||target.searchParams.get('state')!==body.state)throw new Error('主控返回的回接地址不匹配');location.assign(target.href);}catch(cause){error=errorMessage(cause);busy=false;}}
</script>
<div class="callback-shell"><section class="card padded"><a class="brand" href="/"><img class="brand-mark" src="/aswired-logo.gif" alt=""/><strong>ASWired</strong></a><h1>{authorize?'登录探针':'正在完成登录'}</h1>{#if authorize}<p class="muted space-top">以 {demo.user?.username} 登录以下站点：</p><p class="destination">{destination}</p><p class="hint">此站点将获得你当前账户的登录身份与权限。</p><div class="actions space-top"><a href="/" class="button">取消</a><button class="button primary" disabled={busy||!destination} onclick={approve}>{busy?'正在授权…':'继续登录'}</button></div>{:else if !error}<p class="muted space-top">正在验证本次登录请求…</p>{/if}{#if error}<p class="error space-top" role="alert">{error}</p><a class="button space-top" href="/">返回工作区</a>{/if}</section></div>
<style>.callback-shell{min-height:100dvh;display:grid;place-items:center;padding:2rem}.callback-shell section{width:min(100%,32rem)}.callback-shell .brand{padding:0;margin-bottom:2rem}.destination{overflow-wrap:anywhere;font-weight:600;margin-top:1rem}</style>
