<script lang="ts">
 import ExpandableValue from './ExpandableValue.svelte';
 import {onMount} from 'svelte';import AppSelect from './Select.svelte';import Badge from './Badge.svelte';import {demo,api,runAction,errorMessage,copy,download} from '../store.svelte';
 let busy=$state(false),error=$state(''),masterPublicKey=$state(''),name=$state(''),serverId=$state(''),consumerPublicKey=$state(''),namespace=$state(''),inbounds=$state('{}'),actions=$state(['status.get','inbound.users.get','stats.get']),expires=$state(''),ownerUrl=$state(''),shareId=$state(''),token=$state(''),peerId=$state(''),operation=$state('status.get'),params=$state('{}'),requestId=$state(''),result=$state<any>(null);
 const shares=$derived((demo.data.shares??[]).filter(row=>row.scope==='agent_management'));
 const taskIds=$derived([result?.install_task_id,result?.agent_update_task_id,result?.task?.id].filter(Boolean));
 onMount(()=>{api('/api/federation/identity').then(row=>masterPublicKey=row.masterPublicKey).catch(cause=>error=errorMessage(cause));});
 function object(value:string){const parsed=JSON.parse(value);if(!parsed||Array.isArray(parsed)||typeof parsed!=='object')throw new Error('请填写 JSON 对象');return parsed;}
 async function execute(action:string,id?:string,parameters:Record<string,any>={}){if(busy)return;busy=true;error='';result=null;try{result=await runAction(action,id,undefined,parameters);if(result.request_id)requestId=result.request_id;return result;}catch(cause){error=errorMessage(cause);}finally{busy=false;}}
 async function publish(){try{await execute('federation.agent.publish',serverId,{name,consumerPublicKey,namespace,inbounds:object(inbounds),actions,expiresAt:expires?Math.floor(new Date(expires).getTime()/1000):0});}catch(cause){error=errorMessage(cause);}}
 async function connect(){const out=await execute('federation.agent.connect',undefined,{name,ownerUrl,shareId,token});if(out){token='';peerId=out.id??'';}}
 async function command(){try{await execute('federation.agent.execute',peerId,{action:operation,params:object(params)});}catch(cause){error=errorMessage(cause);}}
</script>
<p class="muted">授予另一台 ASWired 主控管理指定入站内的独立命名空间。拥有方保留服务器与核心控制权，授权动作限于状态、所属用户与统计。</p>
{#if error}<p class="error space-top" role="alert">{error}</p>{/if}
<h3 class="space-top">本机消费者身份</h3><p class="hint">接收管理分享时，将以下公钥提供给拥有方。</p><div class="token-box"><code>{masterPublicKey||'正在读取公钥…'}</code><button class="button small" disabled={!masterPublicKey} onclick={()=>copy(masterPublicKey)}>复制公钥</button></div>
<h3 class="space-top">发布管理授权</h3><div class="form-grid space-top"><label class="field">名称<input bind:value={name}/></label><label class="field">服务器<AppSelect bind:value={serverId} options={[{value:'',label:'选择服务器'},...demo.data.servers.map(row=>({value:row.id,label:row.name}))]} aria-label="联邦授权服务器"/></label><label class="field full">消费者主控公钥<input bind:value={consumerPublicKey}/></label><label class="field">命名空间<input bind:value={namespace} placeholder="仅字母、数字、连字符或下划线"/></label><label class="field">到期时间（留空长期）<input type="datetime-local" bind:value={expires}/></label><label class="field full">入站别名白名单 JSON<textarea class="code-editor short" bind:value={inbounds} spellcheck="false" placeholder={'{"reality":"in-hk-reality"}'}></textarea></label><div class="field full"><span>允许动作</span><div class="stack">{#each ['status.get','inbound.users.get','inbound.users.sync','stats.get'] as action}<label class="tag"><input type="checkbox" value={action} bind:group={actions}/>{action}</label>{/each}</div></div></div><button class="button primary space-top" disabled={busy||!serverId||!consumerPublicKey||!namespace||!actions.length} onclick={publish}>{busy?'等待实际执行…':'发布并下发授权'}</button><p class="hint">发布先读取 Agent 身份，再下发签名授权。Agent 完成安装前，分享无法接入；创建返回的令牌只显示一次。</p>
<h3 class="space-top">接收管理分享</h3><div class="form-grid space-top"><label class="field">拥有方 HTTPS 主控地址<input type="url" bind:value={ownerUrl}/></label><label class="field">分享标识<input bind:value={shareId}/></label><label class="field full">一次性展示的分享令牌<input type="password" autocomplete="off" bind:value={token}/></label></div><button class="button space-top" disabled={busy||!ownerUrl||!shareId||!token} onclick={connect}>验证并接入</button>
<div class="stack space-top">{#each shares as row}<div class="car-summary"><div><strong>{row.name}</strong><small>{row.direction==='owner'?'我发布的管理授权':'接收的管理授权'} · {row.namespace}</small></div><Badge value={row.status}/>{#if row.direction==='owner'}<button class="button small" disabled={busy} onclick={()=>execute('federation.agent.revoke',row.id)}>撤销授权</button>{:else}<button class="button small" disabled={busy} onclick={()=>peerId=row.id}>选择操作</button>{/if}</div>{/each}</div>
<h3 class="space-top">在授权范围执行</h3><div class="form-grid space-top"><label class="field">接收的管理授权<AppSelect bind:value={peerId} options={[{value:'',label:'选择管理授权'},...shares.filter(row=>row.direction==='consumer').map(row=>({value:row.id,label:row.name}))]} aria-label="接收的管理授权"/></label><label class="field">动作<AppSelect bind:value={operation} options={['status.get','inbound.users.get','inbound.users.sync','stats.get']} aria-label="联邦范围动作"/></label><label class="field full">参数 JSON<textarea class="code-editor short" bind:value={params} spellcheck="false"></textarea></label></div><p class="hint">用户读取使用 inbound 别名；同步使用 inbound 和 users 数组，只修改所授权命名空间的用户。状态和统计使用空对象。未授权动作由主控与 Agent 拒绝。</p><button class="button primary space-top" disabled={busy||!peerId} onclick={command}>提交受限命令</button>
<div class="actions space-top"><input aria-label="联邦请求标识" bind:value={requestId} placeholder="请求标识"/><button class="button" disabled={busy||!requestId} onclick={()=>execute('federation.agent.result',requestId)}>读取加密任务结果</button></div>
{#if result}<section class="space-top"><h3>本次响应</h3>{#if result.token}<p class="hint">此响应包含分享凭据，请妥善保存。</p><div class="actions"><button class="button" onclick={()=>copy(JSON.stringify(result,null,2))}>复制配置</button><button class="button" onclick={()=>download('aswired-agent-share.json',JSON.stringify(result,null,2),'application/json')}>下载配置</button></div>{/if}{#each taskIds as id}<a class="button small space-top" href={`/tasks?detail=${encodeURIComponent(id)}`}>查看 Agent 授权任务 {id}</a>{/each}{#key result}<ExpandableValue value={result} label="响应详情" force />{/key}<button class="button" onclick={()=>result=null}>关闭响应</button></section>{/if}
