<script lang="ts">
 import {onMount} from 'svelte';import QRCode from 'qrcode';import Icon from './Icon.svelte';import Modal from './Modal.svelte';import {api,runAction,demo,toast,errorMessage,copy,download,acceptSession} from '../store.svelte';import {creationOptions,credentialJSON,passkeyError} from '../passkey';
 let telegramCommand=$state(''),security=$state<any>(null),busy=$state(false),error=$state(''),password=$state(''),code=$state(''),keyName=$state('我的通行密钥'),newPassword=$state(''),confirmPassword=$state(''),pending=$state<{secret:string;uri:string}|null>(null),qr=$state(''),recovery=$state<string[]>([]),tokenName=$state(''),tokenScope=$state('read'),newToken=$state(''),tokenOpen=$state(false);
 $effect(()=>{if(!tokenOpen)newToken='';});
 async function load(){security=await api('/api/account/security');}
 onMount(()=>{load().catch(cause=>error=errorMessage(cause));});
 async function execute(task:()=>Promise<void>){if(busy)return;busy=true;error='';try{await task();}catch(cause){error=passkeyError(cause);}finally{busy=false;code='';}}
 const reauth=()=>({password,code});
 async function beginTOTP(){await execute(async()=>{pending=await api('/api/account/totp/begin',{method:'POST',body:JSON.stringify(reauth())});qr=await QRCode.toDataURL(pending!.uri,{width:180,margin:2});password='';});}
 async function confirmTOTP(){await execute(async()=>{const result=await api('/api/account/totp/confirm',{method:'POST',body:JSON.stringify({code})});recovery=result.recoveryCodes;pending=null;qr='';await load();toast('两步验证已启用，请保存恢复码');});}
 async function disableTOTP(){await execute(async()=>{await api('/api/account/totp/disable',{method:'POST',body:JSON.stringify(reauth())});password='';recovery=[];await load();toast('两步验证已关闭');});}
 async function rotateRecovery(){await execute(async()=>{const result=await api('/api/account/totp/recovery',{method:'POST',body:JSON.stringify(reauth())});recovery=result.recoveryCodes;password='';await load();toast('恢复码已重新生成，旧恢复码已失效');});}
 async function addPasskey(){await execute(async()=>{if(!window.isSecureContext||!window.PublicKeyCredential)throw new Error('通行密钥需要 HTTPS 或 localhost，以及支持的浏览器');const begin=await api('/api/account/passkeys/begin',{method:'POST',body:JSON.stringify({...reauth(),name:keyName})});const credential=await navigator.credentials.create(creationOptions(begin.options)) as PublicKeyCredential|null;if(!credential)throw new Error('未取得通行密钥');await api('/api/account/passkeys/finish',{method:'POST',body:JSON.stringify({challengeId:begin.challengeId,response:credentialJSON(credential)})});password='';await load();toast('通行密钥已注册');});}
 async function deletePasskey(id:string){await execute(async()=>{await api(`/api/account/passkeys/${encodeURIComponent(id)}/delete`,{method:'POST',body:JSON.stringify(reauth())});password='';await load();toast('通行密钥已撤销');});}
 async function changePassword(){await execute(async()=>{if(newPassword!==confirmPassword)throw new Error('两次新密码不一致');if(new TextEncoder().encode(newPassword).length<12)throw new Error('新密码至少 12 字节');const result=await api('/api/account/password',{method:'POST',body:JSON.stringify({currentPassword:password,newPassword,code})});await acceptSession(result);password='';newPassword='';confirmPassword='';toast('密码已更新，旧登录已失效');});}
 async function createToken(){await execute(async()=>{if(!tokenName.trim())throw new Error('请填写令牌名称');const result=await runAction('token.create',undefined,undefined,{name:tokenName.trim(),scopes:tokenScope==='write'?['read','write']:['read']});if(!result.token)throw new Error('主控未返回新令牌');newToken=result.token;tokenOpen=true;tokenName='';});}
 async function telegram(unbind=false){await execute(async()=>{const result=await api('/api/account/telegram',{method:'POST',body:JSON.stringify({unbind})});telegramCommand=result.command??'';toast(unbind?'Telegram 已解绑':'绑定口令已生成，请私聊 Bot 发送');});}
 async function revokeToken(id:string){await execute(async()=>{await runAction('token.revoke',id,'tokens');toast('API Token 已撤销');});}
</script>
<div class="stack">
 {#if error}<p class="error" role="alert">{error}</p>{/if}
 <section><h3>身份确认</h3><p class="hint">修改安全设置时填写当前密码；已启用两步验证时，同时填写新的验证码或未使用的恢复码。</p><div class="form-grid"><label class="field">当前密码<input type="password" autocomplete="current-password" bind:value={password}/></label>{#if security?.totpEnabled||pending}<label class="field">验证码或恢复码<input autocomplete="one-time-code" bind:value={code}/></label>{/if}</div></section>
 <section class="space-top"><div class="section-head"><h3>两步验证</h3><span class="tag">{security?.totpEnabled?'已启用':'未启用'}</span></div>{#if pending}<div class="split space-top"><div><p>使用身份验证器扫描二维码，或手动输入密钥。</p><div class="token-box"><code>{pending.secret}</code><button class="button small" onclick={()=>copy(pending!.secret)}>复制</button></div><p class="hint">输入身份验证器当前显示的 6 位验证码后启用。</p><button class="button primary" disabled={busy||!code} onclick={confirmTOTP}>验证并启用</button></div><div class="qr-box">{#if qr}<img src={qr} alt="两步验证配置二维码" width="180" height="180"/>{/if}</div></div>{:else if security?.totpEnabled}<p class="hint">密码登录需要验证码；剩余 {security.recoveryRemaining} 个恢复码。</p><div class="actions"><button class="button" disabled={busy} onclick={rotateRecovery}>重新生成恢复码</button><button class="button danger" disabled={busy} onclick={disableTOTP}>关闭两步验证</button></div>{:else}<p class="hint">使用身份验证器生成动态验证码。配置验证通过后才会启用。</p><button class="button" disabled={busy} onclick={beginTOTP}>配置两步验证</button>{/if}
 {#if recovery.length}<div class="status-banner space-top">恢复码只在本次生成后展示。请安全保存，每个恢复码只能使用一次。</div><pre class="code-editor short">{recovery.join('\n')}</pre><div class="actions"><button class="button" onclick={()=>copy(recovery.join('\n'))}>复制恢复码</button><button class="button" onclick={()=>download('aswired-recovery-codes.txt',recovery.join('\n'))}>下载恢复码</button><button class="button" onclick={()=>recovery=[]}>已保存，隐藏</button></div>{/if}</section>
 <section class="space-top"><div class="section-head"><h3>通行密钥 Passkey</h3><span class="tag">{security?.rpId||'域名待配置'}</span></div><p class="hint">通过设备的指纹、面容或安全密钥验证，成功后使用同一套 JWT 工作区会话。</p><label class="field">密钥名称<input bind:value={keyName}/></label><button class="button space-top" disabled={busy||!security?.passkeyAvailable} onclick={addPasskey}><Icon name="plus"/>注册通行密钥</button><div class="stack space-top">{#each security?.passkeys??[] as key}<div class="car-summary"><div><strong>{key.name}</strong><small>{key.lastUsed?'最近使用：'+new Date(key.lastUsed).toLocaleString():'尚未使用'}</small></div><button class="button small danger" disabled={busy} onclick={()=>deletePasskey(key.id)}>撤销</button></div>{:else}<p class="muted">尚未注册通行密钥。</p>{/each}</div></section>
 <section class="space-top"><h3>扫码确认登录</h3><p class="hint">在另一台浏览器登录页选择扫码登录，用这台已登录设备扫描二维码，并输入原浏览器显示的六位确认码。只确认本人发起的登录。</p></section><section class="space-top"><h3>修改密码</h3><div class="form-grid"><label class="field">新密码<input type="password" autocomplete="new-password" bind:value={newPassword}/></label><label class="field">确认新密码<input type="password" autocomplete="new-password" bind:value={confirmPassword}/></label></div><button class="button space-top" disabled={busy||!newPassword} onclick={changePassword}>更新密码</button></section>
 <section class="space-top"><h3>Telegram 绑定</h3><p class="hint">生成一次性口令后，私聊此工作区的 Bot 发送绑定命令。不要将口令发送给他人。</p><div class="actions"><button class="button" disabled={busy} onclick={()=>telegram()}>生成绑定口令</button><button class="button" disabled={busy} onclick={()=>telegram(true)}>解除绑定</button></div>{#if telegramCommand}<div class="token-box space-top"><code>{telegramCommand}</code><button class="button small" onclick={()=>copy(telegramCommand)}>复制</button></div>{/if}</section><section class="space-top"><h3>API Token</h3><p class="hint">API Token 用于 API 与 MCP，权限不能超过当前账户。明文只展示一次。</p><div class="form-grid"><label class="field">令牌名称<input bind:value={tokenName} placeholder="例如：我的自动化"/></label><div class="field"><span>权限范围</span><div class="segmented"><button class:active={tokenScope==='read'} onclick={()=>tokenScope='read'}>只读</button><button class:active={tokenScope==='write'} onclick={()=>tokenScope='write'}>读取与修改</button></div></div></div><button class="button space-top" disabled={busy} onclick={createToken}>创建 API Token</button><div class="stack space-top">{#each demo.data.tokens??[] as token}<div class="car-summary"><div><strong>{token.name}</strong><small>{Array.isArray(token.scopes)?token.scopes.join(' / '):token.scopes??'账户权限'}</small></div><button class="button small danger" disabled={busy} onclick={()=>revokeToken(token.id)}>撤销</button></div>{:else}<p class="muted">尚无 API Token。</p>{/each}</div></section>
</div>
<Modal bind:open={tokenOpen} title="保存新 API Token" description="关闭后不能再次查看明文；遗失后请撤销并重新创建。"><div class="token-box"><code>{newToken}</code><button class="button small" onclick={()=>copy(newToken)}>复制</button></div><div class="modal-actions"><button class="button primary" onclick={()=>{tokenOpen=false;newToken='';}}>已保存</button></div></Modal>
