<script lang="ts">
 import {onMount} from 'svelte';import Modal from './Modal.svelte';import Badge from './Badge.svelte';import {api,errorMessage} from '../store.svelte';import type {Row} from '../data';
 let rows=$state<Row[]>([]),activeId=$state(''),maximumBytes=$state(32*1024*1024),file=$state<File|null>(null),name=$state(''),url=$state(''),sha256=$state(''),ip=$state(''),busy=$state(false),error=$state(''),message=$state(''),lookup=$state<any>(null),deleting=$state<Row|null>(null),deleteOpen=$state(false);
 const localeName=(value:any)=>value?.names?.['zh-CN']??value?.names?.en??value?.iso_code??'—';
 const facts=$derived(lookup?[['地址',lookup.ip],['匹配网段',lookup.network??'—'],['国家 / 地区',localeName(lookup.record?.country??lookup.record?.registered_country)],['城市',localeName(lookup.record?.city)],['地区',localeName(lookup.record?.subdivisions?.[0])],['时区',lookup.record?.location?.time_zone??'—'],['自治系统',lookup.record?.autonomous_system_number??'—'],['网络组织',lookup.record?.autonomous_system_organization??'—']]:[]);
 async function load(){const result=await api('/api/ip-databases');rows=result.rows??[];activeId=result.activeId??'';maximumBytes=result.maximumBytes??32*1024*1024;}
 async function perform(action:()=>Promise<any>,success:string){if(busy)return;busy=true;error='';message='';try{await action();await load();message=success;}catch(cause){error=errorMessage(cause);}finally{busy=false;}}
 async function upload(){if(!file)return;if(file.size<=0||file.size>maximumBytes){error=`请选择不超过 ${(maximumBytes/1048576).toFixed(0)} MiB 的 MMDB 文件`;return;}await perform(()=>api('/api/ip-databases?name='+encodeURIComponent(name||file!.name),{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:file}),'文件校验通过并已保存；点击启用后开始使用');}
 async function fetchDatabase(){if(!/^[a-f\d]{64}$/i.test(sha256.trim())){error='请填写来源公布的完整 SHA256 摘要';return;}await perform(()=>api('/api/ip-databases/fetch',{method:'POST',body:JSON.stringify({name,url,sha256:sha256.trim()})}),'下载内容及摘要已校验；点击启用后开始使用');}
 async function fetchDefaultDatabase(){await perform(()=>api('/api/ip-databases/fetch-default',{method:'POST'}),'Komari 默认 GeoLite2 Country 已下载并保存；没有当前 IP 库时会自动启用');}
 async function query(){if(busy)return;busy=true;error='';lookup=null;try{lookup=await api('/api/ip-lookup?ip='+encodeURIComponent(ip.trim()));}catch(cause){error=errorMessage(cause);}finally{busy=false;}}
 onMount(()=>{load().catch(cause=>error=errorMessage(cause));});
</script>
<p class="muted">上传 MMDB、获取 Komari 默认库，或从 HTTPS 来源按固定摘要下载，主控验证后保存。启用后，缺少手工国家/地区的节点会按地址自动识别。最多保留 3 个版本，可切换回已保存的版本。</p>{#if error}<p class="error space-top" role="alert">{error}</p>{/if}{#if message}<p class="hint space-top">{message}</p>{/if}
<section class="hint space-top"><strong>Komari 默认来源</strong><p>使用 GeoLite2 Country 数据库，来源为 Loyalsoldier geoip。没有当前 IP 库时，获取后会自动启用。</p><button class="button space-top" disabled={busy} onclick={fetchDefaultDatabase}>获取默认 IP 库</button></section>
<div class="form-grid space-top"><label class="field full">版本名称<input bind:value={name}/></label><label class="field full">本地 MMDB 文件（最多 {(maximumBytes/1048576).toFixed(0)} MiB）<input type="file" accept=".mmdb,application/octet-stream" onchange={event=>file=event.currentTarget.files?.[0]??null}/></label></div><button class="button primary space-top" disabled={busy||!file} onclick={upload}>上传并校验</button>
<h3 class="space-top">从数据源下载</h3><div class="form-grid space-top"><label class="field full">HTTPS 下载地址<input type="url" bind:value={url}/></label><label class="field full">来源公布的 SHA256<input bind:value={sha256} autocomplete="off" maxlength="64"/></label></div><button class="button space-top" disabled={busy||!url||!sha256} onclick={fetchDatabase}>下载并校验摘要</button>
<section class="space-top"><h3>已保存版本</h3><div class="stack">{#each rows as row}<div class="version"><div class="section-head"><strong>{row.name||row.databaseType}</strong><Badge value={row.id===activeId?'当前启用':'已保存'}/></div><p class="muted">{row.databaseType} · {Number(row.size/1048576).toFixed(2)} MiB · {new Date(row.buildTime).toLocaleString()}</p><small class="digest">SHA256：{row.sha256}</small><div class="actions space-top"><button class="button small" disabled={busy||row.id===activeId} onclick={()=>perform(()=>api('/api/ip-databases/'+encodeURIComponent(row.id)+'/activate',{method:'POST'}),'已切换当前 IP 数据库')}>启用此版本</button><button class="button small" disabled={busy||row.id===activeId} onclick={()=>{deleting=row;deleteOpen=true;}}>删除</button></div></div>{:else}<div class="empty">尚未保存 IP 数据库</div>{/each}</div></section>
<h3 class="space-top">查询当前数据库</h3><form class="actions space-top" onsubmit={event=>{event.preventDefault();query();}}><input aria-label="待查询 IP 地址" bind:value={ip} placeholder="IPv4 或 IPv6 地址" required/><button class="button primary" disabled={busy||!activeId}>查询</button></form>{#if lookup}{#if lookup.found}<dl class="detail-grid space-top">{#each facts as [label,value]}<div><dt>{label}</dt><dd>{String(value)}</dd></div>{/each}</dl>{:else}<p class="hint space-top">当前数据库没有该 IP 的匹配记录。</p>{/if}<p class="hint space-top">结果来自当前本地 MMDB 文件，仅显示地区、网段和网络组织字段。</p>{/if}
<Modal bind:open={deleteOpen} title="删除 IP 数据库版本" description={`删除「${deleting?.name??''}」后，该版本不能再直接回滚。`}><div class="modal-actions"><button class="button" onclick={()=>deleteOpen=false}>取消</button><button class="button danger" disabled={busy} onclick={()=>perform(async()=>{await api('/api/ip-databases/'+encodeURIComponent(deleting!.id),{method:'DELETE'});deleteOpen=false;deleting=null;},'旧版本已删除')}>确认删除</button></div></Modal>
<style>.version{padding:1rem 0;border-bottom:1px solid var(--line)}.digest{display:block;overflow-wrap:anywhere;margin-top:.5rem;color:var(--muted)}</style>
