<script lang="ts">
 import {formatNumber} from '../format';
 import {onMount} from 'svelte';import AppSelect from './Select.svelte';import Modal from './Modal.svelte';import Badge from './Badge.svelte';import Icon from './Icon.svelte';import {api,demo,runAction,errorMessage,toast,copy,download} from '../store.svelte';
 let {admin=false}=$props<{admin?:boolean}>();let data=$state<any>({plans:[],requests:[],renewals:[],history:[],codes:[]}),merged=$state<any>({enabled:false}),code=$state(''),error=$state(''),busy=$state(false),codesOpen=$state(false),created=$state<any[]>([]),planId=$state(''),count=$state(1),maxUses=$state(1),days=$state(30),expires=$state(''),label=$state(''),review=$state<any>(null),reviewKind=$state(''),reviewOpen=$state(false),reviewDays=$state(30),reviewNote=$state(''),confirmed=$state(false),planFilter=$state(''),dueBefore=$state(''),selectedRenewals=$state<string[]>([]);
 const renewals=$derived((data.renewals??[]).filter((r:any)=>r.status==='待核对'&&(!planFilter||r.plan===planFilter)&&(!dueBefore||(demo.data.subscriptions.find(s=>s.id===r.subscriptionId)?.expires??'9999')<=dueBefore+'T23:59:59Z')));
 async function load(){try{const [membership,combined]=await Promise.all([api('/api/membership'),api('/api/account/merged-subscription')]);data=membership;merged=combined;error='';}catch(cause){error=errorMessage(cause);}}
 onMount(()=>{code=new URLSearchParams(location.search).get('code')??'';load();});
 async function act(action:string,targetId?:string,params:Record<string,any>={}){if(busy)return;busy=true;error='';try{const result=await runAction(action,targetId,undefined,params);await load();toast(result.message??'操作已完成');return result;}catch(cause){error=errorMessage(cause);}finally{busy=false;}}
 async function redeem(){const result=await act('membership.redeem',undefined,{code:code.trim()});if(result){code='';if(location.pathname==='/join')history.replaceState({},'',location.pathname);}}
 async function generate(){const result=await act('membership.code.create',undefined,{planId,count,maxUses,days,expires,label});if(result){created=result.codes;codesOpen=true;}}
 function startReview(row:any,kind:string){review=row;reviewKind=kind;reviewDays=30;reviewNote='';confirmed=false;reviewOpen=true;}
 async function finishReview(approve:boolean){const batch=reviewKind==='subscription.renewal.batch';const result=await act(batch?reviewKind:reviewKind+(approve?'.confirm':'.reject'),review.id,{confirmed,days:reviewDays,note:reviewNote,recordVersion:review.recordVersion,...(batch?{entries:renewals.filter((r:any)=>selectedRenewals.includes(r.id)).map((r:any)=>({id:r.id,recordVersion:r.recordVersion}))}:{})});if(result){reviewOpen=false;selectedRenewals=[];const failed=result.results?.filter((r:any)=>!r.success)??[];if(failed.length)error=failed.map((r:any)=>r.id+': '+r.error).join('；');}}
 async function saveMerged(enabled:boolean,rotate=false){busy=true;error='';try{merged=await api('/api/account/merged-subscription',{method:'PUT',body:JSON.stringify({enabled,rotate})});toast(rotate?'合并订阅链接已重置':'合并订阅设置已保存');}catch(cause){error=errorMessage(cause);}finally{busy=false;}}
 $effect(()=>{if(!codesOpen)created=[];});
</script>
{#if error}<div class="status-banner space-top" role="alert">{error}</div>{/if}
{#if admin}
 <section class="card padded space-top"><div class="section-head"><div><h2>邀请码与兑换码</h2><p class="muted">为已有成员发放套餐。每个账户仅能兑换一次同一兑换码；已持有同套餐时保留兑换次数。</p></div><Icon name="gift"/></div><div class="form-grid space-top"><label class="field">套餐<AppSelect bind:value={planId} options={[{value:'',label:'选择套餐'},...demo.data.plans.filter(p=>p.status==='启用').map(p=>({value:p.id,label:p.name}))]} aria-label="兑换套餐"/></label><label class="field">批次备注<input bind:value={label}/></label><label class="field">生成数量<input type="number" min="1" max="100" bind:value={count}/></label><label class="field">每码使用次数<input type="number" min="1" max="10000" bind:value={maxUses}/></label><label class="field">套餐有效天数（0 为长期）<input type="number" min="0" max="3660" bind:value={days}/></label><label class="field">兑换截止日期（留空长期）<input type="date" bind:value={expires}/></label></div><button class="button primary space-top" disabled={busy||!planId} onclick={generate}>生成兑换码</button><div class="stack space-top">{#each data.codes??[] as entry}<div class="car-summary"><div><strong>{entry.label||entry.plan}</strong><small>{entry.used} / {entry.maxUses} 次 · 套餐 {entry.days?entry.days+' 天':'长期'} · 兑换截止 {entry.expires||'不限'}</small></div><Badge value={entry.revoked?'已吊销':entry.used>=entry.maxUses?'已用尽':'可兑换'}/><button class="button small" disabled={busy||entry.revoked} onclick={()=>act('membership.code.revoke',entry.id)}>吊销</button></div>{:else}<p class="empty">尚无兑换码</p>{/each}</div></section>
 <section class="card padded space-top"><h2>套餐申请核对</h2><p class="muted">核对线下约定后发放套餐。这里不自动收款或认定到账。</p>{#each data.requests?.filter((r:any)=>r.status==='待核对')??[] as entry}<div class="car-summary"><div><strong>{entry.member} · {entry.plan}</strong><small>{entry.note||'未填写备注'} · 申请时标价 ¥{formatNumber(entry.price??0)}</small></div><button class="button small" onclick={()=>startReview(entry,'membership.request')}>核对申请</button></div>{:else}<div class="empty">没有待核对的申请</div>{/each}</section>
 <section class="card padded space-top"><div class="section-head"><h2>续期核对</h2><AppSelect bind:value={planFilter} options={[{value:'',label:'全部套餐'},...demo.data.plans.map(p=>({value:p.name,label:p.name}))]} aria-label="按套餐筛选"/></div><div class="actions space-top"><label class="field">到期不晚于<input type="date" bind:value={dueBefore}/></label><button class="button" disabled={!selectedRenewals.length||busy} onclick={()=>startReview({member:`${selectedRenewals.length} 个套餐`,plan:'批量续期'},'subscription.renewal.batch')}>批量核对所选续期</button></div><p class="muted">有效套餐从原到期时间延长；已到期套餐从核对时刻延长。续期不会自动重置流量。</p>{#each renewals as entry}<div class="car-summary"><input type="checkbox" aria-label={`选择 ${entry.member} 的续期`} bind:group={selectedRenewals} value={entry.id}/><div><strong>{entry.member} · {entry.plan}</strong><small>{entry.declaredAt} · {entry.note||'已提交续期声明'}</small></div><button class="button small" onclick={()=>startReview(entry,'subscription.renewal')}>核对续期</button></div>{:else}<div class="empty">没有待核对的续期声明</div>{/each}</section>
{:else}
 <section class="card padded space-top"><div class="section-head"><div><h2>兑换套餐</h2><p class="muted">使用管理员提供的邀请码或兑换码，套餐会发放到当前账户。</p></div><Icon name="gift"/></div><form class="actions space-top" onsubmit={e=>{e.preventDefault();redeem();}}><input aria-label="邀请码或兑换码" class="grow" autocomplete="off" required bind:value={code} placeholder="输入邀请码或兑换码"/><button class="button primary" disabled={busy||!code.trim()}>兑换</button></form></section>
 <section class="card padded space-top"><h2>申请套餐</h2><p class="muted">管理员开放给工作区成员的套餐。申请提交后需管理员核对发放。</p>{#each data.plans as plan}<div class="car-summary"><div><strong>{plan.name} · ¥{formatNumber(plan.price??0)} / {plan.cycleDays||30} 天</strong><small>{plan.description} · {plan.limit?formatNumber(plan.limit):'不限'} GB</small>{#if plan.instructions}<p class="hint">{plan.instructions}</p>{/if}</div><button class="button small" disabled={busy||demo.data.subscriptions.some(s=>s.planId===plan.id)} onclick={()=>act('membership.request',plan.id)}>申请套餐</button></div>{:else}<div class="empty">暂无开放申请的套餐。可使用兑换码，或联系管理员分配。</div>{/each}{#each data.requests as request}<div class="car-summary"><span>{request.plan}</span><Badge value={request.status}/></div>{/each}</section>
 <section class="card padded space-top"><div class="section-head"><div><h2>全部套餐合并订阅</h2><p class="muted">在一个链接中获取有效套餐线路，各套餐保留独立凭据、流量与有效期。</p></div><button class="button" disabled={busy} onclick={()=>saveMerged(!merged.enabled)}>{merged.enabled?'关闭合并订阅':'开启合并订阅'}</button></div>{#if merged.enabled}<div class="actions space-top"><button class="button primary" onclick={()=>copy(merged.url+'&format=clash')}>复制 Clash 链接</button><button class="button" onclick={()=>copy(merged.url+'&format=singbox')}>复制 sing-box 链接</button><a class="button" href={merged.url+'&format=clash'} download="ASWired-merged.yaml">下载配置</a><button class="button" disabled={busy} onclick={()=>saveMerged(true,true)}>重置链接</button></div><p class="hint">相同节点按套餐分别列出，名称标注套餐。过期、停用或额度用尽的套餐不会输出；重置后旧链接立即失效。</p>{/if}</section>
 <section class="card padded space-top"><h2>续期进度</h2>{#each [...data.renewals.filter((r:any)=>r.status==='待核对'),...data.history].sort((a:any,b:any)=>String(b.reviewedAt??b.declaredAt).localeCompare(String(a.reviewedAt??a.declaredAt))) as entry}<div class="car-summary"><div><strong>{entry.plan}</strong><small>{entry.reviewedAt??entry.declaredAt} {entry.expires?'· 到期 '+entry.expires:''}</small></div><Badge value={entry.status}/></div>{:else}<div class="empty">尚无续期记录</div>{/each}</section>
{/if}
<Modal bind:open={codesOpen} title="保存兑换码" description="完整兑换码只显示这一次。邀请链接包含兑换码，请仅交给指定成员。" wide><div class="stack">{#each created as entry}<div class="car-summary"><code class="wrap-code">{entry.code}</code><button class="button small" onclick={()=>copy(entry.url)}>复制邀请链接</button></div>{/each}</div><div class="modal-actions"><button class="button" onclick={()=>download('ASWired-codes.txt',created.map(e=>e.code+'\t'+e.url).join('\n'))}>下载列表</button><button class="button primary" onclick={()=>codesOpen=false}>已保存</button></div></Modal>
<Modal bind:open={reviewOpen} title={reviewKind==='membership.request'?'核对套餐申请':'核对续期声明'} description={review?.member+' · '+review?.plan}><div class="stack"><label class="field">{reviewKind==='membership.request'?'发放有效天数（0为长期）':'续期天数'}<input type="number" min={reviewKind==='membership.request'?0:1} max="3660" bind:value={reviewDays}/></label><div class="actions">{#each [30,60,90] as d}<button class="button small" onclick={()=>reviewDays=d}>{d} 天</button>{/each}</div><label class="field">核对备注<input bind:value={reviewNote}/></label><label class="tag"><input type="checkbox" bind:checked={confirmed}/>我已人工核对约定条件，确认本次发放或续期</label><p class="hint">本系统不自动验证线下付款。操作会记录核对人及结果。</p></div><div class="modal-actions">{#if reviewKind!=='subscription.renewal.batch'}<button class="button" disabled={busy} onclick={()=>finishReview(false)}>拒绝</button>{/if}<button class="button" onclick={()=>reviewOpen=false}>取消</button><button class="button primary" disabled={busy||!confirmed} onclick={()=>finishReview(true)}>确认</button></div></Modal>
<style>.grow{flex:1;min-width:12rem}.wrap-code{overflow-wrap:anywhere}</style>
