<script lang="ts">
 import ExpandableValue from './ExpandableValue.svelte';
 import AppSelect from './Select.svelte';import Badge from './Badge.svelte';import {demo,saveRow,getRow,runAction,errorMessage} from '../store.svelte';
 let tab=$state('端口转发'),busy=$state(false),error=$state(''),result=$state<any>(null),name=$state(''),recordId=$state(''),serverId=$state(''),method=$state('tcp'),target=$state(''),count=$state(3),timeout=$state(1000),operation=$state('network.wireguard.status'),params=$state('{"id":"wg-main"}'),rules=$state('[\n  {"protocol":"tcp","listen":"0.0.0.0:8443","target":"127.0.0.1:443"}\n]'),hops=$state('[]'),chain=$state(false);
 const servers=$derived([{value:'',label:'选择服务器'},...demo.data.servers.map(row=>({value:row.id,label:row.name}))]);
 const operations=[{value:'network.wireguard.apply',label:'应用 WireGuard'},{value:'network.wireguard.remove',label:'移除 WireGuard'},{value:'network.wireguard.status',label:'读取 WireGuard 状态'},{value:'network.warp.apply',label:'应用已有 WARP 配置'},{value:'network.warp.remove',label:'移除 WARP'},{value:'network.warp.status',label:'读取 WARP 状态'},{value:'network.forward.status',label:'读取转发状态'}];
 const taskIds=$derived([...(result?.task?.id?[result.task.id]:[]),...(result?.tasks??[]).map((task:any)=>task.id),...(result?.chain?.taskIds??[])].filter(Boolean));
 function parse(value:string,array=false){const out=JSON.parse(value);if(!out||typeof out!=='object'||Array.isArray(out)!==array)throw new Error(array?'请填写 JSON 数组':'请填写 JSON 对象');return out;}
 async function act(action:string,id=serverId,parameters:Record<string,any>={}){if(busy)return;busy=true;error='';result=null;try{result=await runAction(action,id,undefined,parameters);}catch(cause){error=errorMessage(cause);}finally{busy=false;}}
 async function saveForward(apply=false){if(busy)return;busy=true;error='';result=null;try{if(!name.trim()||(!chain&&!serverId))throw new Error('填写名称并选择服务器');const row=await saveRow('forwards',{id:recordId||crypto.randomUUID(),name,serverId,status:'启用',...(chain?{hops:parse(hops,true),protocol:method,target}:{rules:parse(rules,true)})});recordId=row.id;result=apply?await runAction(chain?'forward.chain.apply':'forward.apply',row.id,'forwards'): {message:'转发配置已保存，尚未应用'};}catch(cause){error=errorMessage(cause);}finally{busy=false;}}
 async function editForward(id:string){error='';try{const row=await getRow('forwards',id);recordId=row.id;name=row.name??'';serverId=row.serverId??'';chain=Array.isArray(row.hops)&&row.hops.length>0;rules=JSON.stringify(row.rules??[],null,2);hops=JSON.stringify(row.hops??[],null,2);method=row.protocol??'tcp';target=row.target??'';}catch(cause){error=errorMessage(cause);}}
 function chooseOperation(value:string){operation=value;params=value.endsWith('.apply')?JSON.stringify({id:'wg-main',private_key:'',addresses:['10.0.0.2/32'],mtu:1420,peers:[{public_key:'',endpoint:'',allowed_ips:['10.0.0.1/32'],persistent_keepalive:25}]},null,2):'{"id":"wg-main"}';}
 async function rawAction(){try{await act(operation,serverId,parse(params));}catch(cause){error=errorMessage(cause);}}
 function loadQuality(id:string){serverId=id;}

</script>
<div class="tabs">{#each ['端口转发','WireGuard 与 WARP','网络质量'] as item}<button class:active={tab===item} onclick={()=>{tab=item;error='';result=null;}}>{item}</button>{/each}</div>
{#if error}<p class="error" role="alert">{error}</p>{/if}
{#if tab==='端口转发'}
 <p class="muted">配置 TCP / UDP 转发或 2–8 跳转发链。链从终点向入口下发，各服务器执行结果分别记录。</p>
 <div class="form-grid space-top"><label class="field">名称<input bind:value={name}/></label><label class="field">服务器<AppSelect bind:value={serverId} options={servers} aria-label="转发服务器"/></label><label class="tag"><input type="checkbox" bind:checked={chain}/>配置多跳转发链</label>
 {#if chain}<label class="field">协议<AppSelect bind:value={method} options={['tcp','udp']} aria-label="转发链协议"/></label><label class="field full">最终目标 host:port<input bind:value={target}/></label><label class="field full">跳点 JSON<textarea class="code-editor short" bind:value={hops} spellcheck="false"></textarea></label><p class="hint full">按入口到终点顺序填写对象数组，每项包含 serverId 和 listen，例如 listen 为 0.0.0.0:8443。服务器不能重复。</p>
 {:else}<label class="field full">规则 JSON<textarea class="code-editor" bind:value={rules} spellcheck="false"></textarea></label><p class="hint full">每项包含 protocol（tcp/udp）、listen（本机 IP:端口）和 target（目标 host:port）；UDP 可填 udp_idle_seconds。主控为每条规则生成标识。</p>{/if}</div>
 <div class="actions space-top"><button class="button" disabled={busy} onclick={()=>saveForward()}>保存配置</button><button class="button primary" disabled={busy} onclick={()=>saveForward(true)}>保存并应用</button><button class="button" disabled={busy} onclick={()=>{recordId='';name='';}}>新增配置</button><button class="button" disabled={busy} onclick={()=>act('forward.ledger',serverId)}>读取真实转发用量</button></div>
 <div class="stack space-top">{#each demo.data.forwards??[] as row}<div class="car-summary"><strong>{row.name}</strong><Badge value={row.status}/><div class="actions"><button class="button small" disabled={busy} onclick={()=>editForward(row.id)}>编辑</button><button class="button small" disabled={busy} onclick={()=>act(row.hops?.length?'forward.chain.apply':'forward.apply',row.id)}>应用</button>{#if row.hops?.length}<button class="button small" disabled={busy} onclick={()=>act('forward.chain.status',row.id)}>刷新逐跳状态</button>{/if}{#if !row.hops?.length}<button class="button small" disabled={busy} onclick={()=>act('forward.disable',row.id)}>停用并更新</button>{/if}</div></div>{/each}</div>
{:else if tab==='WireGuard 与 WARP'}
 <p class="muted">Agent 在目标服务器管理隧道。WARP 需要你已有的有效 WireGuard 配置，应用不会代办服务注册。</p>
 <div class="form-grid space-top"><label class="field">服务器<AppSelect bind:value={serverId} options={servers} aria-label="网络操作服务器"/></label><label class="field">操作<AppSelect value={operation} onchange={chooseOperation} options={operations} aria-label="网络操作"/></label><label class="field full">操作参数 JSON<textarea class="code-editor" bind:value={params} spellcheck="false"></textarea></label></div>
 <p class="hint">隧道应用需要 id、private_key、addresses 和 peers，密钥为 32 字节 Base64；读取和移除使用 id。应用会改变目标服务器网络运行状态，以任务回报为准。</p><button class="button primary space-top" disabled={busy||!serverId} onclick={rawAction}>提交操作</button>
{:else}
 <p class="muted">通过目标 Agent 执行 TCP 连接或 ICMP 探测。TCP 失败率表示连接失败，ICMP 才报告丢包。</p><div class="form-grid space-top"><label class="field">服务器<AppSelect value={serverId} onchange={loadQuality} options={servers} aria-label="网络质量服务器"/></label><label class="field">方法<AppSelect bind:value={method} options={['tcp','icmp']} aria-label="网络探测方法"/></label><label class="field full">探测目标<input bind:value={target} placeholder={method==='tcp'?'主机:端口':'主机名或 IP'}/></label><label class="field">次数<input type="number" min="1" max="10" bind:value={count}/></label><label class="field">每次超时 / 毫秒<input type="number" min="100" max="5000" bind:value={timeout}/></label></div><button class="button primary space-top" disabled={busy||!serverId||!target} onclick={()=>act('network.quality',serverId,{method,target,count,timeout_ms:timeout})}>立即探测</button>
 <a class="button space-top" href="/settings">Komari 监控设置</a>
{/if}
{#if result}<section class="space-top"><h3>本次请求</h3>{#if result.chain?.id}<button class="button small space-top" disabled={busy} onclick={()=>act('forward.chain.status',result.chain.id)}>刷新逐跳确认状态</button>{/if}{#if taskIds.length}<p class="hint">请求已进入任务队列，提交成功不代表节点已完成。</p><div class="actions">{#each taskIds as id}<a class="button small" href={`/tasks?detail=${encodeURIComponent(id)}`}>查看任务 {id}</a>{/each}</div>{/if}{#if typeof result.message==='string'}<p class="hint space-top" role="status">{result.message}</p>{/if}{#key result}<ExpandableValue value={result} label="响应详情" force />{/key}</section>{/if}
