<script lang="ts">
 import {formatNumber} from '../format';
 import {globeLocations,globeProject,globeGrid,renewalTimeline,renewalPrice,providerLink,type PublicProbeAsset} from '../probe-assets';
 let {nodes,showGlobe=false,showAssets=false}=$props<{nodes:PublicProbeAsset[];showGlobe?:boolean;showAssets?:boolean}>();
 let longitude=$state(0),latitude=$state(15),dragging=$state(false),lastX=0,lastY=0;
 const locations=$derived(globeLocations(nodes));const grid=$derived(globeGrid(latitude,longitude));const points=$derived(locations.map(node=>({...node,...globeProject(node.latitude,node.longitude,latitude,longitude)})));const timeline=$derived(renewalTimeline(nodes));
 function pointerDown(event:PointerEvent){if(event.button!==0)return;dragging=true;lastX=event.clientX;lastY=event.clientY;(event.currentTarget as SVGSVGElement).setPointerCapture(event.pointerId);}
 function pointerMove(event:PointerEvent){if(!dragging)return;longitude=((longitude-(event.clientX-lastX)*.5+540)%360)-180;latitude=Math.max(-80,Math.min(80,latitude+(event.clientY-lastY)*.4));lastX=event.clientX;lastY=event.clientY;}
 function focus(node:{latitude:number;longitude:number}){latitude=node.latitude;longitude=node.longitude;}
 const days=(remaining:number)=>remaining<0?`已过期 ${Math.abs(remaining)} 天`:remaining===0?'今日到期':`剩余 ${remaining} 天`;
</script>
{#if showGlobe}<section class="card padded space-top"><div class="section-head"><h2>服务器地球视图</h2><span class="muted">{locations.length} 个已填写点位</span></div><div class="globe-layout"><div><svg class="globe" class:dragging viewBox="0 0 400 400" role="img" aria-label="可旋转的服务器球面位置图，也可使用下方经纬度控件" onpointerdown={pointerDown} onpointermove={pointerMove} onpointerup={()=>dragging=false} onpointercancel={()=>dragging=false}><defs><radialGradient id="aswired-globe-shade" cx="35%" cy="28%" r="75%"><stop offset="0" stop-color="var(--nested)"/><stop offset="1" stop-color="var(--bg)"/></radialGradient></defs><circle cx="200" cy="200" r="173" fill="none" stroke="var(--line)"/><circle cx="200" cy="200" r="170" fill="url(#aswired-globe-shade)" stroke="var(--primary)" stroke-opacity=".35"/>{#each grid as line}<path d={line} fill="none" stroke="var(--primary)" stroke-opacity=".18" stroke-width=".7"/>{/each}{#each points.filter(point=>point.visible) as point}<g><circle cx={point.x} cy={point.y} r="8" fill="var(--primary)" opacity=".15"/><circle cx={point.x} cy={point.y} r="3.5" fill={point.online?'var(--primary)':'var(--muted)'} stroke="var(--bg)" stroke-width="1.5"/><title>{point.name||`服务器 ${point.index+1}`} · {formatNumber(point.latitude)}, {formatNumber(point.longitude)} · {point.online?'在线':'离线'}</title></g>{/each}</svg><div class="rotation"><label>水平旋转<input type="range" min="-180" max="180" step="1" bind:value={longitude}/></label><label>仰角<input type="range" min="-90" max="90" step="1" bind:value={latitude}/></label></div></div><div class="location-list"><p class="hint">拖动球面旋转；点位只使用管理员填写的经纬度，不根据地区推测位置。</p>{#each locations as node}<button class="location" onclick={()=>focus(node)}><span><strong>{node.name||`服务器 ${node.index+1}`}</strong><small class="muted">{formatNumber(node.latitude)}, {formatNumber(node.longitude)}</small></span><span class:offline={!node.online} class="dot"></span></button>{:else}<p class="empty">尚无公开的有效坐标。</p>{/each}{#if nodes.length>locations.length}<p class="hint space-top">{nodes.length-locations.length} 台服务器未填写有效坐标，仍可在状态列表中查看。</p>{/if}</div></div></section>{/if}
{#if showAssets}<section class="card padded space-top"><div class="section-head"><h2>续费时间轴</h2><span class="muted">按实际到期日排序</span></div><ol class="renewals">{#each timeline as node}<li class:expired={node.days<0}><div><strong>{node.name||`服务器 ${node.index+1}`}</strong><small class="muted">{new Date(node.expires).toLocaleDateString()} · {days(node.days)}</small></div><div><strong>{renewalPrice(node)}</strong><small class="muted">{node.renewal_cycle||'未填写周期'}</small></div><div>{#if providerLink(node.provider_url)}<a href={providerLink(node.provider_url)} target="_blank" rel="noreferrer">{node.provider_name||'服务商页面'}</a>{:else}<span class="muted">{node.provider_name||'未填写服务商'}</span>{/if}</div></li>{:else}<li><p class="empty">尚无公开的有效到期日。</p></li>{/each}</ol>{#if nodes.length>timeline.length}<p class="hint">{nodes.length-timeline.length} 台服务器未填写有效到期日。</p>{/if}<p class="hint space-top">仅展示管理员公开的资产信息。费用与周期照实显示，不换算汇率或估算续费金额。</p></section>{/if}
<style>.globe-layout{display:grid;grid-template-columns:minmax(240px,420px) minmax(0,1fr);gap:2rem;align-items:center}.globe{width:100%;height:auto;display:block;cursor:grab;touch-action:none}.globe.dragging{cursor:grabbing}.rotation{display:flex;gap:1rem}.rotation label{flex:1;font-size:.75rem;color:var(--muted)}.rotation input{width:100%;height:1.5rem;accent-color:var(--primary);padding:0}.location-list{max-height:380px;overflow:auto}.location{display:flex;align-items:center;justify-content:space-between;text-align:left;width:100%;padding:.75rem;border-bottom:1px solid var(--line);gap:1rem;background:transparent;color:var(--text)}.location:hover{background:var(--nested)}small{display:block;line-height:1.8}.dot{width:.45rem;height:.45rem;border-radius:50%;background:var(--primary);flex-shrink:0}.dot.offline{background:var(--muted)}.renewals{list-style:none;margin:1.3rem 0 0;padding:0 0 0 1rem;border-left:1px solid var(--line)}.renewals li{position:relative;display:grid;grid-template-columns:1fr 1fr minmax(100px,.5fr);gap:1rem;padding:1rem;border-bottom:1px solid var(--line);font-size:.85rem}.renewals li::before{content:'';position:absolute;left:-1.25rem;top:1.45rem;width:.45rem;height:.45rem;border-radius:50%;background:var(--primary)}.renewals li.expired::before{background:var(--muted)}.renewals li.expired{color:var(--muted)}.renewals .empty{grid-column:1/-1}@media(max-width:700px){.globe-layout{grid-template-columns:1fr;gap:1rem}.globe-layout>div:first-child{max-width:400px;width:100%;margin:auto}.location-list{max-height:220px}.renewals li{grid-template-columns:1fr 1fr}.renewals li>div:last-child{grid-column:1/-1}}</style>
