<script lang="ts">
 import {onDestroy} from 'svelte';import QRCode from 'qrcode';import Modal from './Modal.svelte';import {api,acceptSession,errorMessage} from '../store.svelte';
 let open=$state(false),busy=$state(false),error=$state(''),qr=$state(''),verification=$state(''),expires=$state('');let request:{requestId:string;pollSecret:string}|null=null,timer:ReturnType<typeof setTimeout>|undefined,generation=0;
 function clear(){generation++;if(timer)clearTimeout(timer);const previous=request;request=null;if(previous)fetch('/api/auth/qr/cancel',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(previous),keepalive:true}).catch(()=>{});qr='';}
 async function start(){clear();const current=++generation;open=true;busy=true;error='';try{const result=await api('/api/auth/qr/start',{method:'POST',body:JSON.stringify({deviceName:'ASWired 浏览器'})});if(current!==generation)return;request={requestId:result.requestId,pollSecret:result.pollSecret};verification=result.verificationCode;expires=result.expiresAt;qr=await QRCode.toDataURL(result.qrURL,{width:220,margin:2});timer=setTimeout(()=>poll(current),1500);}catch(cause){error=errorMessage(cause);}finally{busy=false;}}
 async function poll(current:number){if(!request||current!==generation||!open)return;try{const result=await api('/api/auth/qr/poll',{method:'POST',body:JSON.stringify(request)});if(current!==generation||!open)return;if(result.token){request=null;generation++;await acceptSession(result);open=false;return;}timer=setTimeout(()=>poll(current),1800);}catch(cause){if(current===generation){error=errorMessage(cause);request=null;}}}
 $effect(()=>{if(!open)clear();});onDestroy(clear);
</script>
<button type="button" class="button" onclick={start}>使用已登录设备扫码</button>
<Modal bind:open title="扫码登录此浏览器" description="使用已登录的手机扫描二维码，在手机上核对并输入下方确认码。">{#if busy}<p class="muted">正在生成二维码…</p>{:else if qr}<div class="qr-login"><img src={qr} alt="使用已登录手机扫描此二维码" width="220" height="220"/><p>浏览器确认码</p><strong class="verification">{verification}</strong><p class="hint">二维码有效至 {new Date(expires).toLocaleTimeString()}。只确认你本人发起的登录。</p></div>{/if}{#if error}<p class="error space-top" role="alert">{error}</p>{/if}<div class="modal-actions"><button class="button" onclick={()=>open=false}>取消</button><button class="button primary" disabled={busy} onclick={start}>重新生成</button></div></Modal>
<style>.qr-login{display:grid;justify-items:center;gap:.8rem}.qr-login img{border-radius:.5rem}.verification{font-family:ui-monospace,monospace;letter-spacing:.24em;font-size:1.8rem}</style>
