<script lang="ts">
 import AppSelect from './Select.svelte';import {demo,saveSettings,runAction,downloadAuthenticated,errorMessage,toast} from '../store.svelte';
 let config=$state<Record<string,any>>({...demo.settings.remoteBackup,provider:demo.settings.remoteBackup?.provider??'webdav'}),busy=$state(false),error=$state(''),remoteId=$state('');
 const fields=$derived(config.provider==='webdav'?[['url','WebDAV 目录 URL'],['username','用户名'],['password','密码']]:config.provider==='s3'?[['url','S3 端点 URL'],['bucket','存储桶'],['prefix','对象前缀'],['region','区域'],['accessKeyId','Access Key ID'],['secretAccessKey','Secret Access Key']]:[['clientId','Google OAuth Client ID'],['clientSecret','Google OAuth Client Secret'],['refreshToken','Google Refresh Token'],['folderId','Drive 文件夹 ID']]);
 const secret=(key:string)=>['password','secretAccessKey','clientSecret','refreshToken','accessKeyId'].includes(key);
 async function save(){const remote={...config};for(const key of Object.keys(remote))if(remote[key]==='')delete remote[key];await saveSettings({...demo.settings,remoteBackup:remote});}
 async function execute(action:string){if(busy)return;busy=true;error='';try{await save();if(action==='save'){toast('远程备份配置已保存');return;}const result=await runAction(action,undefined,undefined,action.endsWith('download')?{id:remoteId}:{});if(result.id)remoteId=result.id;if(action.endsWith('download')&&result.url)await downloadAuthenticated(result.url,'aswired-backup.zip');toast(result.message??'远程备份操作已完成');}catch(cause){error=errorMessage(cause);}finally{busy=false;}}
</script>
<section class="space-top"><h3>远程加密备份</h3><p class="hint">先配置远程存储和独立备份密码。密码用于加密备份，恢复时同样需要。</p><label class="field">存储服务<AppSelect bind:value={config.provider} options={[{value:'webdav',label:'WebDAV'},{value:'s3',label:'S3 兼容存储'},{value:'gdrive',label:'Google Drive'}]} aria-label="远程备份服务"/></label><div class="form-grid space-top">{#each fields as [key,label]}<label class="field">{label}<input type={secret(key)?'password':'text'} autocomplete="off" bind:value={config[key]} placeholder={secret(key)?'留空保留已有凭据':''}/></label>{/each}<label class="field">保留最近份数（0 为不自动清理）<input type="number" min="0" max="10000" bind:value={config.keepLast}/></label><label class="field full">备份加密密码（至少 16 位）<input type="password" autocomplete="off" bind:value={config.encryptionPassword} placeholder="留空保留已有密码"/></label></div>{#if error}<p class="error" role="alert">{error}</p>{/if}<div class="actions space-top"><button class="button" disabled={busy} onclick={()=>execute('save')}>保存远程配置</button><button class="button" disabled={busy} onclick={()=>execute('backup.remote.test')}>测试连接</button><button class="button primary" disabled={busy} onclick={()=>execute('backup.remote.upload')}>创建并上传加密备份</button></div><label class="field space-top">远程备份标识<input bind:value={remoteId}/></label><button class="button space-top" disabled={busy||!remoteId} onclick={()=>execute('backup.remote.download')}>下载并解密备份</button><p class="hint">下载后仍需通过下方恢复操作明确确认覆盖。</p><a href="/schedules" class="quiet-link">管理定时备份任务</a></section>
