<script lang="ts">
 import {onDestroy,untrack} from 'svelte';import {api,demo,errorMessage,toast} from '../store.svelte';import Icon from './Icon.svelte';import AppSelect from './Select.svelte';import Modal from './Modal.svelte';
 let {events,revision,onRefresh}=$props<{events:Record<string,any>[];revision:number;onRefresh:()=>void}>();
 type Ban={id:string;ip:string;type:string;createdAt:string;expiresAt:string;failures:number};
 let security=$state<{manual:string[];managed:string[];bans:Ban[]}|null>(null),ip=$state(''),type=$state(''),busy=$state(false),error=$state(''),allowOpen=$state(false),addresses=$state(''),confirmOpen=$state(false),pending=$state<{ip:string;permanent:boolean}|null>(null),disposed=false,request=0;
 const labels:Record<string,string>={'login.failed':'登录失败','subscription.probe':'订阅探测','security.ban':'封禁','security.unban':'解除封禁','security.allowlist.updated':'白名单变更'};
 $effect(()=>{const next=revision;untrack(()=>{void load();});});
 onDestroy(()=>{disposed=true;request++;});
 async function load(){const id=++request,user=demo.user?.id;try{const result=await api<NonNullable<typeof security>>('/api/security');if(!disposed&&id===request&&user===demo.user?.id)security=result;}catch(e){if(!disposed&&id===request)error=errorMessage(e);}}
 async function mutate(path:string,method:string,body?:unknown){if(busy)return;busy=true;error='';try{await api(path,{method,...(body?{body:JSON.stringify(body)}:{})});if(disposed)return;allowOpen=false;confirmOpen=false;await load();onRefresh();toast('安全规则已更新');}catch(e){if(!disposed)error=errorMessage(e);}finally{busy=false;}}
 function review(permanent:boolean){pending={ip:ip.trim(),permanent};confirmOpen=true;}
 const types=$derived([...new Set<string>(events.map((row:Record<string,any>)=>String(row.event??'')))]);
 const visible=$derived(events.filter((row:Record<string,any>)=>!type||row.event===type));
 function at(value:string){return value?new Date(value).toLocaleString('zh-CN',{hour12:false}):'永久';}
</script>
<button class="allowlist" onclick={()=>{addresses=(security?.manual??[]).join('\n');allowOpen=true;}}><span><Icon name="shield" size={17}/>订阅 IP 白名单</span><small>手工 {security?.manual.length??0} · 受管地址 {security?.managed.length??0}</small></button>
<div class="ban-controls"><input aria-label="封禁 IP" bind:value={ip} placeholder="输入 IP 手动封禁"/><button class="button" disabled={!ip.trim()||busy} onclick={()=>review(false)}><Icon name="shield" size={15}/>临时封禁</button><button class="button danger" disabled={!ip.trim()||busy} onclick={()=>review(true)}><Icon name="shield" size={15}/>永久封禁</button><small>临时封禁 1 小时，作用于登录与订阅入口。</small></div>
{#if error}<p class="error" role="alert">{error}</p>{/if}
<h3>当前封禁（{security?.bans.length??0}）</h3><div class="ban-table scroll"><table aria-label="当前封禁"><thead><tr><th>IP</th><th>类型</th><th>封禁时间</th><th>到期</th><th>失败次数</th><th>操作</th></tr></thead><tbody>{#each security?.bans??[] as ban(ban.id)}<tr><td>{ban.ip}</td><td>{ban.type}</td><td>{at(ban.createdAt)}</td><td>{at(ban.expiresAt)}</td><td>{ban.failures}</td><td><button class="button small" disabled={busy} onclick={()=>mutate(`/api/security/bans/${encodeURIComponent(ban.id)}`,'DELETE')}>解封</button></td></tr>{:else}<tr><td colspan="6" class="empty">暂无封禁</td></tr>{/each}</tbody></table></div>
<div class="events-heading"><h3>安全事件</h3><div><AppSelect aria-label="安全事件类型" bind:value={type} options={[{value:'',label:'全部类型'},...types.map(value=>({value,label:labels[value]??value}))]}/></div><button class="button" aria-label="刷新安全事件" onclick={()=>{void load();onRefresh();}}><Icon name="refresh" size={16}/></button></div>
<div class="scroll events-table"><table aria-label="安全事件"><thead><tr><th>时间</th><th>类型</th><th>IP</th><th>详情</th></tr></thead><tbody>{#each visible as row(row.key)}<tr><td>{row.time?at(row.time):'—'}</td><td><span class="event-type">{labels[row.event]??row.event??'系统事件'}</span></td><td>{row.ip??'—'}</td><td class="details">{row.message||row.msg||JSON.stringify(row.details??{})}</td></tr>{:else}<tr><td colspan="4" class="empty">暂无安全事件</td></tr>{/each}</tbody></table></div>
<Modal bind:open={allowOpen} title="订阅 IP 白名单" description="白名单地址免于入口封禁；仍需提供有效订阅凭据，并遵守各订阅自身的 IP 限制。"><label class="field"><span>手工地址（每行一个 IP 或 CIDR）</span><textarea rows="7" bind:value={addresses}></textarea></label><p class="hint">受管服务器地址自动加入：{security?.managed.join('、')||'暂无'}</p>{#if error}<p class="error">{error}</p>{/if}<div class="modal-actions"><button class="button" onclick={()=>allowOpen=false}>取消</button><button class="button primary" disabled={busy} onclick={()=>mutate('/api/security/allowlist','PUT',{addresses:addresses.split('\n').map(v=>v.trim()).filter(Boolean)})}>保存</button></div></Modal>
<Modal bind:open={confirmOpen} title={pending?.permanent?'永久封禁 IP':'临时封禁 IP'} description="该地址将无法通过登录与订阅入口访问。"><p>{pending?.ip} · {pending?.permanent?'永久，直到手工解封':'1 小时后自动到期'}</p>{#if error}<p class="error">{error}</p>{/if}<div class="modal-actions"><button class="button" onclick={()=>confirmOpen=false}>取消</button><button class="button danger" disabled={busy} onclick={()=>mutate('/api/security/bans','POST',pending)}>确认封禁</button></div></Modal>
<style>.allowlist{display:flex;width:100%;justify-content:space-between;gap:12px;align-items:center;padding:15px 16px;border:1px solid var(--border);background:transparent;color:var(--foreground);margin-bottom:22px}.allowlist span{display:flex;align-items:center;gap:8px;font-size:13px}.allowlist small,.event-type{font-size:11px;background:color-mix(in srgb,var(--primary) 12%,transparent);color:var(--primary);padding:3px 8px}.ban-controls{display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin-bottom:24px}.ban-controls input{width:260px;max-width:100%}.ban-controls small{font-size:11px;color:var(--muted)}h3{font-size:13px;margin:0 0 10px}.scroll{overflow:auto;border:1px solid var(--border)}.ban-table{min-height:220px;max-height:360px}.events-table{min-height:240px;max-height:450px}table{width:100%;border-collapse:collapse;min-width:740px;font-size:12px}th,td{padding:11px 13px;text-align:left;border-bottom:1px solid var(--line)}th{background:var(--nested);color:var(--muted);position:sticky;top:0;font-weight:500}td{vertical-align:top}.empty{text-align:center;color:var(--muted);padding:35px}.events-heading{display:flex;align-items:center;gap:10px;margin:25px 0 10px}.events-heading h3{margin:0}.events-heading>div{width:170px}.details{max-width:480px;overflow-wrap:anywhere;color:var(--muted)}.field textarea{width:100%}@media(max-width:700px){.allowlist{flex-wrap:wrap}.ban-controls input{width:100%}}</style>
