<script lang="ts">
 import {realityClientFormats} from '../reality-client-options';
 import {onMount,onDestroy} from 'svelte';import AppSelect from './Select.svelte';import Modal from './Modal.svelte';import Badge from './Badge.svelte';import {api,errorMessage,copy,download} from '../store.svelte';import type {Row} from '../data';
 let {presetNodeId=''}=$props<{presetNodeId?:string}>();let rows=$state<Row[]>([]),subscriptions=$state<Row[]>([]),busy=$state(false),error=$state(''),name=$state(''),subscriptionId=$state(''),nodeId=$state(''),minutes=$state(60),maxUses=$state(1),format=$state('clash'),secretURL=$state(''),showSecret=$state(false),revoking=$state<Row|null>(null),revokeOpen=$state(false);let stopped=false,timer:ReturnType<typeof setTimeout>|undefined;
 const formats=realityClientFormats;
 const nodes=$derived(subscriptions.find(row=>row.id===subscriptionId)?.nodes??[]);const link=$derived(secretURL?secretURL+'&format='+encodeURIComponent(format):'');
 async function load(){try{const result=await api('/api/temporary-subscriptions');if(stopped)return;rows=result.rows??[];subscriptions=result.subscriptions??[];if(!subscriptionId){const matching=subscriptions.find(row=>(row.nodes??[]).some((node:Row)=>node.id===presetNodeId));const sub=presetNodeId?matching:subscriptions[0];subscriptionId=sub?.id??'';nodeId=(sub?.nodes??[]).find((node:Row)=>node.id===presetNodeId)?.id??sub?.nodes?.[0]?.id??'';if(presetNodeId&&!matching)error='该节点不在你当前的有效套餐中。请选择自己的套餐和节点。';}}catch(cause){if(!stopped)error=errorMessage(cause);}}
 function chooseSubscription(id:string){subscriptionId=id;nodeId=subscriptions.find(row=>row.id===id)?.nodes?.[0]?.id??'';}
 async function create(){if(busy)return;busy=true;error='';try{const result=await api('/api/temporary-subscriptions',{method:'POST',body:JSON.stringify({name,subscriptionId,nodeId,expiresInSeconds:minutes*60,maxUses})});secretURL=result.url;showSecret=true;await load();}catch(cause){error=errorMessage(cause);}finally{busy=false;}}
 async function revoke(){if(!revoking||busy)return;busy=true;error='';try{await api('/api/temporary-subscriptions/'+encodeURIComponent(revoking.id),{method:'DELETE'});revokeOpen=false;revoking=null;await load();}catch(cause){error=errorMessage(cause);}finally{busy=false;}}
 async function poll(){await load();if(!stopped)timer=setTimeout(poll,10000);}
 onMount(()=>{poll();});onDestroy(()=>{stopped=true;if(timer)clearTimeout(timer);secretURL='';});$effect(()=>{if(!showSecret)secretURL='';});
</script>
<section class="card padded"><h2>创建临时订阅</h2><p class="muted space-top">从自己的有效套餐选择一个节点，生成有有效期和访问次数限制的链接。</p>{#if error}<p class="error" role="alert">{error}</p>{/if}<form class="space-top" onsubmit={event=>{event.preventDefault();create();}}><div class="form-grid"><label class="field">名称<input bind:value={name} maxlength="200" placeholder="可留空"/></label><label class="field">来源套餐<AppSelect value={subscriptionId} onchange={chooseSubscription} options={[{value:'',label:'选择自己的套餐'},...subscriptions.map(row=>({value:row.id,label:row.name??row.plan}))]} aria-label="临时订阅来源套餐"/></label><label class="field full">节点<AppSelect bind:value={nodeId} options={[{value:'',label:'选择节点'},...nodes.map((node:Row)=>({value:node.id,label:node.name}))]} aria-label="临时订阅节点"/></label><label class="field">有效期 / 分钟<input type="number" min="1" max="10080" step="1" required bind:value={minutes}/></label><label class="field">最大下载次数<input type="number" min="1" max="1000" step="1" required bind:value={maxUses}/></label></div><p class="hint space-top">临时链接继承原套餐的有效期、配额与白名单，使用同一成员的节点凭据。只输出所选节点的标准配置；不带可能扩展节点范围的模板或脚本。链接过期或次数用尽只停止后续配置下载，已下载配置仍受原套餐约束。</p><button class="button primary space-top" disabled={busy||!subscriptionId||!nodeId}>{busy?'创建中…':'创建临时链接'}</button></form></section>
<section class="card no-pad space-top"><div class="table-scroll"><table><thead><tr><th>名称 / 节点</th><th>到期</th><th>已用 / 上限</th><th>状态</th><th>操作</th></tr></thead><tbody>{#each rows as row}<tr><td><strong>{row.name}</strong><small class="muted">{row.nodeName}</small></td><td>{new Date(row.expiresAt).toLocaleString()}</td><td>{row.used} / {row.maxUses}</td><td><Badge value={row.status}/></td><td><button class="button small" disabled={busy||row.revoked} onclick={()=>{revoking=row;revokeOpen=true;}}>撤销</button></td></tr>{:else}<tr><td colspan="5"><div class="empty">尚无临时订阅；列表不会显示完整链接或节点凭据。</div></td></tr>{/each}</tbody></table></div></section>
<Modal bind:open={showSecret} title="保存临时订阅链接" description="完整链接只在创建后显示这一次。不要用预览打开来测试次数，实际下载会消耗次数。" wide><label class="field">客户端格式<AppSelect bind:value={format} options={formats} aria-label="临时订阅客户端格式"/></label>{#if format==='qx'}<p class="hint">Quantumult X 仅适用于未启用 Vision Flow 的节点。启用 Vision 时请选择其他格式。</p>{/if}<pre class="code-editor short space-top">{link}</pre><div class="modal-actions"><button class="button" onclick={()=>copy(link)}>复制链接</button><button class="button" onclick={()=>download('aswired-temporary-link.txt',link)}>保存链接文本</button><button class="button primary" onclick={()=>showSecret=false}>已保存</button></div></Modal>
<Modal bind:open={revokeOpen} title="撤销临时订阅" description={`撤销「${revoking?.name??''}」后，链接将无法再次下载配置。`}><div class="modal-actions"><button class="button" onclick={()=>revokeOpen=false}>取消</button><button class="button danger" disabled={busy} onclick={revoke}>确认撤销</button></div></Modal>
