<script lang="ts">
 import AppSelect from "./Select.svelte";
 import {quickRules,routingFields,ruleSummary,setRuleField,moveRule,parseRoutingJSON,csvValues} from '../routing';
 import {objectJSON,withRoutingObservers,type XrayObject} from '../xray-workbench';
 import {errorMessage} from '../store.svelte';
 import Icon from './Icon.svelte';
 import './xray-workbench.css';
 let {config,scope='',disabled=false,editing=$bindable(false),onchange}:{config:XrayObject;scope?:string;disabled?:boolean;editing?:boolean;onchange:(value:XrayObject)=>void}=$props();
 let selected=$state(-1),mode=$state<'rules'|'balancers'>('rules'),form=$state<XrayObject>({}),json=$state(''),advanced=$state(false),error=$state(''),menu=$state(false),confirm=$state(false),quickTarget=$state(''),drag=-1;
 const routing=$derived(config.routing??{}),rules=$derived(routing.rules??[]),balances=$derived(routing.balancers??[]),outs=$derived(config.outbounds??[]),items=$derived(mode==='rules'?rules:balances),current=$derived(items[selected]);
 const presets=$derived([...quickRules,{name:'家宽常用（走 WARP）',rule:{domain:['geosite:netflix','geosite:disney','geosite:openai'],outboundTag:'warp-v4'}},{name:'测速分流（走 WARP）',rule:{domain:['geosite:speedtest'],outboundTag:'warp-v4'}}]);
 const apiTag=$derived(config.api?.tag??'api');
 function isSystem(rule:XrayObject){return rule.outboundTag===apiTag;}
 function start(value:XrayObject,index=-1){if(disabled||editing)return;selected=index;form=JSON.parse(JSON.stringify(value));json=JSON.stringify(form,null,2);advanced=false;editing=true;error='';confirm=false;}
 function addRule(preset:XrayObject={}){mode='rules';menu=false;let target=preset.outboundTag??quickTarget??'';if(target==='warp-v4'&&!outs.some((out:any)=>out.tag===target))target=outs.find((out:any)=>out.protocol==='wireguard'&&out.tag.toLowerCase().includes('warp'))?.tag??'';if(!target||!outs.some((out:any)=>out.tag===target))target=outs[0]?.tag??'';start({type:'field',...(scope?{inboundTag:[scope]}:{}),...preset,outboundTag:target});}
 function addBalancer(){mode='balancers';start({tag:`balance-${crypto.randomUUID().slice(0,6)}`,selector:[],strategy:{type:'random'}});}
 function target(value:string){const next={...form};delete next.outboundTag;delete next.balancerTag;if(value.startsWith('bal:'))next.balancerTag=value.slice(4);else next.outboundTag=value.slice(4);form=next;}
 function commit(){try{const next=advanced?objectJSON(json):form;if(mode==='rules'){parseRoutingJSON(JSON.stringify({rules:[next]}));if(Boolean(next.outboundTag)===Boolean(next.balancerTag))throw new Error('请选择一个出站或均衡器');if(next.outboundTag===apiTag)throw new Error('系统 API 规则只读');if(next.outboundTag&&!outs.some((o:any)=>o.tag===next.outboundTag))throw new Error('所选出站不存在');if(next.balancerTag&&!balances.some((b:any)=>b.tag===next.balancerTag))throw new Error('所选均衡器不存在');if(!Object.entries(next).some(([key,value])=>!['type','outboundTag','balancerTag','ruleTag'].includes(key)&&(Array.isArray(value)?value.length:!!value)))throw new Error('至少填写一个匹配条件');}else{parseRoutingJSON(JSON.stringify({balancers:[next]}));if(!next.tag||balances.some((b:any,i:number)=>i!==selected&&b.tag===next.tag))throw new Error('均衡器标签为空或重复');if(!next.selector?.length||!outs.some((o:any)=>o.protocol!=='blackhole'&&next.selector.some((p:string)=>p&&o.tag.startsWith(p))))throw new Error('出站标签前缀未匹配任何有效出站');if(selected>=0&&current.tag!==next.tag&&rules.some((r:any)=>r.balancerTag===current.tag))throw new Error('均衡器被规则引用，请先调整引用再改名');}
 const values=selected<0?[...items,next]:items.map((v:any,i:number)=>i===selected?next:v);onchange(withRoutingObservers({...config,routing:{...routing,[mode==='rules'?'rules':'balancers']:values}}));selected=selected<0?values.length-1:selected;editing=false;error='';}catch(cause){error=errorMessage(cause);}}
 function remove(){if(mode==='rules'&&isSystem(current))return;if(mode==='balancers'&&rules.some((r:any)=>r.balancerTag===current.tag)){error='请先修改引用此均衡器的规则';return;}onchange({...config,routing:{...routing,[mode==='rules'?'rules':'balancers']:items.filter((_:any,i:number)=>i!==selected)}});selected=-1;confirm=false;error='';}
 function reorder(from:number,to:number){if(disabled||editing||from<0||!rules[from]||!rules[to]||isSystem(rules[from])||isSystem(rules[to]))return;onchange({...config,routing:{...routing,rules:moveRule(rules,from,to)}});selected=to;}
 function switchMode(next:'rules'|'balancers'){if(editing)return;mode=next;selected=-1;confirm=false;error='';}
 function quickAvailable(rule:XrayObject){return !rule.outboundTag||outs.some((o:any)=>o.tag===rule.outboundTag)||(rule.outboundTag==='warp-v4'&&outs.some((o:any)=>o.protocol==='wireguard'&&o.tag.toLowerCase().includes('warp')));}
</script>

<section class="workbench" aria-label="服务器路由管理">
 <div class="wb-heading"><h3>{mode==='rules'?'路由规则':'负载均衡'} <small>（共 {items.length} 个）{mode==='rules'?'· 可拖拽排序':''}</small></h3><div class="wb-actions"><details class="wb-menu" bind:open={menu}><summary class="button primary"><Icon name="plus" size={14}/>快捷添加⌄</summary><div class="wb-menu-items">{#each presets as preset}<button disabled={disabled||editing||!quickAvailable(preset.rule)} title={quickAvailable(preset.rule)?'添加至配置草稿':'请先添加对应的出站'} onclick={()=>addRule(preset.rule)}>{preset.name}{!('outboundTag' in preset.rule)?'（需选择出站）':''}</button>{/each}</div></details><button class="button" disabled={disabled||editing} onclick={()=>addRule()}>＋ 自定义规则</button><button class="button" disabled={disabled||editing} onclick={()=>{if(mode==='balancers')addBalancer();else switchMode('balancers');}}>负载均衡{mode==='balancers'?' ＋':''}</button>{#if mode==='balancers'}<button class="button" disabled={editing} onclick={()=>switchMode('rules')}>返回路由规则</button>{/if}</div></div>
 {#if scope}<p class="wb-hint">当前来自入站 {scope}：新增规则自动限定此入站，列表仍展示服务器全部规则。</p>{/if}
 <div class="wb-settings"><label class="field">域名解析策略<AppSelect aria-label="域名解析策略" value={routing.domainStrategy??'AsIs'} disabled={disabled||editing} onchange={value=>onchange({...config,routing:{...routing,domainStrategy:value}})} options={['AsIs','IPIfNonMatch','IPOnDemand']}/></label><p class="wb-hint">默认出口：{outs[0]?.tag??'未配置'}。按顺序匹配，命中第一条后转发；多个匹配条件同时满足才生效。</p></div>
 {#if error}<p class="wb-error" role="alert">{error}</p>{/if}
 <div class="wb-split"><div class="wb-list">{#each items as item,index}<div class="wb-row" class:selected={selected===index} draggable={mode==='rules'&&!disabled&&!editing&&!isSystem(item)} ondragstart={()=>drag=index} ondragover={event=>event.preventDefault()} ondrop={event=>{event.preventDefault();reorder(drag,index);drag=-1;}} ondragend={()=>drag=-1} role="group" aria-label={mode==='rules'?`规则 ${index+1}`:`均衡器 ${item.tag}`}><button class="wb-select" disabled={editing} onclick={()=>{selected=index;confirm=false;error='';}}><span aria-hidden="true">⠿</span><span class="wb-copy">{mode==='rules'?ruleSummary(item):item.tag}<small>{mode==='rules'?`→ ${item.balancerTag?'均衡 · '+item.balancerTag:item.outboundTag}`:item.strategy?.type??'random'}</small></span>{#if mode==='rules'&&isSystem(item)}<span class="wb-badge">系统</span>{/if}</button>{#if mode==='rules'}<div class="wb-order"><button aria-label={`上移规则 ${index+1}`} disabled={disabled||editing||index===0||isSystem(item)||isSystem(rules[index-1]??{})} onclick={()=>reorder(index,index-1)}>↑</button><button aria-label={`下移规则 ${index+1}`} disabled={disabled||editing||index===rules.length-1||isSystem(item)||isSystem(rules[index+1]??{})} onclick={()=>reorder(index,index+1)}>↓</button></div>{/if}</div>{:else}<div class="wb-empty">{mode==='rules'?'暂无路由规则，连接使用默认出站。':'暂无均衡器，点击“负载均衡 ＋”添加。'}</div>{/each}</div>
 <div class="wb-detail">{#if editing}<h4>{selected<0?'添加':'编辑'}{mode==='rules'?'路由规则':'均衡器'}</h4><fieldset disabled={disabled}>
 {#if advanced}<label class="field">高级 JSON<textarea class="code-editor" aria-label="路由条目 JSON" bind:value={json} spellcheck="false"></textarea></label>
 {:else if mode==='rules'}<label class="field">转发到<AppSelect aria-label="规则目标" value={form.balancerTag?'bal:'+form.balancerTag:'out:'+(form.outboundTag??'')} onchange={target} options={[...outs.map((out:any)=>({value:'out:'+out.tag,label:out.tag+' · '+out.protocol})),...balances.map((balance:any)=>({value:'bal:'+balance.tag,label:'均衡 · '+balance.tag}))]}/></label><div class="form-grid">{#each routingFields as [key,label,placeholder]}<label class="field">{label}<input aria-label={label} value={Array.isArray(form[key])?form[key].join(', '):form[key]??''} {placeholder} oninput={event=>form=setRuleField(form,key,event.currentTarget.value)}/></label>{/each}</div><p class="wb-hint">数组字段使用逗号分隔；入站标签留空表示作用于全部入站。</p>
 {:else}<div class="form-grid"><label class="field">均衡器标签<input bind:value={form.tag}/></label><label class="field">策略<AppSelect aria-label="均衡策略" value={form.strategy?.type??'random'} onchange={value=>form={...form,strategy:{...form.strategy,type:value}}} options={['random','roundRobin','leastPing','leastLoad']}/></label><label class="field">出站标签前缀<input value={(form.selector??[]).join(', ')} oninput={event=>form={...form,selector:csvValues(event.currentTarget.value)}} placeholder="proxy-, warp-"/></label><label class="field">备用出站<AppSelect aria-label="备用出站" value={form.fallbackTag??''} onchange={value=>{form={...form};if(value)form.fallbackTag=value;else delete form.fallbackTag;}} options={[{value:'',label:'不指定'},...outs.map((out:any)=>({value:out.tag,label:out.tag}))]}/></label></div><p class="wb-hint">leastPing / leastLoad 自动补充探测配置；已有探测参数会保留。</p>{/if}
 <div class="wb-actions"><button class="button" onclick={()=>{if(!advanced){json=JSON.stringify(form,null,2);advanced=true;}else{try{form=objectJSON(json);advanced=false;error='';}catch(cause){error=errorMessage(cause);}}}}>{advanced?'表单编辑':'高级 JSON'}</button><button class="button primary" onclick={commit}>采用修改</button><button class="button" onclick={()=>{editing=false;error='';selected=Math.max(-1,selected);}}>取消编辑</button></div></fieldset>
 {:else if current}<div class="wb-heading"><h4>{mode==='rules'?`规则 ${selected+1}`:current.tag}</h4><div class="wb-actions"><button class="button small" disabled={disabled||(mode==='rules'&&isSystem(current))} onclick={()=>start(current,selected)}>编辑</button><button class="button small danger" disabled={disabled||(mode==='rules'&&isSystem(current))} onclick={()=>confirm=true}>删除</button></div></div><pre aria-label="路由配置预览">{JSON.stringify(current,null,2)}</pre>{#if confirm}<div class="wb-confirm"><p class="wb-hint">从草稿删除此{mode==='rules'?'规则':'均衡器'}？保存完整配置后生效。</p><div class="wb-actions"><button class="button small" onclick={()=>confirm=false}>取消</button><button class="button small danger" disabled={disabled} onclick={remove}>确认删除条目</button></div></div>{/if}
 {:else}<div class="wb-empty">选择{mode==='rules'?'一条规则':'一个均衡器'}查看或编辑，或从上方添加。</div>{/if}</div></div>
 <p class="wb-hint">排序、添加和删除只修改当前草稿，点击“保存配置并重启”后统一应用。</p>
</section>
