export type Field={key:string;label:string;type?:string;options?:string[];value?:any;required?:boolean;adminOnly?:boolean;hint?:string;placeholder?:string;min?:number;max?:number;optional?:boolean};
export type Module={title:string;sub:string;icon:string;columns:[string,string][];fields:Field[];action?:string;readonly?:boolean};
const f=(key:string,label:string,type='text',options?:string[],value:any='',required=false):Field=>({key,label,type,options,value,required});
const name=f('name','名称','text',undefined,'',true),status=f('status','状态','select',['启用','停用'],'启用');
export const modules:Record<string,Module>={
servers:{title:'服务器',sub:'连接每一台服务器，让资源、配置与状态保持一致。',icon:'server',columns:[['name','服务器'],['status','状态'],['address','连接地址'],['core','内核'],['connection','通道'],['cost','月成本'],['expires','到期']],fields:[name,f('address','管理地址','text',undefined,'',true),{...f('connection','连接模式','select',['自动','WebSocket','HTTP','轮询'],'自动'),hint:'自动按 WebSocket → HTTP → 轮询回退。HTTP 需要主控可访问 Agent 管理端口；轮询适用于 NAT。'},{...f('agentPort','Agent 管理端口','number',undefined,23889),min:1,max:65535,optional:true},{...f('agentUrl','Agent 管理 URL（可留空）','url'),hint:'留空使用服务器地址和管理端口；仅用于 HTTP 直连。'},f('komariUUID','Komari 服务器 UUID'),f('region','地区','select',['香港','日本','新加坡','美国','德国'],'香港'),f('provider','服务商'),{...f('latitude','公开纬度（可留空）','number'),min:-90,max:90,optional:true,hint:'仅填写确认过的位置；地球视图不会按地区猜测。'},{...f('longitude','公开经度（可留空）','number'),min:-180,max:180,optional:true},f('provider_name','公开服务商名称'),f('provider_url','公开服务商网址','url'),f('expires_at','公开资产到期日','date'),{...f('renewal_price','公开续费金额（可留空）','number'),optional:true},f('renewal_currency','续费币种（例如 USD / CNY）'),f('renewal_cycle','续费周期（例如 每月 / 每年）'),{...f('limit','月流量 / GB','number',undefined,0),optional:true},{...f('cost','月成本 / 元','number',undefined,0),optional:true},f('expires','到期日','date',undefined,''),f('description','备注','textarea'),f('globalConfig','全局配置 JSON（不含入站、出站）','json')],action:'配置发布'},
inbounds:{title:'入站与客户端',sub:'使用 VLESS TCP REALITY 接入，每位成员使用独立凭据。',icon:'network',columns:[['name','入站'],['server','服务器'],['protocol','协议'],['transport','传输 / 安全'],['port','端口'],['clients','客户端'],['status','状态']],fields:[name,f('server','服务器','servers'),f('protocol','协议','fixed',undefined,'VLESS'),f('transport','传输与安全','fixed',undefined,'TCP / Reality'),f('port','监听端口','number',undefined,443,true),f('listen','监听地址（留空使用 0.0.0.0）'),f('tag','入站标识','text',undefined,'in-new',true),f('flow','Flow','select',['xtls-rprx-vision','无'],'xtls-rprx-vision'),f('sniffing','嗅探','select',['关闭','仅路由','启用'],'仅路由'),status],action:'入站校验与发布'},
outbounds:{title:'出站与中转',sub:'管理 VLESS TCP REALITY 出站，以及直连和阻断。',icon:'route',columns:[['name','出站名称'],['protocol','类型'],['server','服务器'],['target','目标'],['tag','标识'],['status','状态']],fields:[name,f('server','服务器','servers'),f('protocol','类型','select',['VLESS','Freedom','Blackhole'],'VLESS'),f('target','目标地址','text',undefined,'',false),f('tag','标识','text',undefined,'out-new'),{...f('settings','连接设置 JSON','json',undefined,{vnext:[{address:'',port:443,users:[{id:'',encryption:'none',flow:'xtls-rprx-vision'}]}]}),hint:'VLESS 填写服务器地址、端口和 UUID；直连与阻断可留空。'},{...f('streamSettings','TCP REALITY 设置 JSON','json',undefined,{network:'tcp',security:'reality',realitySettings:{serverName:'',publicKey:'',shortId:'',fingerprint:'chrome'}}),hint:'填写 REALITY SNI、公钥和 Short ID。传输固定为 tcp，安全方式固定为 reality。'},status],action:'中转配置发布'},
nodes:{title:'节点库',sub:'管理多协议节点，按国家/地区与用途组织。',icon:'layers',columns:[['name','节点'],['region','国家 / 地区'],['protocol','协议'],['source','来源'],['latency','TCP 延迟 / ms'],['tags','标签'],['status','状态']],fields:[name,f('region','国家 / 地区'),f('source','来源','text',undefined,'手动导入'),f('tags','标签，以逗号分隔'),{...f('uri','节点链接','textarea'),hint:'粘贴完整的节点分享链接。协议和连接参数由链接解析。'},status],action:'节点健康检查'},
schedules:{title:'定时任务',sub:'按指定周期执行实际任务，并在审计与任务记录中核对结果。',icon:'clock',columns:[['name','任务'],['action','操作'],['intervalSeconds','间隔 / 秒'],['enabled','启用']],fields:[name,f('action','操作','select',['source.sync','backup.create','backup.remote.upload','notification.daily','komari.sync'],'backup.create'),f('targetId','目标记录 ID（订阅源同步必填）'),f('intervalSeconds','执行间隔 / 秒（至少 30）','number',undefined,3600),f('params','操作参数 JSON','json'),f('enabled','启用定时任务','checkbox',undefined,false)]},
sources:{title:'外部订阅',sub:'同步上游多协议节点，保留来源与变更记录。',icon:'link',columns:[['name','订阅源'],['format','格式'],['nodes','节点数'],['updated','最近同步'],['sync','周期'],['status','状态']],fields:[name,f('url','订阅地址','url',undefined,'',true),f('format','解析格式','select',['自动识别','Clash Meta','V2Ray','sing-box','Surge'],'自动识别'),f('sync','同步频率','select',['每 1 小时','每 6 小时','每 12 小时','每天'],'每 6 小时'),f('intervalSeconds','自动同步间隔 / 秒（0 为关闭）','number',undefined,0),f('include','保留名称匹配'),f('exclude','排除名称匹配'),f('prefix','重命名前缀'),{...f('owner','所属成员'),adminOnly:true},{...f('fetchEndpointId','订阅抓取端点（留空为主控）','endpoints'),adminOnly:true},{...f('fetchFallback','端点失败时','select',['none','direct'],'none'),adminOnly:true},f('fallback','异常时','select',['保留上次成功快照','暂停分发'],'保留上次成功快照')],action:'外部订阅刷新'},
members:{title:'成员与权限',sub:'让每位同行者拥有自己的订阅、额度与清晰边界。',icon:'users',columns:[['name','成员'],['email','邮箱'],['application','账户系统'],['role','角色'],['plan','套餐'],['expires','到期'],['status','状态']],fields:[name,f('username','登录用户名','text',undefined,'',true),{...f('application','账户系统','select',['aswired','komari'],'aswired'),hint:'aswired：工作区管理员或成员；komari：探针管理员。用户名全局唯一，账户系统创建后不可切换。'},f('password','密码（留空保留原密码）','password'),f('email','邮箱','email'),f('role','角色','select',['管理员','成员'],'成员'),f('plan','套餐','plans'),f('limit','额度 / GB','number',undefined,200),f('expires','到期日期','date',undefined,''),{...f('behaviorLimits','行为限速 JSON（留空继承）','json'),hint:'支持 sustained 持续超速、burst 窗口命中；成员配置覆盖套餐与全局。规则格式见系统设置的行为限速。'},f('resourceQuotas','自有资源数量配额（0 为禁用）','json',undefined,{nodes:50}),f('status','状态','select',['正常','暂停'],'正常')],action:'成员凭据同步'},
certificates:{title:'证书与域名',sub:'申请、更新和部署证书，跟踪每次实际执行结果。',icon:'shield',columns:[['name','域名'],['provider','DNS 服务商'],['challenge','验证'],['expires','到期'],['status','状态']],fields:[name,f('domains','证书域名（逗号分隔）'),f('email','ACME 联系邮箱','email',undefined,'',true),f('provider','DNS 服务商','select',['Cloudflare','alidns','dnspodcn','namesilo'],'Cloudflare'),f('challenge','验证方式','select',['DNS-01','HTTP-01'],'DNS-01'),f('credential','Cloudflare DNS 编辑令牌 / Namesilo API Key','password'),f('accessKeyId','阿里云 Access Key ID'),f('accessKeySecret','阿里云 Access Key Secret','password'),f('secretId','腾讯云 Secret ID'),f('secretKey','腾讯云 Secret Key','password'),f('httpChallengeHost','HTTP 验证监听 IP','text',undefined,'0.0.0.0'),f('httpChallengePort','HTTP 验证端口（公网 80 须转发至此）','number',undefined,8080),f('serverIds','证书部署服务器','serverIds',undefined,[]),f('acmeDirectory','ACME 目录 URL（留空为 Let’s Encrypt）','url'),f('termsAgreed','我已阅读并同意所选 ACME 证书服务条款','checkbox',undefined,false),f('staging','使用测试证书（客户端不信任）','checkbox',undefined,false),f('autoRenew','自动续期','checkbox',undefined,true),f('autoDeploy','续期成功后自动部署到所选服务器','checkbox',undefined,false)],action:'申请 / 续期证书'},
tasks:{title:'任务与发布',sub:'每次变更都有预检、版本与可追溯的执行记录。',icon:'tasks',columns:[['name','任务'],['target','目标'],['type','类型'],['revision','版本'],['created','创建时间'],['duration','耗时'],['status','状态']],fields:[],readonly:true,action:'重试任务'},
notifications:{title:'通知中心',sub:'把需要关注的变化送给对的人，避免重复打扰。',icon:'bell',columns:[['name','通知规则'],['trigger','触发条件'],['channel','渠道'],['target','接收者'],['cooldown','冷却时间'],['status','状态']],fields:[name,f('trigger','触发条件'),f('channel','渠道','select',['站内','站内 + Telegram','邮件 + 站内','Webhook + Telegram'],'站内'),f('target','接收者','select',['管理员','成员'],'管理员'),f('cooldown','冷却时间','select',['10 分钟','6 小时','24 小时','按账单去重'],'6 小时'),f('message','消息模板','textarea',undefined,'{resource} 状态发生变化：{event}'),status],action:'生成测试通知'},
audit:{title:'审计日志',sub:'谁在什么时间改变了什么，记录始终清晰。',icon:'file',columns:[['name','操作'],['actor','操作者'],['resource','资源'],['action','事件'],['created','时间'],['result','结果']],fields:[],readonly:true}
};
